<?php
namespace Database\Seeders;
use App\Models\IndustryTemplate;use App\Models\PlatformAddon;use Illuminate\Database\Seeder;use Illuminate\Support\Str;
/** Provides phase26 platform seeder behavior within the WorkIntel application. */ class PlatformSeeder extends Seeder
{
 /** Handles the run operation for the current WorkIntel workflow. */ public function run():void
 {
  $addons=[
   ['name'=>'Extra Sandbox','slug'=>'extra-sandbox','description'=>'Adds one additional sandbox workspace.','category'=>'platform','pricing_mode'=>'flat','monthly_price'=>12,'unit_price'=>0,'included_quantity'=>0,'unit_name'=>'sandbox','entitlement_key'=>'limit.sandbox_workspaces','entitlement_value'=>['value'=>1],'entitlement_mode'=>'additive','eligible_plans'=>['gold','platinum']],
   ['name'=>'Extended Storage','slug'=>'extended-storage','description'=>'Metered private storage capacity for evidence, imports and documents.','category'=>'storage','pricing_mode'=>'metered','monthly_price'=>0,'unit_price'=>0.12,'included_quantity'=>10,'unit_name'=>'GB-month','entitlement_key'=>null,'entitlement_value'=>null,'entitlement_mode'=>'grant','eligible_plans'=>['silver','gold','platinum']],
   ['name'=>'Priority Support','slug'=>'priority-support','description'=>'Grants priority support to an eligible workspace.','category'=>'support','pricing_mode'=>'flat','monthly_price'=>49,'unit_price'=>0,'included_quantity'=>0,'unit_name'=>'workspace','entitlement_key'=>'feature.priority_support','entitlement_value'=>['value'=>true],'entitlement_mode'=>'grant','eligible_plans'=>['silver','gold','platinum']],
   ['name'=>'Extra Automation Capacity','slug'=>'automation-capacity','description'=>'Adds 25 active automation workflow slots.','category'=>'automation','pricing_mode'=>'flat','monthly_price'=>19,'unit_price'=>0,'included_quantity'=>0,'unit_name'=>'25 workflows','entitlement_key'=>'limit.automation_workflows','entitlement_value'=>['value'=>25],'entitlement_mode'=>'additive','eligible_plans'=>['gold','platinum']],
  ];
  foreach($addons as $row){$m=PlatformAddon::firstOrNew(['slug'=>$row['slug']]);if(!$m->exists)$m->uuid=(string)Str::uuid();$m->fill(array_merge($row,['status'=>'active','currency'=>'USD']))->save();}

  $templates=[
   ['name'=>'Software & SaaS','slug'=>'software-saas','industry'=>'Software','description'=>'Engineering/product/support organization starter structure.','blueprint'=>['departments'=>[['name'=>'Engineering','code'=>'ENG'],['name'=>'Product','code'=>'PROD'],['name'=>'Customer Success','code'=>'CS'],['name'=>'Operations','code'=>'OPS']], 'job_titles'=>[['name'=>'Software Engineer','code'=>'SWE'],['name'=>'Product Manager','code'=>'PM'],['name'=>'Customer Success Manager','code'=>'CSM']], 'custom_fields'=>[['label'=>'GitHub Username','key'=>'github_username','field_type'=>'text','visibility'=>'hr']], 'lifecycle_templates'=>[['name'=>'Software Employee Onboarding','type'=>'onboarding','items'=>[['title'=>'Provision source control access','owner_type'=>'it'],['title'=>'Assign onboarding buddy','owner_type'=>'manager'],['title'=>'Complete security training','owner_type'=>'employee']]]]]],
   ['name'=>'Agency & Professional Services','slug'=>'agency-services','industry'=>'Professional Services','description'=>'Client-service organization with delivery and finance defaults.','blueprint'=>['departments'=>[['name'=>'Client Services','code'=>'CLIENT'],['name'=>'Creative','code'=>'CREATIVE'],['name'=>'Delivery','code'=>'DELIVERY'],['name'=>'Finance','code'=>'FIN']], 'job_titles'=>[['name'=>'Account Manager','code'=>'AM'],['name'=>'Project Manager','code'=>'PJM'],['name'=>'Specialist','code'=>'SPEC']], 'expense_policies'=>[['name'=>'Client Delivery Expenses','receipt_required_over'=>25,'max_claim_amount'=>3000,'allowed_categories'=>['travel','meals','software','supplies']]]]],
   ['name'=>'Field Services','slug'=>'field-services','industry'=>'Field Services','description'=>'Operations, dispatch and field technician starter configuration.','blueprint'=>['departments'=>[['name'=>'Field Operations','code'=>'FIELD'],['name'=>'Dispatch','code'=>'DISPATCH'],['name'=>'Safety','code'=>'SAFETY']], 'job_titles'=>[['name'=>'Field Technician','code'=>'TECH'],['name'=>'Dispatcher','code'=>'DSP'],['name'=>'Safety Officer','code'=>'SAFE']], 'custom_fields'=>[['label'=>'Vehicle / Fleet ID','key'=>'fleet_id','field_type'=>'text','visibility'=>'team']], 'lifecycle_templates'=>[['name'=>'Field Worker Onboarding','type'=>'onboarding','items'=>[['title'=>'Issue PPE','owner_type'=>'hr'],['title'=>'Assign mobile device','owner_type'=>'it'],['title'=>'Complete site safety induction','owner_type'=>'employee']]]]]],
   ['name'=>'Retail Operations','slug'=>'retail-operations','industry'=>'Retail','description'=>'Store operations, scheduling and inventory-facing starter structure.','blueprint'=>['departments'=>[['name'=>'Store Operations','code'=>'STORE'],['name'=>'Inventory','code'=>'INV'],['name'=>'People Operations','code'=>'HR']], 'job_titles'=>[['name'=>'Store Manager','code'=>'STOREMGR'],['name'=>'Shift Lead','code'=>'SHIFTLEAD'],['name'=>'Associate','code'=>'ASSOC']], 'custom_fields'=>[['label'=>'Home Store','key'=>'home_store','field_type'=>'text','visibility'=>'team']]]],
  ];
  foreach($templates as $row){$m=IndustryTemplate::firstOrNew(['slug'=>$row['slug']]);if(!$m->exists)$m->uuid=(string)Str::uuid();$m->fill(array_merge($row,['version'=>1,'status'=>'active']))->save();}
 }
}
