import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const read=p=>fs.readFileSync(p,'utf8')
const parse=p=>JSON.parse(read(p))

test('compact AI supervisor state is machine-readable, bounded and resume-safe', () => {
  const state=parse('docs/ai-state/CURRENT-STATE.yaml')
  const queue=parse('docs/ai-state/COORDINATION-QUEUE.yaml')
  const claims=parse('docs/ai-state/DETERMINISTIC-CLAIMS.yaml')
  const registry=parse('benchmarks/runner/registry.json')

  assert.equal(state.compact_state_path,'docs/ai-state')
  assert.match(state.observed_main_sha,/^[0-9a-f]{40}$/i)
  for(const key of ['active_issue','active_pr','active_branch','current_milestone','milestone_status','last_completed_milestone','exact_next_safe_action','pending_runner_ids','blocked_runner_ids','current_blockers','timeout_control','response_status']) assert.ok(Object.hasOwn(state,key),`CURRENT-STATE missing ${key}`)
  assert.equal(state.timeout_control.max_consolidated_status_refreshes_per_milestone,1)
  assert.equal(state.timeout_control.tight_polling_allowed,false)
  assert.equal(state.timeout_control.rerun_on_message_delivery_timeout,false)
  assert.equal(state.timeout_control.fast_batch_default,true)
  assert.equal(state.timeout_control.routine_substep_confirmation_required,false)
  assert.equal(state.timeout_control.continuous_execution_default,true)
  assert.equal(state.timeout_control.chain_safe_milestones_without_user_reply,true)
  assert.equal(state.timeout_control.technical_blocker_confirmation_required,false)
  assert.equal(state.timeout_control.waiting_external_lane_stops_execution_window,false)
  assert.equal(state.timeout_control.readme_progress_sync_each_milestone,true)
  assert.equal(state.timeout_control.authority_drift_requires_user_confirmation,false)
  assert.equal(state.timeout_control.rehydrate_material_drift_in_same_window,true)
  assert.equal(state.timeout_control.terminal_engineering_choice_prompt_default,false)
  assert.equal(state.fallback_work_policy.enabled,true)
  assert.equal(state.fallback_work_policy.scan_before_terminal_handoff,true)
  assert.equal(state.fallback_work_policy.automatic_selection,true)
  assert.equal(state.fallback_work_policy.stop_early_to_conserve_tokens,false)
  assert.equal(state.fallback_work_policy.may_invent_product_scope,false)
  assert.equal(state.fallback_work_policy.state_pointer_only_drift_is_actionable,false)
  assert.equal(state.state_sync_policy.observed_main_sha_is_resume_anchor_not_live_authority,true)
  assert.equal(state.state_sync_policy.recursive_post_merge_state_only_pr_forbidden,true)
  assert.equal(state.state_sync_policy.pointer_only_drift_reconciled_in_memory,true)
  assert.equal(state.state_sync_policy.semantic_status_drift_requires_source_sync,true)
  assert.equal(state.state_sync_policy.merge_evidence_may_live_on_pr_issue_until_next_substantive_mutation,true)
  assert.equal(state.state_sync_policy.committed_state_is_semantic_checkpoint,true)
  assert.equal(state.state_sync_policy.live_transaction_status_read_from_github,true)
  assert.equal(state.state_sync_policy.committed_active_pr_is_live_authority,false)
  assert.equal(state.state_sync_policy.committed_active_branch_is_live_authority,false)
  assert.equal(state.state_sync_policy.readme_includes_volatile_transaction_fields,false)
  assert.equal(state.state_sync_policy.post_merge_state_only_reconciliation_required,false)
  assert.equal(state.state_sync_policy.closed_authority_issue_requires_user_prompt,false)
  assert.equal(state.state_sync_policy.last_completed_transaction_evidence_may_live_on_github,true)
  assert.deepEqual(state.fallback_work_policy.order,[
    'accepted_open_pr_repair_review_merge',
    'accepted_actionable_open_issue',
    'ci_test_security_review_audit_state_branch_repair',
    'authorized_dependency_supply_chain_maintenance',
    'docs_compact_state_readme_coordination_lifecycle_reconciliation',
    'non_destructive_evidence_diagnostics_for_existing_blocker',
  ])

  assert.ok(fs.statSync('docs/ai-state/CURRENT-STATE.yaml').size<=12*1024)
  assert.ok(fs.statSync('docs/ai-state/LAST-CHECKPOINT.md').size<=16*1024)
  assert.ok(fs.statSync('docs/ai-state/EXECUTION-JOURNAL.md').size<=32*1024)

  assert.equal(queue.non_authoritative_resume_index,true)
  assert.ok(queue.issues.some(x=>x.number===70&&x.state==='open'))
  assert.ok(queue.pull_requests.some(x=>x.number===65&&x.state==='merged'))
  if(state.active_pr===null) {
    assert.equal(state.active_branch,'main')
  } else {
    assert.ok(queue.pull_requests.some(x=>x.number===state.active_pr&&x.state==='open'))
  }
  assert.equal(new Set(claims.claims.map(x=>x.id)).size,claims.claims.length)

  const ids=new Set(registry.entries.map(x=>x.id))
  for(const id of [...state.pending_runner_ids,...state.blocked_runner_ids]) assert.ok(ids.has(id),`missing runner ${id}`)
})

test('issue 70 runner diagnostic is immediate by safety class but unauthorized and blocked', () => {
  const registry=parse('benchmarks/runner/registry.json')
  const task=registry.entries.find(x=>x.id==='RB-005')
  assert.ok(task)
  assert.equal(task.execution_policy,'immediate')
  assert.equal(task.immediate_reason,'incident-recovery-and-data-safety')
  assert.equal(task.security_critical,true)
  assert.equal(task.authorization.state,'not-authorized')
  assert.equal(task.definition_status,'blocked')
  assert.match(task.registered_source_identity.registered_head_sha,/^[0-9a-f]{40}$/i)
  assert.equal(Object.hasOwn(task.registered_source_identity,'candidate_head_sha'),false)
  assert.equal(task.result_recording.mode,'external-exact-head-envelope')
})

test('runner terminal evidence schema lives outside candidate source state', () => {
  const schema=parse('benchmarks/runner/result-envelope.schema.json')
  assert.equal(schema.properties.status.enum.includes('passed'),true)
  assert.equal(schema.properties.status.enum.includes('failed'),true)
  assert.equal(schema.properties.candidate_source_identity.properties.head_sha.pattern,'^[0-9a-fA-F]{40}$')
  assert.equal(schema.properties.evidence.items.properties.immutable.const,true)
})

test('user-facing response status carries repository, work, module and truthful progress sources', () => {
  const state=parse('docs/ai-state/CURRENT-STATE.yaml')
  const maturity=read('docs/architecture/MODULAR_MATURITY_STATUS.md')
  const responseContract=read('docs/ai-state/USER-RESPONSE-CONTRACT.md')
  const rs=state.response_status
  assert.equal(rs.repository_name,'Vertex-Systems-Network/workforce-intelligence')
  assert.ok(rs.current_work.length>0)
  assert.ok(rs.current_module.length>0)
  assert.equal(rs.bar_cells,10)
  assert.ok(Number.isInteger(rs.module_progress.percent) && rs.module_progress.percent>=0 && rs.module_progress.percent<=100)
  assert.equal(rs.overall_progress.percent,100)
  assert.equal(rs.overall_progress.scope,'active release-scope modular maturity')
  assert.ok(maturity.includes('Overall weighted modular maturity for the active release scope: 100%'))
  for(const marker of ['Repo:','Current Work:','Current Module:','Module Progress:','Overall Progress:']) assert.ok(responseContract.includes(marker))
})

test('README AI progress block stays synchronized with compact state', () => {
  const state=parse('docs/ai-state/CURRENT-STATE.yaml')
  const readme=read('README.md')
  const rs=state.response_status
  const bar=percent => {
    const cells=Math.max(0,Math.min(10,Math.round(percent/10)))
    return '█'.repeat(cells)+'░'.repeat(10-cells)
  }
  for(const marker of ['<!-- AI-PROGRESS:START -->','<!-- AI-PROGRESS:END -->','## AI Development Progress']) assert.ok(readme.includes(marker))
  assert.ok(readme.includes('**Repo:** `'+rs.repository_name+'`'))
  assert.ok(readme.includes('**Current Work:** '+rs.current_work))
  assert.ok(readme.includes('**Current Module:** '+rs.current_module))
  assert.ok(readme.includes('**Module Progress:** ['+bar(rs.module_progress.percent)+'] **'+rs.module_progress.percent+'%**'))
  assert.ok(readme.includes('**Overall Progress:** ['+bar(rs.overall_progress.percent)+'] **'+rs.overall_progress.percent+'%** — '+rs.overall_progress.scope))
  assert.ok(readme.includes('**Active Issue:** '+(state.active_issue===null?'none':'#'+state.active_issue)))
  assert.ok(readme.includes('**Next Action:** '+state.exact_next_safe_action))
  const block=readme.slice(readme.indexOf('<!-- AI-PROGRESS:START -->'),readme.indexOf('<!-- AI-PROGRESS:END -->'))
  for(const volatile of ['**Active PR:**','**Active Branch:**','**Last Completed:**']) assert.equal(block.includes(volatile),false)
})

test('Continuous Fast-Batch chains safe milestones without routine user confirmation or weakened gates', () => {
  const agents=read('AGENTS.md')
  const fastBatch=read('docs/ai-state/FAST-BATCH-EXECUTION.md')
  const responseContract=read('docs/ai-state/USER-RESPONSE-CONTRACT.md')
  const options=read('.ai/NEXT-ACTION-OPTIONS.md')
  const claims=parse('docs/ai-state/DETERMINISTIC-CLAIMS.yaml')
  assert.ok(agents.includes('Continuous autonomous execution window'))
  assert.ok(agents.includes('Milestone completion is a checkpoint'))
  assert.ok(agents.includes('Do **not** ask the user to diagnose or confirm a technical repair'))
  assert.ok(agents.includes('A single blocked lane'))
  assert.ok(fastBatch.includes('Continue chaining safe authorized milestones'))
  assert.ok(fastBatch.includes('Routine technical work never requires user confirmation'))
  assert.ok(fastBatch.includes('A blocked lane is not automatically a blocked execution window'))
  assert.ok(fastBatch.includes('Never tight-poll'))
  assert.ok(responseContract.includes('Continuous Fast-Batch is the default'))
  assert.ok(responseContract.includes('immediate selection of the next safe authorized milestone'))
  assert.ok(responseContract.includes('mandatory fallback work scan'))
  assert.ok(responseContract.includes('Do not voluntarily end a development response merely to conserve tokens/context'))
  assert.equal(responseContract.includes('execution budget is exhausted'),false)
  assert.equal(options.includes('host/session execution budget remains'),false)
  assert.equal(fastBatch.includes('host/session execution budget is exhausted'),false)
  assert.ok(options.includes('autonomous continuation'))
  assert.ok(options.includes('Do **not** present numbered 1/2/3 engineering choices'))
  assert.ok(options.includes('resume/rehydration entry'))
  assert.equal(options.includes('Respond with 1 to 3 shuffled valid next-action options'),false)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-010')?.value,true)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-011')?.value,false)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-012')?.value,false)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-013')?.value,true)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-014')?.value,false)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-015')?.value,false)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-016')?.value,true)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-017')?.value,true)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-018')?.value,true)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-019')?.value,false)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-020')?.value,true)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-021')?.value,false)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-022')?.value,false)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-023')?.value,true)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-024')?.value,false)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-025')?.value,false)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-026')?.value,false)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-027')?.value,false)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-028')?.value,false)
  assert.equal(claims.claims.find(x=>x.id==='CLAIM-029')?.value,false)
  assert.ok(agents.includes('User-prompt suppression and authority reconciliation'))
  assert.ok(agents.includes('Committed state is a semantic checkpoint, not a live transaction ledger'))
  assert.ok(agents.includes('do not hand control back merely because repository state moved'))
  assert.equal(agents.includes('GitHub Issue #50 is the current planning/product-authority gate only'),false)
  assert.ok(agents.includes('Post-merge recursion guard'))
  assert.ok(agents.includes('expected post-merge pointer drift'))
  assert.ok(fastBatch.includes('must not spawn a recursive state-only PR'))
  assert.ok(agents.includes('Mandatory fallback work scan'))
  assert.ok(agents.includes('Do not voluntarily stop merely to conserve tokens/context'))
  assert.ok(fastBatch.includes('mandatory fallback scan'))
  assert.ok(options.includes('mandatory fallback work scan'))
})
