import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { readSource } from './source-bundles.mjs'
/** Read one repository source file for M5 frontend contracts. */
const read=file=>fs.readFileSync(file,'utf8')
test('M5 Work Management module home is operational and permission-aware',()=>{const source=read('resources/js/work-management/WorkManagementHome.tsx');assert.match(source,/canAccessPage\(workspace,'projects'\)/);assert.match(source,/Promise\.allSettled/);assert.match(source,/\/api\/v1\/automations\/overview/);assert.match(source,/activeAutomations/);assert.match(source,/Work management snapshot/)})
test('M5 Projects never fabricates budget consumption',()=>{const source=read('resources/js/pages/Projects.tsx');assert.doesNotMatch(source,/tasks_count\s*\/\s*\(.*tasks_count/);assert.match(source,/Actual usage is shown in Financials/);assert.equal((source.match(/<TableWrap\b/g)||[]).length,0);assert.match(source,/projects\.financials\.members/);assert.match(source,/Overdue/)})
test('M5 Tasks uses WorkIntel workflow editing and shared filters',()=>{const source=readSource('resources/js/pages/Tasks.tsx');assert.doesNotMatch(source,/window\.prompt\(/);assert.match(source,/<FilterBar/);assert.match(source,/task-status-edit/);assert.match(source,/taskHealth/)})
test('M5 Approvals uses DataGrid V3 for request, workflow, delegation and audit lists',()=>{const source=read('resources/js/pages/Approvals.tsx');assert.equal((source.match(/<TableWrap\b/g)||[]).length,0);assert.ok((source.match(/<DataGrid\b/g)||[]).length>=4);assert.match(source,/approval-workflow-form/)})

test('M5 Automations uses DataGrid V3 and shared workflow forms',()=>{const source=read('resources/js/pages/Automations.tsx');assert.equal((source.match(/<TableWrap\b/g)||[]).length,0);assert.ok((source.match(/<DataGrid\b/g)||[]).length>=2);assert.match(source,/formId="automation-form"/);assert.match(source,/formId="hook-form"/);assert.doesNotMatch(source,/window\.prompt\(/)})

test('M5 Time & Attendance module home is operational and partial-failure tolerant',()=>{const source=read('resources/js/time-attendance/TimeAttendanceHome.tsx');assert.match(source,/Promise\.allSettled/);for(const endpoint of ['/api/v1/attendance','/api/v1/timesheets/week','/api/v1/leave','/api/v1/scheduling/week'])assert.ok(source.includes(endpoint))})
test('M5 Time & Attendance core lists use shared DataGrid and form contracts',()=>{const attendance=read('resources/js/pages/Attendance.tsx'),timesheets=read('resources/js/pages/Timesheets.tsx'),leave=read('resources/js/pages/Leave.tsx'),scheduling=read('resources/js/pages/Scheduling.tsx');for(const source of [attendance,timesheets,leave,scheduling])assert.equal((source.match(/<TableWrap\b/g)||[]).length,0);assert.ok((timesheets.match(/<DataGrid\b/g)||[]).length>=3);assert.ok((leave.match(/<FormDialog\b/g)||[]).length>=3);assert.ok((scheduling.match(/<FormDialog\b/g)||[]).length>=4)})
test('M5 legacy Shifts destination converges on canonical Scheduling',()=>{const app=read('resources/js/WorkforceApp.tsx'),palette=read('resources/js/components/CommandPalette.tsx'),catalog=read('resources/js/moduleCatalog.ts');assert.match(app,/case\s+'shifts':\s*return\s*<SchedulingHub\s+initialTab="templates"\s*\/>/);assert.match(palette,/meta\.page!=='shifts'/);assert.doesNotMatch(catalog,/pages:\['attendance','time','leave','schedule','shifts'\]/)})
test('M5 People and HR module home is operational and permission-aware',()=>{const source=read('resources/js/people-hr/PeopleHrHome.tsx');assert.match(source,/Promise\.allSettled/);for(const endpoint of ['/api/v1/people','/api/v1/hris/members','/api/v1/organization','/api/v1/performance/overview'])assert.ok(source.includes(endpoint))})
test('M5 HRIS removes native policy prompts and standardizes lifecycle forms',()=>{const source=read('resources/js/pages/Hris.tsx');assert.doesNotMatch(source,/window\.prompt\(/);assert.match(source,/policy-acknowledgement-form/);assert.match(source,/function HrisFormDialog/);assert.match(source,/return <FormDialog/)})
test('M5 Performance uses DataGrid and FormDialog for primary workflows',()=>{const source=read('resources/js/pages/Performance.tsx');assert.equal((source.match(/<TableWrap\b/g)||[]).length,0);assert.ok((source.match(/<DataGrid\b/g)||[]).length>=3);assert.ok((source.match(/<FormDialog\b/g)||[]).length>=5);assert.match(source,/performance\.goals/);assert.match(source,/performance\.reviews/);assert.match(source,/performance\.learning/)})
test('M5 People security sessions use DataGrid V3',()=>{const source=read('resources/js/pages/People.tsx');assert.equal((source.match(/<TableWrap\b/g)||[]).length,0);assert.match(source,/people\.security\.sessions\./);assert.match(source,/securitySessionColumns/)})

test('M5 Attendance policy uses WorkIntel dialogs and DataGrid for corrections',()=>{const source=read('resources/js/components/AttendancePolicyPanel.tsx');assert.doesNotMatch(source,/window\.confirm\(/);assert.equal((source.match(/<TableWrap\b/g)||[]).length,0);assert.ok((source.match(/<FormDialog\b/g)||[]).length>=2);assert.ok((source.match(/<DataGrid\b/g)||[]).length>=1);assert.ok((source.match(/<SettingRow\b/g)||[]).length>=4)})
