import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'
/** Read one repository source file for M11 frontend contracts. */
const read=file=>fs.readFileSync(file,'utf8')

test('M11 exposes global contextual Help Center separately from command search',()=>{const shell=read('resources/js/WorkforceApp.tsx'),bar=read('resources/js/components/ShellContextBar.tsx');for(const token of ['HelpCenter','F1','setHelpOpen','workintel:open-help'])assert.ok(shell.includes(token),token);for(const token of ['onOpenHelp',"t('help.find_anything')","t('help.help')"])assert.ok(bar.includes(token),token)})
test('M11 role guides are permission and module visibility aware',()=>{const c=read('resources/js/help/roleHelpCatalog.ts');for(const token of ['canAccessPage','isPageVisibleInNavigation','roleGuideForWorkspace','inferredGuideKey','workspace.permissions'])assert.ok(c.includes(token),token)})
test('M11 Start Here progress persists in existing user page preferences',()=>{const hook=read('resources/js/help/roleExperience.ts'),controller=read('app/Http/Controllers/Api/V1/UserPagePreferenceController.php');for(const token of ['role-help-v1','onboarding_completed','checklist_version','workintel:role-experience-changed'])assert.ok(hook.includes(token),token);for(const token of ['settings.onboarding_completed','settings.help_seen','settings.role_seen'])assert.ok(controller.includes(token),token)})
test('M11 surfaces Start Here on overview and relevant module homes',()=>{assert.match(read('resources/js/pages/Overview.tsx'),/RoleStartHere/);assert.match(read('resources/js/components/ModuleHome.tsx'),/RoleStartHere/);const start=read('resources/js/components/RoleStartHere.tsx');for(const token of ["t('help.personal_checklist')","t('help.start_here')","t('help.mark_complete'"])assert.ok(start.includes(token),token)})
test('M11 Help Center provides localized page context search onboarding and role handbook',()=>{const h=read('resources/js/components/HelpCenter.tsx');for(const token of ["t('help.this_page')","t('help.start_here')","t('help.role_handbook')","t('help.related_destinations')","t('help.what_good_looks_like')","t('help.accessible_work_areas')"])assert.ok(h.includes(token),token)})
test('M11 core Help Center chrome is translated for Turkish Russian Urdu and Arabic',()=>{const c=read('resources/js/i18n/locales/help.ts');for(const token of ['Yardım Merkezi','Центр помощи','مدد مرکز','مركز المساعدة','help.module_step_three','help.welcome_text'])assert.ok(c.includes(token),token)})
test('M11 first run guidance is non-blocking persistent and opens Start Here through the shell',()=>{const first=read('resources/js/components/FirstRunGuide.tsx'),shell=read('resources/js/WorkforceApp.tsx');for(const token of ['experience.state.seen',"dismissHelp('first-run')",'workintel:open-help',"tab:'start'"])assert.ok(first.includes(token),token);assert.ok(shell.includes('FirstRunGuide'))})
test('M11 contextual empty states use one shared shell help recovery contract',()=>{const ds=read('resources/js/design-system/index.tsx'),home=read('resources/js/work-management/WorkManagementHome.tsx');for(const token of ['contextualHelp','workintel:open-help',"t('help.open_context')"])assert.ok(ds.includes(token),token);assert.ok(home.includes('contextualHelp'))})
test('M11 RTL reduced-motion and browser keyboard certification contracts are registered',()=>{const css=read('resources/js/design-system/toolkit.css'),e2e=read('tests/e2e/authenticated-platform.spec.mjs');for(const token of ['[dir="rtl"] .ui-help-directional-icon','ui-first-run-guide','prefers-reduced-motion:reduce'])assert.ok(css.includes(token),token);for(const token of ['M11 Help Center keyboard and RTL flow','F1','getByRole(\'dialog\''])assert.ok(e2e.includes(token),token)})
