<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Models\PartnerWorkspace;use App\Models\PlatformAddon;use App\Models\Workspace;use App\Models\WorkspaceAddon;use App\Services\Platform\AddonService;use App\Services\Platform\PartnerService;use App\Services\Platform\WorkspaceProvisioningService;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Validation\Rule;
/** Provides partner api controller behavior within the WorkIntel application. */ class PartnerApiController extends Controller
{
 /** Handles the me operation for the current WorkIntel workflow. */ public function me(Request $r):JsonResponse{$a=$r->attributes->get('partnerAccount');$k=$r->attributes->get('partnerApiKey');return response()->json(['partner'=>['id'=>$a->id,'uuid'=>$a->uuid,'name'=>$a->name,'slug'=>$a->slug,'type'=>$a->type],'api_key'=>['name'=>$k->name,'scopes'=>$k->scopes,'expires_at'=>$k->expires_at?->toIso8601String()]]);}
 /** Handles the workspaces operation for the current WorkIntel workflow. */ public function workspaces(Request $r):JsonResponse{$a=$r->attributes->get('partnerAccount');$rows=PartnerWorkspace::with('workspace.subscription.plan')->where('partner_account_id',$a->id)->where('status','active')->get()->map(fn($x)=>['relationship'=>$x->relationship_type,'external_reference'=>$x->external_reference,'workspace'=>['id'=>$x->workspace->id,'uuid'=>$x->workspace->getAttribute('uuid'),'name'=>$x->workspace->name,'slug'=>$x->workspace->slug,'type'=>$x->workspace->workspace_type,'status'=>$x->workspace->status,'plan'=>$x->workspace->subscription?->plan?->slug]]);return response()->json(['data'=>$rows]);}
 /** Creates create workspace data for the requested workflow. */ public function createWorkspace(Request $r,WorkspaceProvisioningService $provision,PartnerService $partner):JsonResponse{$a=$r->attributes->get('partnerAccount');$billing=$a->billingWorkspace;abort_unless($billing,422,'Partner billing workspace is not available.');$d=$r->validate(['name'=>'required|string|max:140','plan_slug'=>['nullable',Rule::in(['free','silver','gold','platinum'])],'external_reference'=>'nullable|string|max:120']);$workspace=$provision->createManagedWorkspace($billing,$a->owner,$d['name'],$d['plan_slug']??'free');$partner->attachWorkspace($a,$workspace,'managed',$d['external_reference']??null);return response()->json(['data'=>['id'=>$workspace->id,'name'=>$workspace->name,'slug'=>$workspace->slug,'status'=>$workspace->status]],201);}
 /** Handles the addons operation for the current WorkIntel workflow. */ public function addons(Request $r):JsonResponse{return response()->json(['data'=>PlatformAddon::where('status','active')->orderBy('name')->get()]);}
 /** Handles the workspace usage operation for the current WorkIntel workflow. */ public function workspaceUsage(Request $r,int $workspaceId,AddonService $addons):JsonResponse{$a=$r->attributes->get('partnerAccount');$link=PartnerWorkspace::where('partner_account_id',$a->id)->where('workspace_id',$workspaceId)->where('status','active')->firstOrFail();return response()->json(['workspace_id'=>$workspaceId,'addon_estimate'=>$addons->monthlyEstimate($link->workspace)]);}
 /** Handles the record usage operation for the current WorkIntel workflow. */ public function recordUsage(Request $r,int $workspaceId,WorkspaceAddon $workspaceAddon,AddonService $addons):JsonResponse{$a=$r->attributes->get('partnerAccount');$link=PartnerWorkspace::where('partner_account_id',$a->id)->where('workspace_id',$workspaceId)->where('status','active')->firstOrFail();abort_unless((int)$workspaceAddon->workspace_id===(int)$workspaceId,404);$d=$r->validate(['metric'=>'required|string|max:80','quantity'=>'required|numeric|min:0.0001','idempotency_key'=>'required|string|max:160','metadata'=>'nullable|array']);return response()->json(['data'=>$addons->recordUsage($link->workspace,$workspaceAddon,$d['metric'],(float)$d['quantity'],$d['idempotency_key'],$d['metadata']??[])],201);}
}
