<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use App\Models\AttendanceRecord;
use App\Models\Project;
use App\Models\ReportRun;
use App\Models\Task;
use App\Models\TimeEntry;
use App\Models\WorkspaceMember;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;
/** Provides public api controller behavior within the WorkIntel application. */ class PublicApiController extends Controller
{
    /** Handles the me operation for the current WorkIntel workflow. */ public function me(Request $request): JsonResponse { $w=$request->attributes->get('workspace');$key=$request->attributes->get('workspaceApiKey');return response()->json(['workspace'=>['id'=>$w->id,'name'=>$w->name,'slug'=>$w->slug,'timezone'=>$w->timezone,'currency'=>$w->currency],'api_key'=>['name'=>$key->name,'scopes'=>$key->scopes,'expires_at'=>$key->expires_at?->toIso8601String()]]); }
    /** Handles the people operation for the current WorkIntel workflow. */ public function people(Request $request): JsonResponse { $w=$request->attributes->get('workspace');$rows=WorkspaceMember::with(['user','department'])->where('workspace_id',$w->id)->where('status','active')->orderBy('id')->limit(min(500,max(1,$request->integer('limit',100))))->get()->map(fn($m)=>['id'=>$m->id,'name'=>trim($m->user->first_name.' '.$m->user->last_name),'email'=>$m->user->email,'department'=>$m->department?->name,'job_title'=>$m->job_title,'employment_type'=>$m->employment_type,'status'=>$m->status]);return response()->json(['data'=>$rows]); }
    /** Handles the projects operation for the current WorkIntel workflow. */ public function projects(Request $request): JsonResponse { $w=$request->attributes->get('workspace');return response()->json(['data'=>Project::where('workspace_id',$w->id)->orderByDesc('updated_at')->limit(min(500,max(1,$request->integer('limit',100))))->get(['id','client_id','name','code','status','priority','start_date','end_date','billable','updated_at'])]); }
    /** Handles the tasks operation for the current WorkIntel workflow. */ public function tasks(Request $request): JsonResponse { $w=$request->attributes->get('workspace');$q=Task::where('workspace_id',$w->id);if($request->filled('project_id'))$q->where('project_id',$request->integer('project_id'));return response()->json(['data'=>$q->orderByDesc('updated_at')->limit(min(500,max(1,$request->integer('limit',100))))->get(['id','project_id','parent_id','title','status','priority','estimated_minutes','due_at','billable','completed_at','updated_at'])]); }
    /** Handles the time entries operation for the current WorkIntel workflow. */ public function timeEntries(Request $request): JsonResponse { $w=$request->attributes->get('workspace');$q=TimeEntry::where('workspace_id',$w->id)->with(['member.user','project:id,name','task:id,title']);if($request->filled('member_id'))$q->where('member_id',$request->integer('member_id'));if($request->filled('date_from'))$q->whereDate('date','>=',$request->string('date_from'));if($request->filled('date_to'))$q->whereDate('date','<=',$request->string('date_to'));return response()->json(['data'=>$q->latest('started_at')->limit(min(1000,max(1,$request->integer('limit',200))))->get()->map(fn($x)=>['id'=>$x->id,'member_id'=>$x->member_id,'employee'=>$x->member?->user?->first_name.' '.$x->member?->user?->last_name,'project_id'=>$x->project_id,'project'=>$x->project?->name,'task_id'=>$x->task_id,'task'=>$x->task?->title,'date'=>$x->date?->toDateString(),'started_at'=>$x->started_at?->toIso8601String(),'ended_at'=>$x->ended_at?->toIso8601String(),'duration_seconds'=>$x->duration_seconds,'billable'=>$x->billable,'source'=>$x->source,'approval_status'=>$x->approval_status,'note'=>$x->note])]); }
    /** Handles the store time entry operation for the current WorkIntel workflow. */ public function storeTimeEntry(Request $request): JsonResponse
    {
        $w=$request->attributes->get('workspace');$data=$request->validate(['member_id'=>['required','integer'],'project_id'=>['required','integer'],'task_id'=>['nullable','integer'],'started_at'=>['required','date'],'ended_at'=>['required','date','after:started_at'],'billable'=>['nullable','boolean'],'note'=>['nullable','string','max:2000']]);
        $member=WorkspaceMember::where('workspace_id',$w->id)->whereKey($data['member_id'])->firstOrFail();$project=Project::where('workspace_id',$w->id)->whereKey($data['project_id'])->firstOrFail();$task=null;if(!empty($data['task_id'])){$task=Task::where('workspace_id',$w->id)->whereKey($data['task_id'])->firstOrFail();if($task->project_id!==$project->id)throw ValidationException::withMessages(['task_id'=>['Task does not belong to project.']]);}
        $start=\Carbon\Carbon::parse($data['started_at']);$end=\Carbon\Carbon::parse($data['ended_at']);if($end->diffInHours($start)>24)throw ValidationException::withMessages(['ended_at'=>['A single time entry cannot exceed 24 hours.']]);
        $overlap=TimeEntry::where('workspace_id',$w->id)->where('member_id',$member->id)->where(fn($q)=>$q->whereBetween('started_at',[$start,$end])->orWhereBetween('ended_at',[$start,$end])->orWhere(fn($x)=>$x->where('started_at','<=',$start)->where('ended_at','>=',$end)))->exists();if($overlap)throw ValidationException::withMessages(['started_at'=>['This entry overlaps existing tracked time.']]);
        $entry=TimeEntry::create(['workspace_id'=>$w->id,'member_id'=>$member->id,'project_id'=>$project->id,'task_id'=>$task?->id,'date'=>$start->toDateString(),'started_at'=>$start,'ended_at'=>$end,'duration_seconds'=>$start->diffInSeconds($end),'billable'=>$data['billable']??$project->billable,'source'=>'api','approval_status'=>'draft','note'=>$data['note']??null]);return response()->json(['data'=>$entry],201);
    }
    /** Handles the report runs operation for the current WorkIntel workflow. */ public function reportRuns(Request $request): JsonResponse { $w=$request->attributes->get('workspace');return response()->json(['data'=>ReportRun::where('workspace_id',$w->id)->latest('created_at')->limit(min(200,max(1,$request->integer('limit',50))))->get(['id','uuid','name','dataset','status','row_count','summary','created_at','completed_at'])]); }
    /** Handles the attendance operation for the current WorkIntel workflow. */ public function attendance(Request $request): JsonResponse { $w=$request->attributes->get('workspace');$q=AttendanceRecord::where('workspace_id',$w->id);if($request->filled('member_id'))$q->where('member_id',$request->integer('member_id'));if($request->filled('date_from'))$q->whereDate('date','>=',$request->string('date_from'));if($request->filled('date_to'))$q->whereDate('date','<=',$request->string('date_to'));return response()->json(['data'=>$q->latest('date')->limit(min(1000,max(1,$request->integer('limit',200))))->get()]); }
}
