<?php
namespace App\Services\Enterprise;
use App\Models\User;use App\Models\UserMfaMethod;use Illuminate\Support\Facades\Crypt;use Illuminate\Support\Str;
/** Provides totp service behavior within the WorkIntel application. */ class TotpService{
 /** Handles the begin operation for the current WorkIntel workflow. */ public function begin(User $user):array{$secret=$this->base32Encode(random_bytes(20));$recovery=collect(range(1,10))->map(fn()=>strtoupper(Str::random(5).'-'.Str::random(5)))->all();$method=UserMfaMethod::updateOrCreate(['user_id'=>$user->id,'type'=>'totp'],['secret_encrypted'=>Crypt::encryptString($secret),'recovery_code_hashes'=>array_map(fn($c)=>hash('sha256',strtoupper($c)),$recovery),'confirmed_at'=>null,'last_used_at'=>null]);$issuer=rawurlencode(config('app.name','WorkIntel'));$label=rawurlencode(config('app.name','WorkIntel').':'.$user->email);return ['method_id'=>$method->id,'secret'=>$secret,'otpauth_uri'=>"otpauth://totp/{$label}?secret={$secret}&issuer={$issuer}&algorithm=SHA1&digits=6&period=30",'recovery_codes'=>$recovery];}
 /** Handles the confirm operation for the current WorkIntel workflow. */ public function confirm(User $user,string $code):bool{$m=$this->method($user);if(!$m||!$this->verifyTotp(Crypt::decryptString($m->secret_encrypted),$code))return false;$m->update(['confirmed_at'=>now(),'last_used_at'=>now()]);return true;}
 /** Handles the verify operation for the current WorkIntel workflow. */ public function verify(User $user,string $code):bool{$m=$this->method($user);if(!$m||!$m->confirmed_at)return false;$normalized=strtoupper(trim($code));if(preg_match('/^\d{6}$/',$normalized)&&$this->verifyTotp(Crypt::decryptString($m->secret_encrypted),$normalized)){$m->update(['last_used_at'=>now()]);return true;}$hash=hash('sha256',$normalized);$codes=$m->recovery_code_hashes??[];$idx=array_search($hash,$codes,true);if($idx===false)return false;unset($codes[$idx]);$m->update(['recovery_code_hashes'=>array_values($codes),'last_used_at'=>now()]);return true;}
 /** Handles the enabled operation for the current WorkIntel workflow. */ public function enabled(User $user):bool{return (bool)$this->method($user)?->confirmed_at;}
 /** Handles the method operation for the current WorkIntel workflow. */ public function method(User $user):?UserMfaMethod{return UserMfaMethod::where('user_id',$user->id)->where('type','totp')->first();}
 /** Handles the verify totp operation for the current WorkIntel workflow. */ private function verifyTotp(string $secret,string $code):bool{$counter=(int)floor(time()/30);foreach([-1,0,1] as $drift)if(hash_equals($this->hotp($this->base32Decode($secret),$counter+$drift),$code))return true;return false;}
 /** Handles the hotp operation for the current WorkIntel workflow. */ private function hotp(string $key,int $counter):string{$bin=pack('N*',0).pack('N*',$counter);$hash=hash_hmac('sha1',$bin,$key,true);$offset=ord($hash[19])&0xf;$value=((ord($hash[$offset])&0x7f)<<24)|((ord($hash[$offset+1])&0xff)<<16)|((ord($hash[$offset+2])&0xff)<<8)|(ord($hash[$offset+3])&0xff);return str_pad((string)($value%1000000),6,'0',STR_PAD_LEFT);}
 /** Handles the base32 encode operation for the current WorkIntel workflow. */ private function base32Encode(string $data):string{$alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$bits='';foreach(str_split($data) as $c)$bits.=str_pad(decbin(ord($c)),8,'0',STR_PAD_LEFT);$out='';foreach(str_split($bits,5) as $chunk){$chunk=str_pad($chunk,5,'0');$out.=$alphabet[bindec($chunk)];}return $out;}
 /** Handles the base32 decode operation for the current WorkIntel workflow. */ private function base32Decode(string $input):string{$alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$bits='';foreach(str_split(strtoupper(preg_replace('/[^A-Z2-7]/','',$input))) as $c){$p=strpos($alphabet,$c);if($p===false)continue;$bits.=str_pad(decbin($p),5,'0',STR_PAD_LEFT);}$out='';foreach(str_split($bits,8) as $chunk)if(strlen($chunk)===8)$out.=chr(bindec($chunk));return $out;}
}
