import {copy,type PageCopyRegistry} from './core'

/** Help short terms used by the legacy page-copy translator. */
export const helpTerms:PageCopyRegistry={
  'Checklist':copy('Kontrol listesi','Чек-лист','چیک لسٹ','قائمة التحقق'),
  'Help':copy('Yardım','Помощь','مدد','مساعدة'),
}

/** Help exact phrases used by the legacy page-copy translator. */
export const helpPhrases:PageCopyRegistry={
  'Start lifecycle checklist':copy('Yaşam döngüsü kontrol listesini başlat','Запустить чек-лист жизненного цикла','لائف سائیکل چیک لسٹ شروع کریں','بدء قائمة دورة الحياة'),
  'Checklist item…':copy('Kontrol listesi öğesi…','Пункт чек-листа…','چیک لسٹ آئٹم…','عنصر قائمة التحقق…'),
  'No checklist items.':copy('Kontrol listesi öğesi yok.','Нет пунктов чек-листа.','کوئی چیک لسٹ آئٹم نہیں۔','لا توجد عناصر في قائمة التحقق.'),
  'Safety & checklist forms':copy('Güvenlik ve kontrol listesi formları','Формы безопасности и чек-листов','حفاظتی اور چیک لسٹ فارمز','نماذج السلامة وقوائم التحقق'),
  'Set up your workspace for reliable operations':copy('Çalışma alanınızı güvenilir operasyonlar için kurun','Настройте рабочее пространство для надёжной работы','اپنے ورک اسپیس کو قابلِ اعتماد آپریشنز کے لیے ترتیب دیں','أعِد مساحة العمل لعمليات موثوقة'),
  'Start with workspace identity and access, then configure the operating modules your team will use every day.':copy('Çalışma alanı kimliği ve erişimle başlayın, ardından ekibinizin her gün kullanacağı operasyon modüllerini yapılandırın.','Начните с идентификации рабочего пространства и доступа, затем настройте рабочие модули для ежедневной работы команды.','ورک اسپیس شناخت اور رسائی سے شروع کریں، پھر وہ آپریشنل ماڈیولز ترتیب دیں جو ٹیم روزانہ استعمال کرے گی۔','ابدأ بهوية مساحة العمل والوصول، ثم اضبط الوحدات التشغيلية التي سيستخدمها فريقك يوميًا.'),
  'Workspace settings reflect your organization.':copy('Çalışma alanı ayarları kuruluşunuzu yansıtır.','Настройки рабочего пространства отражают вашу организацию.','ورک اسپیس کی ترتیبات آپ کی تنظیم کی عکاسی کرتی ہیں۔','تعكس إعدادات مساحة العمل مؤسستك.'),
  'Members have intentional roles and scopes.':copy('Üyelerin bilinçli olarak atanmış rolleri ve kapsamları vardır.','У участников осознанно назначены роли и области доступа.','اراکین کے کردار اور اسکوپس ارادی طور پر مقرر ہیں۔','للأعضاء أدوار ونطاقات مقصودة.'),
  'Core work, time and reporting modules are ready for use.':copy('Temel iş, zaman ve raporlama modülleri kullanıma hazırdır.','Основные модули работы, времени и отчётности готовы к использованию.','بنیادی کام، وقت اور رپورٹنگ ماڈیولز استعمال کے لیے تیار ہیں۔','وحدات العمل والوقت والتقارير الأساسية جاهزة للاستخدام.'),
  'Keep workspace configuration understandable and safe':copy('Çalışma alanı yapılandırmasını anlaşılır ve güvenli tutun','Сохраняйте конфигурацию понятной и безопасной','ورک اسپیس کنفیگریشن کو واضح اور محفوظ رکھیں','حافظ على إعداد مساحة العمل واضحًا وآمنًا'),
  'Validate access, modules and settings before supporting daily operations.':copy('Günlük operasyonları desteklemeden önce erişimi, modülleri ve ayarları doğrulayın.','Проверьте доступ, модули и настройки перед поддержкой ежедневных операций.','روزمرہ آپریشنز سے پہلے رسائی، ماڈیولز اور ترتیبات کی تصدیق کریں۔','تحقق من الوصول والوحدات والإعدادات قبل دعم العمليات اليومية.'),
  'Permissions are intentional.':copy('İzinler bilinçli olarak atanmıştır.','Разрешения назначены осознанно.','اجازتیں ارادی ہیں۔','الصلاحيات مقصودة.'),
  'Workspace configuration is supportable.':copy('Çalışma alanı yapılandırması sürdürülebilir biçimde desteklenebilir.','Конфигурация рабочего пространства пригодна для сопровождения.','ورک اسپیس کنفیگریشن قابلِ معاونت ہے۔','إعداد مساحة العمل قابل للدعم.'),
  'Operational modules expose the right data.':copy('Operasyon modülleri doğru verileri gösterir.','Рабочие модули показывают нужные данные.','آپریشنل ماڈیولز درست ڈیٹا دکھاتے ہیں۔','تعرض الوحدات التشغيلية البيانات الصحيحة.'),
  'Run the team from work, approvals and time signals':copy('Ekibi iş, onay ve zaman sinyalleri üzerinden yönetin','Управляйте командой через работу, согласования и сигналы времени','ٹیم کو کام، منظوریوں اور وقت کے سگنلز سے چلائیں','أدِر الفريق من خلال العمل والموافقات وإشارات الوقت'),
  'Use the manager path to keep delivery, team workload and exceptions visible without browsing administrative areas.':copy('Yönetim alanlarını dolaşmadan teslimatı, ekip iş yükünü ve istisnaları görünür tutmak için yönetici yolunu kullanın.','Используйте путь менеджера, чтобы видеть выполнение, нагрузку команды и исключения без перехода в административные разделы.','ایڈمن علاقوں میں گئے بغیر ڈیلیوری، ٹیم ورک لوڈ اور استثناؤں کو دیکھنے کے لیے مینیجر راستہ استعمال کریں۔','استخدم مسار المدير لإبقاء التسليم وعبء عمل الفريق والاستثناءات مرئية دون تصفح مناطق الإدارة.'),
  'Work is assigned and prioritized.':copy('İş atanmış ve önceliklendirilmiştir.','Работа назначена и расставлена по приоритетам.','کام تفویض اور ترجیحی ہے۔','العمل مُسند ومُرتب حسب الأولوية.'),
  'Approvals and attendance exceptions are visible.':copy('Onaylar ve devam istisnaları görünürdür.','Согласования и исключения посещаемости видимы.','منظوریاں اور حاضری کے استثنا واضح ہیں۔','الموافقات واستثناءات الحضور مرئية.'),
  'Team communication stays linked to work.':copy('Ekip iletişimi işle bağlantılı kalır.','Командная коммуникация остаётся связанной с работой.','ٹیم کی گفتگو کام سے منسلک رہتی ہے۔','يبقى تواصل الفريق مرتبطًا بالعمل.'),
  'Establish clean people and lifecycle operations':copy('Temiz çalışan ve yaşam döngüsü operasyonları oluşturun','Выстройте чистые процессы по людям и жизненному циклу','لوگوں اور لائف سائیکل کے صاف آپریشنز قائم کریں','أنشئ عمليات واضحة للأشخاص ودورة حياتهم'),
  'Start with people records and organization structure, then validate attendance, leave and performance workflows.':copy('Çalışan kayıtları ve organizasyon yapısıyla başlayın; ardından devam, izin ve performans iş akışlarını doğrulayın.','Начните с записей сотрудников и структуры организации, затем проверьте процессы посещаемости, отпусков и эффективности.','لوگوں کے ریکارڈ اور تنظیمی ساخت سے شروع کریں، پھر حاضری، رخصت اور کارکردگی کے ورک فلو کی تصدیق کریں۔','ابدأ بسجلات الأشخاص وهيكل المؤسسة، ثم تحقق من سير عمل الحضور والإجازات والأداء.'),
  'People records are complete within your scope.':copy('Çalışan kayıtları kapsamınız içinde eksiksizdir.','Записи сотрудников полны в пределах вашей области доступа.','آپ کے اسکوپ میں لوگوں کے ریکارڈ مکمل ہیں۔','سجلات الأشخاص مكتملة ضمن نطاقك.'),
  'Organization relationships are understandable.':copy('Organizasyon ilişkileri anlaşılırdır.','Организационные связи понятны.','تنظیمی تعلقات قابلِ فہم ہیں۔','العلاقات التنظيمية مفهومة.'),
  'HR exceptions and development workflows are visible.':copy('İK istisnaları ve gelişim iş akışları görünürdür.','Исключения HR и процессы развития видимы.','HR استثنا اور ترقی کے ورک فلو واضح ہیں۔','استثناءات الموارد البشرية ومسارات التطوير مرئية.'),
  'Prepare payroll from approved workforce evidence':copy('Bordroyu onaylı işgücü kanıtlarından hazırlayın','Готовьте расчёт зарплаты на основе утверждённых данных','منظور شدہ ورک فورس شواہد سے پے رول تیار کریں','جهّز الرواتب من أدلة القوى العاملة المعتمدة'),
  'Validate attendance and approved time before operating payroll, compliance and finance workflows.':copy('Bordro, uyumluluk ve finans iş akışlarını yürütmeden önce devam ve onaylı zamanı doğrulayın.','Проверьте посещаемость и утверждённое время до запуска процессов зарплаты, комплаенса и финансов.','پے رول، تعمیل اور مالی ورک فلو سے پہلے حاضری اور منظور شدہ وقت کی تصدیق کریں۔','تحقق من الحضور والوقت المعتمد قبل تشغيل مسارات الرواتب والامتثال والمالية.'),
  'Time inputs are reviewable.':copy('Zaman girdileri incelenebilir.','Данные времени доступны для проверки.','وقت کے اندراجات قابلِ جائزہ ہیں۔','مدخلات الوقت قابلة للمراجعة.'),
  'Payroll runs use approved evidence.':copy('Bordro çalıştırmaları onaylı kanıtları kullanır.','Расчёты зарплаты используют утверждённые данные.','پے رول رنز منظور شدہ شواہد استعمال کرتے ہیں۔','تستخدم عمليات الرواتب أدلة معتمدة.'),
  'Compliance and finance outputs are discoverable.':copy('Uyumluluk ve finans çıktıları kolayca bulunabilir.','Результаты комплаенса и финансов легко находятся.','تعمیل اور مالی نتائج آسانی سے مل جاتے ہیں۔','مخرجات الامتثال والمالية سهلة الاكتشاف.'),
  'Know what to do, when to do it, and where to find your records':copy('Ne yapacağınızı, ne zaman yapacağınızı ve kayıtlarınızı nerede bulacağınızı bilin','Знайте, что делать, когда и где находить свои записи','جانیں کیا کرنا ہے، کب کرنا ہے اور اپنے ریکارڈ کہاں ملیں گے','اعرف ما الذي تفعله ومتى وأين تجد سجلاتك'),
  'Your Start Here path focuses on assigned work, attendance, schedule, time, requests and collaboration.':copy('Buradan Başla yolunuz atanmış iş, devam, planlama, zaman, talepler ve işbirliğine odaklanır.','Ваш путь «Начать здесь» сосредоточен на назначенной работе, посещаемости, расписании, времени, запросах и совместной работе.','آپ کا یہاں سے شروع کریں راستہ تفویض شدہ کام، حاضری، شیڈول، وقت، درخواستوں اور تعاون پر مرکوز ہے۔','يركز مسار «ابدأ من هنا» على العمل المسند والحضور والجدول والوقت والطلبات والتعاون.'),
  'You can find assigned work.':copy('Atanmış işi bulabilirsiniz.','Вы можете найти назначенную работу.','آپ تفویض شدہ کام تلاش کر سکتے ہیں۔','يمكنك العثور على العمل المسند.'),
  'You know where attendance and time records live.':copy('Devam ve zaman kayıtlarının nerede olduğunu bilirsiniz.','Вы знаете, где находятся записи посещаемости и времени.','آپ جانتے ہیں حاضری اور وقت کے ریکارڈ کہاں ہیں۔','تعرف أين توجد سجلات الحضور والوقت.'),
  'Requests, pay and conversations are easy to return to.':copy('Taleplere, ücrete ve konuşmalara kolayca geri dönebilirsiniz.','К запросам, оплате и разговорам легко вернуться.','درخواستوں، تنخواہ اور گفتگو پر واپس جانا آسان ہے۔','يسهل الرجوع إلى الطلبات والرواتب والمحادثات.'),
}
