import { useMemo, useState, type CSSProperties, type FormEvent, type ReactNode } from 'react'
import { ArrowRight, Check, Mail, MapPin, Phone } from 'lucide-react'
import { apiRequest } from '../api/client'
import type { PublicWebsitePayload, WebsitePublicForm, WebsiteSchema, WebsiteSection } from './types'
import { translatePageCopy } from '../i18n/pageCopy'
import type { LocaleCode } from '../i18n/catalog'
import './website-renderer.css'

/** Returns a bounded numeric layout token for public website CSS variables. */
function numberToken(value:unknown,fallback:number,min:number,max:number){const numeric=Number(value);return Number.isFinite(numeric)?Math.min(max,Math.max(min,numeric)):fallback}
/** Returns a safe public link target while rejecting script/data protocols. */
function safeUrl(value:unknown,fallback='#'){const url=String(value??'').trim();return /^(?:https?:\/\/|mailto:|tel:|\/|#)/i.test(url)?url:fallback}
/** Returns a section media item previously resolved by the public backend. */
function mediaOf(settings:Record<string,any>){return settings.media as {url?:string;alt_text?:string|null;caption?:string|null}|undefined}
/** Build bounded section-level design variables shared by preview and published delivery. */
function sectionPresentation(settings:Record<string,any>):{className:string;style:CSSProperties;id?:string}{
 const design=settings.design??{},effects=settings.effects??{},breakpoints=design.breakpoints??{},tablet=breakpoints.tablet??{},mobile=breakpoints.mobile??{}
 const align=['left','center','right'].includes(String(design.align))?String(design.align):'left',animation=['fade','fade-up','scale'].includes(String(effects.animation))?String(effects.animation):'none'
 const className=`wi-site-section wi-site-section--align-${align}${design.hide_desktop?' is-hidden-desktop':''}${design.hide_tablet?' is-hidden-tablet':''}${design.hide_mobile?' is-hidden-mobile':''}${design.full_bleed?' is-full-bleed':''}${animation!=='none'?` wi-site-effect wi-site-effect--${animation}`:''}`
 const style={background:design.background?String(design.background):undefined,color:design.text_color?String(design.text_color):undefined,borderRadius:design.radius?`${numberToken(design.radius,0,0,48)}px`:undefined,'--wi-section-padding':`${numberToken(design.padding_y,72,0,220)}px`,'--wi-section-width':`${numberToken(design.content_width,1180,520,1600)}px`,'--wi-section-padding-tablet':`${numberToken(tablet.padding_y,Number(design.padding_y??64),0,220)}px`,'--wi-section-width-tablet':`${numberToken(tablet.content_width,Math.min(Number(design.content_width??1180),900),320,1200)}px`,'--wi-section-padding-mobile':`${numberToken(mobile.padding_y,Math.min(Number(design.padding_y??48),72),0,180)}px`,'--wi-section-width-mobile':`${numberToken(mobile.content_width,560,280,760)}px`,'--wi-effect-duration':`${numberToken(effects.duration,500,100,2000)}ms`,'--wi-effect-delay':`${numberToken(effects.delay,0,0,2000)}ms`,'--wi-effect-easing':['linear','ease-in-out','ease-out'].includes(String(effects.easing))?String(effects.easing):'ease-out'} as CSSProperties
 return{className,style,id:design.anchor?String(design.anchor).replace(/[^a-z0-9_-]/gi,'-'):undefined}
}
/** Renders one rich text string that has already passed backend sanitization for public payloads. */
function Rich({html}:{html:string}){return <div className="wi-site-rich" dangerouslySetInnerHTML={{__html:html||''}}/>}

/** Renders a public lead form and submits only declared fields to the workspace public endpoint. */
function LeadForm({form,workspaceSlug,preview=false}:{form:WebsitePublicForm;workspaceSlug:string;preview?:boolean}){
 const [values,setValues]=useState<Record<string,any>>({}),[status,setStatus]=useState<'idle'|'sending'|'sent'|'error'>('idle'),[message,setMessage]=useState('')
 /** Submits one public lead and displays server-confirmed success/error feedback. */
 const submit=async(event:FormEvent)=>{event.preventDefault();if(preview)return;setStatus('sending');setMessage('');try{const response=await apiRequest<{message:string}>(`/api/v1/public-websites/${encodeURIComponent(workspaceSlug)}/forms/${encodeURIComponent(form.uuid)}/submit`,{method:'POST',silent:true,body:JSON.stringify({fields:values,consent:Boolean(values.__consent),source_url:window.location.href,_company_website:''})});setStatus('sent');setMessage(response.message);setValues({})}catch(error){setStatus('error');setMessage(error instanceof Error?error.message:'Could not submit this form.')}}
 return <form className="wi-site-form" onSubmit={submit}>{form.fields.map(field=><label key={field.id} className="wi-site-field"><span>{field.label}{field.required&&<b> *</b>}</span>{field.type==='textarea'?<textarea disabled={preview} required={field.required} value={String(values[field.id]??'')} onChange={e=>setValues(current=>({...current,[field.id]:e.target.value}))}/>:field.type==='select'?<select disabled={preview} required={field.required} value={String(values[field.id]??'')} onChange={e=>setValues(current=>({...current,[field.id]:e.target.value}))}><option value="">Select…</option>{field.options?.map(option=><option key={option} value={option}>{option}</option>)}</select>:field.type==='checkbox'?<input type="checkbox" disabled={preview} checked={Boolean(values[field.id])} onChange={e=>setValues(current=>({...current,[field.id]:e.target.checked}))}/>:<input disabled={preview} type={['email','number','date'].includes(field.type)?field.type:'text'} required={field.required} value={String(values[field.id]??'')} onChange={e=>setValues(current=>({...current,[field.id]:e.target.value}))}/>}</label>)}{form.settings?.require_consent&&<label className="wi-site-consent"><input type="checkbox" disabled={preview} checked={Boolean(values.__consent)} onChange={e=>setValues(current=>({...current,__consent:e.target.checked}))}/> <span>{String(form.settings?.consent_label||'I agree to the privacy policy and consent to this submission.')}</span></label>}<button className="wi-site-button wi-site-button--primary" disabled={preview||status==='sending'}>{status==='sending'?'Sending…':String(form.settings?.submit_label||'Submit')} <ArrowRight size={15}/></button>{message&&<div className={`wi-site-form-message is-${status}`} role={status==='error'?'alert':'status'} aria-live="polite">{message}</div>}</form>
}

/** Renders a repeated title/text/value item collection used by several section families. */
function ItemGrid({items,kind}:{items:any[];kind:string}){return <div className={`wi-site-items wi-site-items--${kind}`}>{items.map((item,index)=><article key={item.id??index} className="wi-site-item">{item.media?.url&&<img src={item.media.url} alt={item.media.alt_text||item.title||''}/>} {item.value&&<strong className="wi-site-item__value">{item.value}</strong>} {item.title&&<h3>{item.title}</h3>} {item.label&&<h3>{item.label}</h3>} {item.text&&<p>{item.text}</p>} {item.quote&&<blockquote>{item.quote}</blockquote>} {item.url&&<a href={safeUrl(item.url)}>Learn more <ArrowRight size={13}/></a>}</article>)}</div>}

/** Renders one section from the stable Website Studio schema catalog. */
function Section({section,forms,workspaceSlug,preview=false}:{section:WebsiteSection;forms:Record<string,WebsitePublicForm>;workspaceSlug:string;preview?:boolean}){
 const s=section.settings||{},media=mediaOf(s),items=Array.isArray(s.items)?s.items:[],presentation=sectionPresentation(s)
 if(section.type==='hero')return <section {...presentation} className={`${presentation.className} wi-site-hero`}><div className="wi-site-section__inner wi-site-hero__grid"><div>{s.eyebrow&&<div className="wi-site-eyebrow">{s.eyebrow}</div>}<h1>{s.title||'Build something meaningful.'}</h1>{s.body&&<p className="wi-site-lead">{s.body}</p>}<div className="wi-site-actions">{s.primary_label&&<a className="wi-site-button wi-site-button--primary" href={safeUrl(s.primary_url)}>{s.primary_label}<ArrowRight size={15}/></a>}{s.secondary_label&&<a className="wi-site-button" href={safeUrl(s.secondary_url)}>{s.secondary_label}</a>}</div></div>{media?.url&&<img className="wi-site-hero__media" src={media.url} alt={media.alt_text||''}/>}</div></section>
 if(section.type==='rich_text'||section.type==='custom')return <section {...presentation}><div className="wi-site-section__inner wi-site-copy">{s.title&&<h2>{s.title}</h2>}<Rich html={String(s.html||s.body||'')}/></div></section>
 if(section.type==='image')return <section {...presentation}><div className="wi-site-section__inner">{s.title&&<h2>{s.title}</h2>}{media?.url?<figure className="wi-site-image"><img src={media.url} alt={media.alt_text||String(s.alt||'')}/>{(s.caption||media.caption)&&<figcaption>{s.caption||media.caption}</figcaption>}</figure>:null}</div></section>
 if(section.type==='gallery')return <section {...presentation}><div className="wi-site-section__inner">{s.title&&<h2>{s.title}</h2>}<div className="wi-site-gallery" style={{'--wi-gallery-columns':numberToken(s.columns,3,1,6)} as CSSProperties}>{(s.media_items||[]).map((item:any)=><img key={item.uuid} src={item.url} alt={item.alt_text||''}/>)}</div></div></section>
 if(['features','stats','services','team','portfolio','testimonials','pricing'].includes(section.type))return <section {...presentation}><div className="wi-site-section__inner">{s.eyebrow&&<div className="wi-site-eyebrow">{s.eyebrow}</div>}{s.title&&<h2>{s.title}</h2>}{s.body&&<p className="wi-site-section__intro">{s.body}</p>}<ItemGrid items={items} kind={section.type}/></div></section>
 if(section.type==='faq')return <section {...presentation}><div className="wi-site-section__inner wi-site-narrow">{s.title&&<h2>{s.title}</h2>}<div className="wi-site-faq">{items.map((item,index)=><details key={item.id??index}><summary>{item.title||item.question||'Question'}</summary><p>{item.text||item.answer||''}</p></details>)}</div></div></section>
 if(section.type==='form'){const form=forms[String(s.form_uuid||'')];return <section {...presentation}><div className="wi-site-section__inner wi-site-form-layout"><div>{s.eyebrow&&<div className="wi-site-eyebrow">{s.eyebrow}</div>}<h2>{s.title||form?.name||'Contact us'}</h2>{s.body&&<p>{s.body}</p>}</div>{form?<LeadForm form={form} workspaceSlug={workspaceSlug} preview={preview}/>:<p>This form is not available.</p>}</div></section>}
 if(section.type==='cta')return <section {...presentation}><div className="wi-site-section__inner"><div className="wi-site-cta"><div><h2>{s.title||'Ready to get started?'}</h2>{s.body&&<p>{s.body}</p>}</div>{s.button_label&&<a className="wi-site-button wi-site-button--primary" href={safeUrl(s.button_url)}>{s.button_label}<ArrowRight size={15}/></a>}</div></div></section>
 if(section.type==='columns')return <section {...presentation}><div className="wi-site-section__inner wi-site-columns" style={{'--wi-columns':numberToken(s.columns,2,1,4)} as CSSProperties}>{items.map((item,index)=><div key={item.id??index}><h3>{item.title}</h3><Rich html={String(item.html||item.text||'')}/></div>)}</div></section>
 if(section.type==='divider')return <div className="wi-site-section__inner"><hr className="wi-site-divider"/></div>
 if(section.type==='spacer')return <div aria-hidden="true" style={{height:numberToken(s.height,48,8,240)}}/>
 return null
}

/** Renders a published or editor-preview website from the same stable schema. */
export default function WebsiteRenderer({payload,workspaceSlug,basePath='',preview=false,viewport}:{payload:PublicWebsitePayload;workspaceSlug:string;basePath?:string;preview?:boolean;viewport?:'desktop'|'tablet'|'mobile'}){
 const theme=payload.site.theme||{},style=useMemo(()=>({
  '--wi-site-bg':theme.background||'#fff','--wi-site-surface':theme.surface||'#f7f7f8','--wi-site-text':theme.text||'#17171c','--wi-site-muted':theme.muted||'#666673','--wi-site-primary':theme.primary||'#4f46e5','--wi-site-radius':`${numberToken(theme.radius,14,0,40)}px`,'--wi-site-button-radius':`${numberToken(theme.button_radius,10,0,40)}px`,'--wi-site-width':`${numberToken(theme.content_width,1180,720,1600)}px`,'--wi-site-heading':theme.font_heading||'Inter','--wi-site-body':theme.font_body||'Inter','--wi-site-body-size':`${numberToken(theme.body_size,16,12,22)}px`,'--wi-site-heading-scale':numberToken(theme.heading_scale,1,.8,1.4),'--wi-site-section-spacing':`${numberToken(theme.section_spacing,72,32,140)}px`,'--wi-site-shadow-strength':numberToken(theme.shadow_strength,1,0,2),
 }) as CSSProperties,[theme])
 /** Converts site-relative paths to either custom-domain or /site/{slug} paths. */
 const link=(path:string)=>{if(/^https?:\/\//i.test(path))return path;if(basePath)return `${basePath}${path==='/'?'':path}`||'/';return path||'/'}
 const header=payload.site.header_config||{},footer=payload.site.footer_config||{}
 const locale=((payload.page.language||'en').split('-')[0]||'en') as LocaleCode
 /** Localize accessibility-only public website chrome without changing workspace-authored content. */
 const lp=(value:string)=>translatePageCopy(locale,value)
 return <div className={`wi-site${preview?' is-preview':''}${preview&&viewport?` is-preview-${viewport}`:''}`} style={style} dir={['ar','ur'].includes(payload.page.language)?'rtl':'ltr'}><a className="ui-skip-link" href="#website-main">{lp('Skip to main content')}</a><header className={`wi-site-header${header.sticky?' is-sticky':''}`}><div className="wi-site-header__inner"><a className="wi-site-brand" href={link('/')}>{payload.site.name}</a>{header.show_navigation!==false&&<nav aria-label={lp('Primary navigation')}>{payload.navigation.map(item=><a key={`${item.path}-${item.label}`} href={link(item.path)}>{item.label}</a>)}</nav>}{header.cta_label&&<a className="wi-site-button wi-site-button--primary" href={link(safeUrl(header.cta_url,'/contact'))}>{header.cta_label}</a>}</div></header><main id="website-main" tabIndex={-1}>{payload.page.schema.sections.map(section=><Section key={section.id} section={section} forms={payload.forms||{}} workspaceSlug={workspaceSlug} preview={preview}/>)}</main><footer className="wi-site-footer"><div className="wi-site-footer__inner"><div><strong>{payload.site.name}</strong><p>{String(footer.tagline||'')}</p></div>{footer.show_navigation!==false&&<nav aria-label={lp('Footer navigation')}>{payload.navigation.map(item=><a key={`footer-${item.path}-${item.label}`} href={link(item.path)}>{item.label}</a>)}</nav>}<small>{String(footer.copyright||`© ${new Date().getFullYear()} ${payload.site.name}. All rights reserved.`).replace('{{year}}',String(new Date().getFullYear())).replace('{{company.name}}',payload.site.name)}</small></div></footer></div>
}
