<?php
return [
 'reset_subject'=>'Reset your password','reset_greeting'=>'Password reset','reset_line'=>'A password reset was requested for your account.','reset_action'=>'Reset password','reset_ignore'=>'If you did not request this reset, no action is required.',
 'verify_subject'=>'Verify your email','verify_greeting'=>'Verify your email','verify_line'=>'Verify this email address to activate your workspace access.','verify_action'=>'Verify email','verify_expiry'=>'This verification link expires in 24 hours.',
 'invite_subject'=>"You're invited to :workspace",'invite_greeting'=>'Workspace invitation','invite_line'=>'You have been invited to join :workspace.','invite_action'=>'Accept invitation','invite_ignore'=>'If you were not expecting this invitation, you can ignore this message.',
 'digest_subject'=>':workspace — :frequency notification digest','digest_greeting'=>':frequency digest','digest_count'=>':count notification(s) included.','alert_footer'=>'This alert was generated by Workforce Intelligence.',
];
