<?php
namespace App\Services\ScreenshotStorage\Drivers;

use App\Models\ScreenshotStorageProvider;use App\Services\ScreenshotStorage\Contracts\StorageProviderDriver;use App\Services\ScreenshotStorage\OAuthTokenService;use Illuminate\Support\Facades\Http;
/** Provides google drive driver behavior within the WorkIntel application. */ class GoogleDriveDriver implements StorageProviderDriver
{
    /** Initializes the class with its required dependencies and state. */ public function __construct(private ScreenshotStorageProvider $provider,private array $config,private string $root=''){}
    /** Handles the put operation for the current WorkIntel workflow. */ public function put(string $key,string $contents,string $mimeType):array{$name=basename($key);$meta=['name'=>$name];if(!empty($this->config['folder_id']))$meta['parents']=[(string)$this->config['folder_id']];$boundary='wi_'.bin2hex(random_bytes(12));$body="--{$boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n".json_encode($meta)."\r\n--{$boundary}\r\nContent-Type: {$mimeType}\r\n\r\n".$contents."\r\n--{$boundary}--";$response=$this->request('POST','https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name',$body,'multipart/related; boundary='.$boundary);if(!$response->successful())throw new \RuntimeException('Google Drive upload failed: HTTP '.$response->status());$id=(string)($response->json('id')??'');if($id==='')throw new \RuntimeException('Google Drive did not return a file ID.');return['key'=>$key,'id'=>$id];}
    /** Returns get data required by the current workflow. */ public function get(string $key,?string $objectId=null):string{if(!$objectId)throw new \RuntimeException('Google Drive object ID is missing.');$r=$this->request('GET','https://www.googleapis.com/drive/v3/files/'.rawurlencode($objectId).'?alt=media');if(!$r->successful())throw new \RuntimeException('Google Drive download failed: HTTP '.$r->status());return$r->body();}
    /** Removes delete data from the requested resource. */ public function delete(string $key,?string $objectId=null):void{if(!$objectId)return;$r=$this->request('DELETE','https://www.googleapis.com/drive/v3/files/'.rawurlencode($objectId));if(!$r->successful()&&$r->status()!==404)throw new \RuntimeException('Google Drive delete failed: HTTP '.$r->status());}
    /** Handles the request operation for the current WorkIntel workflow. */ private function request(string $method,string $url,string $body='',?string $type=null){$tokens=app(OAuthTokenService::class);$token=$tokens->token($this->provider,'google');$client=Http::timeout(30)->withToken($token);if($type)$client=$client->withBody($body,$type);$r=$client->send($method,$url);if($r->status()===401&&!empty(($this->provider->encrypted_config??[])['refresh_token'])){$token=$tokens->token($this->provider,'google',true);$client=Http::timeout(30)->withToken($token);if($type)$client=$client->withBody($body,$type);$r=$client->send($method,$url);}return$r;}
}
