<?php
namespace App\Services\ScreenshotStorage\Drivers;
use App\Models\ScreenshotStorageProvider;use App\Services\ScreenshotStorage\Contracts\StorageProviderDriver;use App\Services\ScreenshotStorage\OAuthTokenService;use Illuminate\Support\Facades\Http;
/** Provides one drive driver behavior within the WorkIntel application. */ class OneDriveDriver implements StorageProviderDriver
{
    /** Initializes the class with its required dependencies and state. */ public function __construct(private ScreenshotStorageProvider $provider,private array $config,private string $root=''){}
    /** Handles the put operation for the current WorkIntel workflow. */ public function put(string $key,string $contents,string $mimeType):array{$path=trim(trim($this->root,'/').'/'.ltrim($key,'/'),'/');$base=$this->base();$url=$base.'/root:/'.$this->encodePath($path).':/content';$r=$this->request('PUT',$url,$contents,$mimeType);if(!$r->successful())throw new \RuntimeException('OneDrive upload failed: HTTP '.$r->status());$id=(string)($r->json('id')??'');if($id==='')throw new \RuntimeException('OneDrive did not return an item ID.');return['key'=>$path,'id'=>$id];}
    /** Returns get data required by the current workflow. */ public function get(string $key,?string $objectId=null):string{if(!$objectId)throw new \RuntimeException('OneDrive item ID is missing.');$r=$this->request('GET',$this->base().'/items/'.rawurlencode($objectId).'/content');if(!$r->successful())throw new \RuntimeException('OneDrive download failed: HTTP '.$r->status());return$r->body();}
    /** Removes delete data from the requested resource. */ public function delete(string $key,?string $objectId=null):void{if(!$objectId)return;$r=$this->request('DELETE',$this->base().'/items/'.rawurlencode($objectId));if(!$r->successful()&&$r->status()!==404)throw new \RuntimeException('OneDrive delete failed: HTTP '.$r->status());}
    /** Handles the base operation for the current WorkIntel workflow. */ private function base():string{return!empty($this->config['drive_id'])?'https://graph.microsoft.com/v1.0/drives/'.rawurlencode((string)$this->config['drive_id']):'https://graph.microsoft.com/v1.0/me/drive';}
    /** Handles the request operation for the current WorkIntel workflow. */ private function request(string $method,string $url,string $body='',?string $type=null){$tokens=app(OAuthTokenService::class);$token=$tokens->token($this->provider,'microsoft');$client=Http::timeout(30)->withToken($token);if($type)$client=$client->withBody($body,$type);$r=$client->send($method,$url);if($r->status()===401&&!empty(($this->provider->encrypted_config??[])['refresh_token'])){$token=$tokens->token($this->provider,'microsoft',true);$client=Http::timeout(30)->withToken($token);if($type)$client=$client->withBody($body,$type);$r=$client->send($method,$url);}return$r;}
    /** Handles the encode path operation for the current WorkIntel workflow. */ private function encodePath(string $path):string{return implode('/',array_map('rawurlencode',explode('/',$path)));}
}
