<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;
use App\Models\Client;
use App\Models\ClientInvoice;
use App\Services\ClientPortal\ClientInvoicePdfService;
use App\Services\ClientPortal\ClientInvoiceService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
/** Provides client invoice controller behavior within the WorkIntel application. */ class ClientInvoiceController extends Controller
{
    /** Initializes the class with its required dependencies and state. */ public function __construct(private readonly ClientInvoiceService $service){}
    /** Returns the requested resource collection. */ public function index(Request $request): JsonResponse { $w=$request->attributes->get('workspace');$q=ClientInvoice::query()->with('client:id,name,company_name')->where('workspace_id',$w->id);if($request->filled('client_id'))$q->where('client_id',$request->integer('client_id'));if($request->filled('status'))$q->where('status',$request->string('status'));return response()->json(['data'=>$q->latest('issue_date')->get()]); }
    /** Creates and persists the requested resource. */ public function store(Request $request): JsonResponse { $w=$request->attributes->get('workspace');$data=$request->validate(['client_id'=>['required','integer'],'currency'=>['nullable','string','size:3'],'issue_date'=>['required','date'],'due_date'=>['nullable','date'],'period_start'=>['nullable','date'],'period_end'=>['nullable','date'],'discount_total'=>['nullable','numeric','min:0'],'tax_percent'=>['nullable','numeric','min:0','max:100'],'notes'=>['nullable','string','max:5000'],'terms'=>['nullable','string','max:5000'],'allowed_gateways'=>['nullable','array'],'allowed_gateways.*'=>['string','in:manual,bank_transfer,stripe,paypal,custom_http'],'include_unbilled_time'=>['nullable','boolean'],'project_ids'=>['nullable','array'],'project_ids.*'=>['integer'],'lines'=>['nullable','array'],'lines.*.project_id'=>['nullable','integer'],'lines.*.description'=>['required_with:lines','string','max:500'],'lines.*.quantity'=>['required_with:lines','numeric','min:0'],'lines.*.unit_price'=>['required_with:lines','numeric','min:0']]);$client=Client::query()->where('workspace_id',$w->id)->whereKey($data['client_id'])->firstOrFail();return response()->json(['data'=>$this->service->create($client,$data,$request->user()->id)],201); }
    /** Returns details for the requested resource. */ public function show(Request $request, ClientInvoice $clientInvoice): JsonResponse { $this->ensure($request,$clientInvoice);return response()->json(['data'=>$clientInvoice->load(['client','lines.project','payments'])]); }
    /** Updates update data for the requested resource. */ public function update(Request $request, ClientInvoice $clientInvoice): JsonResponse { $this->ensure($request,$clientInvoice);$data=$request->validate(['due_date'=>['nullable','date'],'discount_total'=>['nullable','numeric','min:0'],'tax_percent'=>['nullable','numeric','min:0','max:100'],'notes'=>['nullable','string','max:5000'],'terms'=>['nullable','string','max:5000'],'allowed_gateways'=>['nullable','array'],'allowed_gateways.*'=>['string','in:manual,bank_transfer,stripe,paypal,custom_http'],'lines'=>['nullable','array'],'lines.*.project_id'=>['nullable','integer'],'lines.*.description'=>['required_with:lines','string','max:500'],'lines.*.quantity'=>['required_with:lines','numeric','min:0'],'lines.*.unit_price'=>['required_with:lines','numeric','min:0']]);return response()->json(['data'=>$this->service->updateDraft($clientInvoice->load('client'),$data)]); }
    /** Sends send information to the configured recipient. */ public function send(Request $request, ClientInvoice $clientInvoice): JsonResponse { $this->ensure($request,$clientInvoice);return response()->json(['data'=>$this->service->send($clientInvoice)]); }
    /** Handles the payment operation for the current WorkIntel workflow. */ public function payment(Request $request, ClientInvoice $clientInvoice): JsonResponse { $this->ensure($request,$clientInvoice);$data=$request->validate(['amount'=>['required','numeric','gt:0'],'currency'=>['nullable','string','size:3'],'method'=>['required','in:bank_transfer,cash,card,check,manual,other'],'reference'=>['nullable','string','max:160'],'paid_on'=>['required','date'],'note'=>['nullable','string','max:2000']]);$payment=$this->service->recordPayment($clientInvoice,$data,$request->user()->id);return response()->json(['data'=>$payment,'invoice'=>$clientInvoice->fresh(['lines.project','payments'])],201); }
    /** Handles the void operation for the current WorkIntel workflow. */ public function void(Request $request, ClientInvoice $clientInvoice): JsonResponse { $this->ensure($request,$clientInvoice);return response()->json(['data'=>$this->service->void($clientInvoice)]); }
    /** Handles the pdf operation for the current WorkIntel workflow. */ public function pdf(Request $request, ClientInvoice $clientInvoice, ClientInvoicePdfService $pdf): Response { $this->ensure($request,$clientInvoice);return response($pdf->render($clientInvoice),200,['Content-Type'=>'application/pdf','Content-Disposition'=>'attachment; filename="'.$clientInvoice->number.'.pdf"']); }
    /** Handles the ensure operation for the current WorkIntel workflow. */ private function ensure(Request $request, ClientInvoice $invoice): void { abort_unless($invoice->workspace_id===$request->attributes->get('workspace')->id,404); }
}
