<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use App\Models\CommerceCheckoutSession;use App\Models\SubscriptionPlan;use App\Services\Commerce\CommerceCheckoutService;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Validation\Rule;
/** Provides commerce controller behavior within the WorkIntel application. */ class CommerceController extends Controller
{
    /** Initializes the class with its required dependencies and state. */ public function __construct(private readonly CommerceCheckoutService $commerce){}
    /** Handles the pricing operation for the current WorkIntel workflow. */ public function pricing():JsonResponse{return response()->json(['plans'=>$this->commerce->catalog()]);}
    /** Handles the quote operation for the current WorkIntel workflow. */ public function quote(Request $r):JsonResponse{$w=$r->attributes->get('workspace');$d=$r->validate(['plan_slug'=>['required',Rule::exists('subscription_plans','slug')->where('is_active',true)->where('is_public',true)],'billing_interval'=>['required',Rule::in(['monthly','annual'])],'coupon_code'=>'nullable|string|max:64']);$plan=SubscriptionPlan::where('slug',$d['plan_slug'])->firstOrFail();$q=$this->commerce->quote($w,$plan,$d['billing_interval'],$d['coupon_code']??null);if($q['coupon'])$q['coupon']=['code'=>$q['coupon']->code,'name'=>$q['coupon']->name];return response()->json(['quote'=>$q]);}
    /** Handles the checkout operation for the current WorkIntel workflow. */ public function checkout(Request $r):JsonResponse{$w=$r->attributes->get('workspace');$d=$r->validate(['plan_slug'=>['required',Rule::exists('subscription_plans','slug')->where('is_active',true)->where('is_public',true)],'billing_interval'=>['required',Rule::in(['monthly','annual'])],'provider'=>'nullable|string|in:manual,bank_transfer,stripe,paypal,paddle,custom_http','coupon_code'=>'nullable|string|max:64']);$plan=SubscriptionPlan::where('slug',$d['plan_slug'])->firstOrFail();$session=$this->commerce->create($w,$r->user(),$plan,$d['billing_interval'],$d['provider']??null,$d['coupon_code']??null);return response()->json(['checkout'=>$this->payload($session)],201);}
    /** Returns details for the requested resource. */ public function show(Request $r,CommerceCheckoutSession $commerceCheckoutSession):JsonResponse{$w=$r->attributes->get('workspace');abort_unless((int)$commerceCheckoutSession->workspace_id===(int)$w->id,404);return response()->json(['checkout'=>$this->payload($commerceCheckoutSession->load(['plan','coupon']))]);}
    /** Handles the payload operation for the current WorkIntel workflow. */ private function payload(CommerceCheckoutSession $s):array{return ['id'=>$s->id,'uuid'=>$s->uuid,'status'=>$s->status,'provider'=>$s->provider,'plan'=>$s->plan?->name,'plan_slug'=>$s->plan?->slug,'billing_interval'=>$s->billing_interval,'seat_quantity'=>$s->seat_quantity,'currency'=>$s->currency,'subtotal'=>(float)$s->subtotal,'discount_total'=>(float)$s->discount_total,'tax_total'=>(float)$s->tax_total,'total'=>(float)$s->total,'checkout_url'=>$s->checkout_url,'expires_at'=>$s->expires_at?->toIso8601String(),'completed_at'=>$s->completed_at?->toIso8601String(),'coupon'=>$s->coupon?->code,'instructions'=>$s->metadata['instructions']??null];}
}
