<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use App\Models\EnterpriseIdentityProvider;use App\Models\Workspace;use App\Services\Enterprise\OidcService;use Illuminate\Http\Request;use Illuminate\Support\Facades\Crypt;
/** Provides enterprise sso controller behavior within the WorkIntel application. */ class EnterpriseSsoController extends Controller{
 /** Handles the start operation for the current WorkIntel workflow. */ public function start(Request $request,string $workspace,EnterpriseIdentityProvider $provider,OidcService $oidc){$w=Workspace::where('slug',$workspace)->firstOrFail();abort_unless((int)$provider->workspace_id===(int)$w->id&&$provider->status==='active',404);if($provider->type==='oidc')return redirect()->away($oidc->authorizationUrl($provider));abort(501,'Direct SAML assertion runtime is not enabled. Use the provider metadata endpoint and configure the signed SAML adapter before activation.');}
 /** Handles the oidc callback operation for the current WorkIntel workflow. */ public function oidcCallback(Request $request,EnterpriseIdentityProvider $provider,OidcService $oidc){$oidc->callback($provider,$request);return redirect(rtrim(config('app.url'),'/').'/app');}
 /** Handles the saml metadata operation for the current WorkIntel workflow. */ public function samlMetadata(EnterpriseIdentityProvider $provider){abort_unless($provider->type==='saml',404);$entity=e(rtrim(config('app.url'),'/').'/saml/sp/'.$provider->uuid);$acs=e(route('enterprise.saml.acs',['provider'=>$provider->id]));$xml='<?xml version="1.0" encoding="UTF-8"?>'."\n".'<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" entityID="'.$entity.'"><SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"><NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat><AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="'.$acs.'" index="1" isDefault="true"/></SPSSODescriptor></EntityDescriptor>';return response($xml,200,['Content-Type'=>'application/samlmetadata+xml']);}
 /** Handles the saml acs operation for the current WorkIntel workflow. */ public function samlAcs(Request $request,EnterpriseIdentityProvider $provider){abort_unless($provider->type==='saml',404);return response()->json(['message'=>'SAML provider configuration is installed, but signed assertion processing is intentionally disabled until a standards-compliant SAML runtime adapter is installed and configured.'],501);}
}
