<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use App\Models\AssetAssignment;use App\Models\CompanyAsset;use App\Models\WorkspaceMember;use App\Services\HRIS\HrisAccessService;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
/** Provides hris asset controller behavior within the WorkIntel application. */ class HrisAssetController extends Controller{
 /** Initializes the class with its required dependencies and state. */ public function __construct(private readonly HrisAccessService $access){}
 /** Returns the requested resource collection. */ public function index(Request $request):JsonResponse{$workspace=$request->attributes->get('workspace');$actor=$request->attributes->get('workspaceMember');if($actor->hasPermission('hris.assets.manage')){$assets=CompanyAsset::query()->where('workspace_id',$workspace->id)->with(['assignments'=>fn($q)=>$q->whereNull('returned_on')->with('member.user:id,first_name,last_name')])->orderBy('asset_tag')->get();}else{$assets=CompanyAsset::query()->where('workspace_id',$workspace->id)->whereHas('assignments',fn($q)=>$q->where('member_id',$actor->id)->whereNull('returned_on'))->with(['assignments'=>fn($q)=>$q->where('member_id',$actor->id)->whereNull('returned_on')])->get();}return response()->json(['data'=>$assets,'can_manage'=>$actor->hasPermission('hris.assets.manage')]);}
 /** Creates and persists the requested resource. */ public function store(Request $request):JsonResponse{$workspace=$request->attributes->get('workspace');$actor=$request->attributes->get('workspaceMember');abort_unless($actor->hasPermission('hris.assets.manage'),403);$data=$request->validate(['asset_tag'=>'required|string|max:80','name'=>'required|string|max:140','category'=>'required|string|max:60','serial_number'=>'nullable|string|max:120','status'=>'nullable|in:available,assigned,maintenance,retired,lost','purchased_on'=>'nullable|date','purchase_cost'=>'nullable|numeric|min:0','currency'=>'nullable|string|size:3','warranty_expires_on'=>'nullable|date','notes'=>'nullable|string|max:3000']);$asset=CompanyAsset::create(['uuid'=>(string)Str::uuid(),'workspace_id'=>$workspace->id,'status'=>$data['status']??'available',...$data]);return response()->json(['data'=>$asset],201);}
 /** Handles the assign operation for the current WorkIntel workflow. */ public function assign(Request $request,CompanyAsset $asset):JsonResponse{$workspace=$request->attributes->get('workspace');$actor=$request->attributes->get('workspaceMember');abort_unless((int)$asset->workspace_id===(int)$workspace->id,404);abort_unless($actor->hasPermission('hris.assets.manage'),403);$data=$request->validate(['member_id'=>'required|integer','assigned_on'=>'required|date','expected_return_on'=>'nullable|date|after_or_equal:assigned_on','condition_out'=>'nullable|string|max:60','notes'=>'nullable|string|max:2000']);WorkspaceMember::query()->where('workspace_id',$workspace->id)->findOrFail($data['member_id']);abort_if(AssetAssignment::query()->where('asset_id',$asset->id)->whereNull('returned_on')->exists(),422,'Asset is already assigned.');return DB::transaction(function()use($request,$workspace,$asset,$data){$assignment=AssetAssignment::create(['uuid'=>(string)Str::uuid(),'workspace_id'=>$workspace->id,'asset_id'=>$asset->id,'assigned_by'=>$request->user()->id,...$data]);$asset->update(['status'=>'assigned']);return response()->json(['data'=>$assignment->load('asset','member.user')],201);});}
 /** Handles the return asset operation for the current WorkIntel workflow. */ public function returnAsset(Request $request,AssetAssignment $assignment):JsonResponse{$workspace=$request->attributes->get('workspace');$actor=$request->attributes->get('workspaceMember');abort_unless((int)$assignment->workspace_id===(int)$workspace->id,404);abort_unless($actor->hasPermission('hris.assets.manage'),403);abort_if($assignment->returned_on,422,'Asset was already returned.');$data=$request->validate(['returned_on'=>'required|date','condition_in'=>'nullable|string|max:60','notes'=>'nullable|string|max:2000']);return DB::transaction(function()use($request,$assignment,$data){$assignment->update(['returned_on'=>$data['returned_on'],'condition_in'=>$data['condition_in']??null,'notes'=>$data['notes']??$assignment->notes,'returned_by'=>$request->user()->id]);$assignment->asset()->update(['status'=>'available']);return response()->json(['data'=>$assignment->fresh('asset')]);});}
}
