<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use App\Models\CompanyPolicy;use App\Models\PolicyAcknowledgement;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
/** Provides hris policy controller behavior within the WorkIntel application. */ class HrisPolicyController extends Controller{
 /** Returns the requested resource collection. */ public function index(Request $request):JsonResponse{$workspace=$request->attributes->get('workspace');$actor=$request->attributes->get('workspaceMember');$query=CompanyPolicy::query()->where('workspace_id',$workspace->id)->withCount('acknowledgements');if(!$actor->hasPermission('hris.policies.manage'))$query->where('status','published');$policies=$query->latest('published_at')->latest('version')->get();$acks=PolicyAcknowledgement::query()->where('workspace_id',$workspace->id)->where('member_id',$actor->id)->pluck('acknowledged_at','policy_id');return response()->json(['data'=>$policies->map(fn($p)=>array_merge($p->toArray(),['acknowledged_at'=>isset($acks[$p->id])?(string)$acks[$p->id]:null])),'can_manage'=>$actor->hasPermission('hris.policies.manage')]);}
 /** Creates and persists the requested resource. */ public function store(Request $request):JsonResponse{$workspace=$request->attributes->get('workspace');$actor=$request->attributes->get('workspaceMember');abort_unless($actor->hasPermission('hris.policies.manage'),403);$data=$request->validate(['policy_key'=>'required|string|max:120','title'=>'required|string|max:180','content'=>'required|string','acknowledgement_required'=>'sometimes|boolean','publish'=>'sometimes|boolean']);$version=((int)CompanyPolicy::query()->where('workspace_id',$workspace->id)->where('policy_key',$data['policy_key'])->max('version'))+1;return DB::transaction(function()use($request,$workspace,$data,$version){$publish=(bool)($data['publish']??false);if($publish)CompanyPolicy::query()->where('workspace_id',$workspace->id)->where('policy_key',$data['policy_key'])->where('status','published')->update(['status'=>'superseded']);$policy=CompanyPolicy::create(['uuid'=>(string)Str::uuid(),'workspace_id'=>$workspace->id,'policy_key'=>$data['policy_key'],'version'=>$version,'title'=>$data['title'],'content'=>$data['content'],'status'=>$publish?'published':'draft','acknowledgement_required'=>$data['acknowledgement_required']??true,'published_at'=>$publish?now():null,'created_by'=>$request->user()->id]);return response()->json(['data'=>$policy],201);});}
 /** Handles the publish operation for the current WorkIntel workflow. */ public function publish(Request $request,CompanyPolicy $policy):JsonResponse{$workspace=$request->attributes->get('workspace');$actor=$request->attributes->get('workspaceMember');abort_unless((int)$policy->workspace_id===(int)$workspace->id,404);abort_unless($actor->hasPermission('hris.policies.manage'),403);DB::transaction(function()use($workspace,$policy){CompanyPolicy::query()->where('workspace_id',$workspace->id)->where('policy_key',$policy->policy_key)->where('status','published')->where('id','!=',$policy->id)->update(['status'=>'superseded']);$policy->update(['status'=>'published','published_at'=>now()]);});return response()->json(['data'=>$policy->fresh()]);}
 /** Handles the acknowledge operation for the current WorkIntel workflow. */ public function acknowledge(Request $request,CompanyPolicy $policy):JsonResponse{$workspace=$request->attributes->get('workspace');$member=$request->attributes->get('workspaceMember');abort_unless((int)$policy->workspace_id===(int)$workspace->id&&$policy->status==='published',404);$data=$request->validate(['signed_name'=>'required|string|max:180']);$existing=PolicyAcknowledgement::query()->where('policy_id',$policy->id)->where('member_id',$member->id)->first();if($existing)return response()->json(['data'=>$existing]);$ack=PolicyAcknowledgement::create(['uuid'=>(string)Str::uuid(),'workspace_id'=>$workspace->id,'policy_id'=>$policy->id,'member_id'=>$member->id,'signed_name'=>$data['signed_name'],'acknowledged_at'=>now(),'ip_address'=>$request->ip(),'user_agent'=>substr((string)$request->userAgent(),0,500),'content_hash'=>hash('sha256',$policy->content)]);return response()->json(['data'=>$ack]);}
}
