<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Models\{FieldCheckpoint,FieldFile,FieldFormSubmission,FieldFormTemplate,FieldWorkOrder,MobileAccessToken,SafetyIncident,User,Workspace,WorkspaceMember};
use App\Services\Field\FieldWorkforceService;
use App\Services\Enterprise\EnterpriseSecurityService;
use App\Services\Enterprise\TotpService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

/** Provides mobile field controller behavior within the WorkIntel application. */ class MobileFieldController extends Controller
{
    /** Handles the login operation for the current WorkIntel workflow. */ public function login(Request $request): JsonResponse
    {
        $data=$request->validate(['email'=>'required|email','password'=>'required|string','workspace'=>'required|string','device_uuid'=>'required|uuid','platform'=>['required',Rule::in(['android','ios','web'])],'device_name'=>'nullable|string|max:120','app_version'=>'nullable|string|max:40','mfa_code'=>'nullable|string|max:32']);
        $user=User::where('email',strtolower($data['email']))->where('status','active')->first();abort_unless($user&&Hash::check($data['password'],$user->password),422,'The supplied credentials are invalid.');$workspace=Workspace::where('slug',$data['workspace'])->orWhere('id',ctype_digit($data['workspace'])?(int)$data['workspace']:0)->first();abort_unless($workspace,422,'Workspace not found.');app(\App\Services\Modules\WorkspaceModuleService::class)->assertEnabled($workspace,'field');$member=WorkspaceMember::with('roles.permissions')->where('workspace_id',$workspace->id)->where('user_id',$user->id)->where('status','active')->first();abort_unless($member,403,'You are not an active member of this workspace.');abort_unless($member->hasPermission('field.view_own')||$member->hasPermission('field.view_team')||$member->hasPermission('field.manage'),403,'Mobile field access is not enabled for your role.');if(\Illuminate\Support\Facades\Schema::hasTable('workspace_security_policies')&&app(EnterpriseSecurityService::class)->requiresMfa($user)){abort_unless(app(TotpService::class)->enabled($user),403,'MFA enrollment is required by workspace policy.');abort_unless(app(TotpService::class)->verify($user,(string)($data['mfa_code']??'')),422,'A valid MFA code is required.');}$raw='wim_'.Str::random(64);MobileAccessToken::where('workspace_id',$workspace->id)->where('member_id',$member->id)->where('device_uuid',$data['device_uuid'])->update(['revoked_at'=>now()]);$token=MobileAccessToken::create(['uuid'=>(string)Str::uuid(),'workspace_id'=>$workspace->id,'user_id'=>$user->id,'member_id'=>$member->id,'token_hash'=>hash('sha256',$raw),'token_prefix'=>substr($raw,0,14),'device_uuid'=>$data['device_uuid'],'platform'=>$data['platform'],'device_name'=>$data['device_name']??null,'app_version'=>$data['app_version']??null,'expires_at'=>now()->addDays(90),'created_at'=>now()]);return response()->json(['access_token'=>$raw,'token_type'=>'Bearer','expires_at'=>$token->expires_at,'workspace'=>['id'=>$workspace->id,'name'=>$workspace->name,'slug'=>$workspace->slug],'member'=>['id'=>$member->id,'name'=>trim($user->first_name.' '.$user->last_name),'permissions'=>$member->roles->flatMap(fn($r)=>$r->permissions->pluck('slug'))->unique()->values()]]);
    }

    /** Handles the logout operation for the current WorkIntel workflow. */ public function logout(Request $request): JsonResponse{$request->attributes->get('mobileToken')->update(['revoked_at'=>now()]);return response()->json(['message'=>'Mobile session revoked.']);}
    /** Handles the push token operation for the current WorkIntel workflow. */ public function pushToken(Request $request): JsonResponse{$data=$request->validate(['push_token'=>'required|string|max:4096']);$request->attributes->get('mobileToken')->update(['push_token_encrypted'=>Crypt::encryptString($data['push_token'])]);return response()->json(['message'=>'Push token stored securely.']);}

    /** Bootstraps bootstrap behavior for the application lifecycle. */ public function bootstrap(Request $request): JsonResponse
    {
        $member=$request->attributes->get('workspaceMember');$orders=FieldWorkOrder::query()->where('workspace_id',$member->workspace_id)->whereHas('assignees',fn($q)=>$q->where('member_id',$member->id))->with(['project:id,name,code','client:id,name','assignees.member.user:id,first_name,last_name'])->whereNotIn('status',['canceled'])->orderByRaw('due_at is null')->orderBy('due_at')->get();$forms=FieldFormTemplate::where('workspace_id',$member->workspace_id)->where('status','active')->with('fields')->orderBy('name')->get();return response()->json(['member'=>['id'=>$member->id,'name'=>trim($member->user->first_name.' '.$member->user->last_name),'employee_code'=>$member->employee_code],'work_orders'=>$orders,'forms'=>$forms,'server_time'=>now()->toIso8601String(),'sync'=>['max_events'=>100,'supported_events'=>['work_order.status','checkpoint.visit','incident.report']]]);
    }
    /** Handles the orders operation for the current WorkIntel workflow. */ public function orders(Request $request):JsonResponse{$member=$request->attributes->get('workspaceMember');return response()->json(['data'=>FieldWorkOrder::where('workspace_id',$member->workspace_id)->whereHas('assignees',fn($q)=>$q->where('member_id',$member->id))->with(['project:id,name,code','client:id,name','events'=>fn($q)=>$q->orderByDesc('occurred_at')->limit(20)])->orderByDesc('id')->get()]);}
    /** Handles the show order operation for the current WorkIntel workflow. */ public function showOrder(Request $request,FieldWorkOrder $order,FieldWorkforceService $service):JsonResponse{$member=$request->attributes->get('workspaceMember');$service->assertAssigned($member,$order);return response()->json(['data'=>$order->load(['project','client','assignees.member.user','events'=>fn($q)=>$q->orderByDesc('occurred_at'),'files'])]);}
    /** Updates update order status data for the requested resource. */ public function updateOrderStatus(Request $request,FieldWorkOrder $order,FieldWorkforceService $service):JsonResponse{$member=$request->attributes->get('workspaceMember');$data=$request->validate(['status'=>'required|string','note'=>'nullable|string|max:3000','latitude'=>'nullable|numeric|between:-90,90','longitude'=>'nullable|numeric|between:-180,180','accuracy_meters'=>'nullable|numeric|min:0']);return response()->json(['data'=>$service->updateStatus($order,$member,$data['status'],$data['note']??null,$data)]);}
    /** Handles the upload file operation for the current WorkIntel workflow. */ public function uploadFile(Request $request,FieldWorkOrder $order,FieldWorkforceService $service):JsonResponse{$member=$request->attributes->get('workspaceMember');$service->assertAssigned($member,$order);$request->validate(['file'=>'required|file|max:15360|mimes:jpg,jpeg,png,webp,pdf','kind'=>['nullable',Rule::in(['photo','document','signature'])],'caption'=>'nullable|string|max:1000','captured_at'=>'nullable|date']);$file=$request->file('file');$path=$file->storeAs('private/field/'.$member->workspace_id.'/'.$order->uuid,Str::uuid().'.'.$file->getClientOriginalExtension(),'local');$row=FieldFile::create(['uuid'=>(string)Str::uuid(),'workspace_id'=>$member->workspace_id,'field_work_order_id'=>$order->id,'member_id'=>$member->id,'kind'=>$request->input('kind','photo'),'file_path'=>$path,'file_name'=>$file->getClientOriginalName(),'mime_type'=>$file->getMimeType(),'size_bytes'=>$file->getSize(),'sha256'=>hash_file('sha256',$file->getRealPath()),'caption'=>$request->input('caption'),'captured_at'=>$request->input('captured_at'),'created_at'=>now()]);return response()->json(['data'=>$row],201);}
    /** Handles the scan operation for the current WorkIntel workflow. */ public function scan(Request $request,FieldWorkforceService $service):JsonResponse{$member=$request->attributes->get('workspaceMember');$data=$request->validate(['scan_token'=>'required|string|min:20','scan_method'=>['required',Rule::in(['qr','nfc'])],'field_work_order_id'=>'nullable|integer','latitude'=>'nullable|numeric|between:-90,90','longitude'=>'nullable|numeric|between:-180,180','accuracy_meters'=>'nullable|numeric|min:0','visited_at'=>'nullable|date']);return response()->json(['data'=>$service->scanCheckpoint($member,$data['scan_token'],$data)],201);}
    /** Handles the submit form operation for the current WorkIntel workflow. */ public function submitForm(Request $request,FieldFormTemplate $template,FieldWorkforceService $service):JsonResponse{$member=$request->attributes->get('workspaceMember');abort_unless((int)$template->workspace_id===(int)$member->workspace_id&&$template->status==='active',404);$data=$request->validate(['field_work_order_id'=>'nullable|integer','latitude'=>'nullable|numeric|between:-90,90','longitude'=>'nullable|numeric|between:-180,180','answers'=>'required|array']);if($template->requires_work_order)abort_unless($data['field_work_order_id']??null,422,'This form requires a work order.');if($template->requires_location)abort_unless(isset($data['latitude'],$data['longitude']),422,'This form requires location.');if($data['field_work_order_id']??null){$order=FieldWorkOrder::where('workspace_id',$member->workspace_id)->findOrFail($data['field_work_order_id']);$service->assertAssigned($member,$order);}$template->load('fields');foreach($template->fields as $field)if($field->required&&!array_key_exists($field->key,$data['answers']))abort(422,"{$field->label} is required.");$submission=FieldFormSubmission::create(['uuid'=>(string)Str::uuid(),'workspace_id'=>$member->workspace_id,'field_form_template_id'=>$template->id,'member_id'=>$member->id,'field_work_order_id'=>$data['field_work_order_id']??null,'status'=>'submitted','latitude'=>$data['latitude']??null,'longitude'=>$data['longitude']??null,'submitted_at'=>now(),'created_at'=>now()]);foreach($template->fields as $field)if(array_key_exists($field->key,$data['answers']))$submission->answers()->create(['field_form_field_id'=>$field->id,'value'=>['value'=>$data['answers'][$field->key]]]);return response()->json(['data'=>$submission->load('answers')],201);}
    /** Handles the incident operation for the current WorkIntel workflow. */ public function incident(Request $request,FieldWorkforceService $service):JsonResponse{$member=$request->attributes->get('workspaceMember');$data=$request->validate(['field_work_order_id'=>'nullable|integer','type'=>'required|string|max:50','severity'=>['required',Rule::in(['low','medium','high','critical'])],'title'=>'required|string|max:180','description'=>'required|string|max:10000','occurred_at'=>'required|date','latitude'=>'nullable|numeric|between:-90,90','longitude'=>'nullable|numeric|between:-180,180','immediate_action'=>'nullable|string|max:5000']);return response()->json(['data'=>$service->createIncident($member,$data)],201);}
    /** Synchronizes sync data with the current application state. */ public function sync(Request $request,FieldWorkforceService $service):JsonResponse{$member=$request->attributes->get('workspaceMember');$data=$request->validate(['events'=>'required|array|max:100','events.*.event_uuid'=>'required|uuid','events.*.event_type'=>'required|string|max:60','events.*.occurred_at'=>'nullable|date','events.*.payload'=>'nullable|array']);$results=[];foreach($data['events'] as $event){try{$results[]=$service->processOfflineEvent($member,$event);}catch(\Throwable $e){$results[]=['event_uuid'=>$event['event_uuid'],'status'=>'failed','error'=>$e->getMessage()];}}return response()->json(['data'=>$results,'server_time'=>now()->toIso8601String()]);}
}
