<?php
namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;use App\Models\DataImportJob;use App\Models\IndustryTemplate;use App\Models\PartnerAccount;use App\Models\PartnerApiKey;use App\Models\PlatformAddon;use App\Models\Workspace;use App\Models\WorkspaceAddon;use App\Models\WorkspaceBranding;use App\Models\WorkspaceDomain;use App\Services\Billing\EntitlementService;use App\Services\Platform\AddonService;use App\Services\Platform\DataImportService;use App\Services\Platform\DomainService;use App\Services\Platform\IndustryTemplateService;use App\Services\Platform\PartnerService;use App\Services\Platform\WorkspaceProvisioningService;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Arr;use Illuminate\Support\Str;use Illuminate\Validation\Rule;
/** Provides platform controller behavior within the WorkIntel application. */ class PlatformController extends Controller
{
 /** Handles the overview operation for the current WorkIntel workflow. */ public function overview(Request $r,AddonService $addons,EntitlementService $ent):JsonResponse{$w=$r->attributes->get('workspace');$user=$r->user();$accounts=PartnerAccount::with(['workspaces.workspace.subscription.plan','apiKeys'])->whereHas('members',fn($q)=>$q->where('user_id',$user->id)->where('status','active'))->get();$flatEntitlements=$ent->map($w);$entitlements=array_merge($flatEntitlements,Arr::undot($flatEntitlements));return response()->json(['branding'=>$w->branding,'domains'=>$w->customDomains()->orderByDesc('created_at')->get()->map(fn($d)=>$this->domainPayload($d)),'partner_accounts'=>$accounts,'addons'=>$addons->catalogFor($w),'addon_estimate'=>$addons->monthlyEstimate($w),'templates'=>IndustryTemplate::where('status','active')->orderBy('industry')->orderBy('name')->get(),'template_installations'=>\App\Models\IndustryTemplateInstallation::with('template')->where('workspace_id',$w->id)->latest('installed_at')->limit(20)->get(),'imports'=>DataImportJob::where('workspace_id',$w->id)->latest()->limit(30)->get(),'sandboxes'=>Workspace::with('subscription.plan')->where('parent_workspace_id',$w->id)->where('workspace_type','sandbox')->latest()->get(),'entitlements'=>$entitlements]);}
 /** Handles the save branding operation for the current WorkIntel workflow. */ public function saveBranding(Request $r,EntitlementService $ent):JsonResponse{$w=$r->attributes->get('workspace');$ent->assertFeature($w,'feature.white_label');$d=$r->validate(['product_name'=>'nullable|string|max:100','support_email'=>'nullable|email|max:190','support_url'=>'nullable|url|max:500','accent_color'=>['nullable','regex:/^#[0-9A-Fa-f]{6}$/'],'hide_powered_by'=>'nullable|boolean','logo'=>'nullable|file|mimes:png,jpg,jpeg,webp|max:2048','favicon'=>'nullable|file|mimes:png,ico,jpg,jpeg,webp|max:512']);$b=WorkspaceBranding::firstOrNew(['workspace_id'=>$w->id]);if(!$b->exists)$b->uuid=(string)Str::uuid();foreach(['product_name','support_email','support_url','accent_color','hide_powered_by'] as $key)if(array_key_exists($key,$d))$b->{$key}=$d[$key];foreach(['logo','favicon'] as $kind)if($r->hasFile($kind)){$file=$r->file($kind);$path=$file->store('platform/branding/'.$w->id,'local');$old=$b->{$kind.'_path'};if($old)Storage::disk('local')->delete($old);$b->{$kind.'_path'}=$path;$b->{$kind.'_mime'}=$file->getMimeType();}$b->save();return response()->json(['data'=>$b->fresh()]);}
 /** Handles the store domain operation for the current WorkIntel workflow. */ public function storeDomain(Request $r,DomainService $domains,EntitlementService $ent):JsonResponse{$w=$r->attributes->get('workspace');$ent->assertFeature($w,'feature.custom_domains');$limit=(int)$ent->value($w,'limit.custom_domains',0);$count=$w->customDomains()->whereNotIn('status',['removed'])->count();abort_if($limit>=0&&$count>=$limit,422,"Custom domain limit reached ({$count}/{$limit}).");$data=$r->validate(['hostname'=>'required|string|max:255']);$d=$domains->create($w,$data['hostname']);return response()->json(['data'=>$this->domainPayload($d)],201);}
 /** Handles the verify domain operation for the current WorkIntel workflow. */ public function verifyDomain(Request $r,WorkspaceDomain $workspaceDomain,DomainService $svc):JsonResponse{$w=$r->attributes->get('workspace');$this->own($w,$workspaceDomain);return response()->json(['data'=>$this->domainPayload($svc->verifyDns($workspaceDomain))]);}
 /** Handles the activate domain operation for the current WorkIntel workflow. */ public function activateDomain(Request $r,WorkspaceDomain $workspaceDomain,DomainService $svc):JsonResponse{$w=$r->attributes->get('workspace');$this->own($w,$workspaceDomain);return response()->json(['data'=>$this->domainPayload($svc->activate($workspaceDomain))]);}
 /** Handles the destroy domain operation for the current WorkIntel workflow. */ public function destroyDomain(Request $r,WorkspaceDomain $workspaceDomain):JsonResponse{$this->own($r->attributes->get('workspace'),$workspaceDomain);$workspaceDomain->delete();return response()->json(['message'=>'Domain removed.']);}
 /** Handles the store partner operation for the current WorkIntel workflow. */ public function storePartner(Request $r,PartnerService $svc,EntitlementService $ent):JsonResponse{$w=$r->attributes->get('workspace');$ent->assertFeature($w,'feature.partner_platform');$d=$r->validate(['name'=>'required|string|max:140','type'=>['required',Rule::in(['agency','reseller','partner'])]]);return response()->json(['data'=>$svc->createAccount($w,$r->user(),$d['name'],$d['type'])],201);}
 /** Creates create managed workspace data for the requested workflow. */ public function createManagedWorkspace(Request $r,PartnerAccount $partnerAccount,PartnerService $partner,WorkspaceProvisioningService $provision):JsonResponse{$w=$r->attributes->get('workspace');$partner->assertMember($partnerAccount,$r->user(),true);abort_unless((int)$partnerAccount->billing_workspace_id===(int)$w->id,403);$d=$r->validate(['name'=>'required|string|max:140','plan_slug'=>['nullable',Rule::in(['free','silver','gold','platinum'])],'external_reference'=>'nullable|string|max:120']);$child=$provision->createManagedWorkspace($w,$r->user(),$d['name'],$d['plan_slug']??'free');$partner->attachWorkspace($partnerAccount,$child,'managed',$d['external_reference']??null);return response()->json(['data'=>$child],201);}
 /** Creates create partner key data for the requested workflow. */ public function createPartnerKey(Request $r,PartnerAccount $partnerAccount,PartnerService $svc,EntitlementService $ent):JsonResponse{$w=$r->attributes->get('workspace');$ent->assertFeature($w,'feature.partner_api');$svc->assertMember($partnerAccount,$r->user(),true);abort_unless((int)$partnerAccount->billing_workspace_id===(int)$w->id,403);$d=$r->validate(['name'=>'required|string|max:120','scopes'=>'required|array|min:1','scopes.*'=>'string|max:80','expires_at'=>'nullable|date|after:now']);$result=$svc->createApiKey($partnerAccount,$r->user(),$d['name'],$d['scopes'],isset($d['expires_at'])?new \DateTimeImmutable($d['expires_at']):null);return response()->json(['data'=>$result['key'],'token'=>$result['token']],201);}
 /** Handles the revoke partner key operation for the current WorkIntel workflow. */ public function revokePartnerKey(Request $r,PartnerAccount $partnerAccount,PartnerApiKey $partnerApiKey,PartnerService $svc):JsonResponse{$svc->assertMember($partnerAccount,$r->user(),true);$svc->revokeKey($partnerAccount,$partnerApiKey);return response()->json(['message'=>'Partner API key revoked.']);}
 /** Handles the subscribe addon operation for the current WorkIntel workflow. */ public function subscribeAddon(Request $r,PlatformAddon $platformAddon,AddonService $svc,EntitlementService $ent):JsonResponse{$w=$r->attributes->get('workspace');$ent->assertFeature($w,'feature.addon_marketplace');$d=$r->validate(['quantity'=>'nullable|numeric|min:0.0001|max:10000']);return response()->json(['data'=>$svc->subscribe($w,$platformAddon,(float)($d['quantity']??1))->load('addon'),'estimate'=>$svc->monthlyEstimate($w)],201);}
 /** Determines whether the cancel addon condition is satisfied. */ public function cancelAddon(Request $r,WorkspaceAddon $workspaceAddon,AddonService $svc):JsonResponse{return response()->json(['data'=>$svc->cancel($r->attributes->get('workspace'),$workspaceAddon),'estimate'=>$svc->monthlyEstimate($r->attributes->get('workspace'))]);}
 /** Handles the addon usage operation for the current WorkIntel workflow. */ public function addonUsage(Request $r,WorkspaceAddon $workspaceAddon,AddonService $svc):JsonResponse{$w=$r->attributes->get('workspace');$d=$r->validate(['metric'=>'required|string|max:80','quantity'=>'required|numeric|min:0.0001','idempotency_key'=>'required|string|max:160','metadata'=>'nullable|array']);return response()->json(['data'=>$svc->recordUsage($w,$workspaceAddon,$d['metric'],(float)$d['quantity'],$d['idempotency_key'],$d['metadata']??[])],201);}
 /** Handles the install template operation for the current WorkIntel workflow. */ public function installTemplate(Request $r,IndustryTemplate $industryTemplate,IndustryTemplateService $svc):JsonResponse{$w=$r->attributes->get('workspace');return response()->json(['data'=>$svc->apply($w,$industryTemplate,$r->user())],201);}
 /** Handles the store import operation for the current WorkIntel workflow. */ public function storeImport(Request $r,DataImportService $svc,EntitlementService $ent):JsonResponse{$w=$r->attributes->get('workspace');$ent->assertFeature($w,'feature.import_wizard');$d=$r->validate(['file'=>'required|file|max:10240','entity_type'=>['required',Rule::in(DataImportService::ENTITIES)],'source_system'=>'required|string|max:60','mapping'=>'required','options'=>'nullable']);$mapping=is_string($d['mapping'])?json_decode($d['mapping'],true):$d['mapping'];$options=isset($d['options'])?(is_string($d['options'])?json_decode($d['options'],true):$d['options']):[];if(!is_array($mapping))abort(422,'Mapping must be valid JSON.');$job=$svc->createJob($w,$r->user(),$r->file('file'),$d['entity_type'],$d['source_system'],$mapping,is_array($options)?$options:[]);return response()->json(['data'=>$job,'preview'=>$svc->preview($job)],201);}
 /** Handles the preview import operation for the current WorkIntel workflow. */ public function previewImport(Request $r,DataImportJob $dataImportJob,DataImportService $svc):JsonResponse{$this->own($r->attributes->get('workspace'),$dataImportJob);return response()->json(['data'=>$dataImportJob,'preview'=>$svc->preview($dataImportJob,$r->integer('limit',10))]);}
 /** Handles the run import operation for the current WorkIntel workflow. */ public function runImport(Request $r,DataImportJob $dataImportJob,DataImportService $svc):JsonResponse{$this->own($r->attributes->get('workspace'),$dataImportJob);return response()->json(['data'=>$svc->run($dataImportJob)]);}
 /** Creates create sandbox data for the requested workflow. */ public function createSandbox(Request $r,WorkspaceProvisioningService $svc):JsonResponse{$w=$r->attributes->get('workspace');$d=$r->validate(['name'=>'required|string|max:140','days'=>'nullable|integer|min:1|max:90']);return response()->json(['data'=>$svc->createSandbox($w,$r->user(),$d['name'],$d['days']??30)],201);}
 /** Handles the archive sandbox operation for the current WorkIntel workflow. */ public function archiveSandbox(Request $r,Workspace $sandbox):JsonResponse{$w=$r->attributes->get('workspace');abort_unless($sandbox->workspace_type==='sandbox'&&(int)$sandbox->parent_workspace_id===(int)$w->id,404);$sandbox->update(['status'=>'archived']);return response()->json(['data'=>$sandbox]);}
 /** Handles the own operation for the current WorkIntel workflow. */ private function own(Workspace $workspace,$model):void{abort_unless((int)$model->workspace_id===(int)$workspace->id,404);}
 /** Handles the domain payload operation for the current WorkIntel workflow. */ private function domainPayload(WorkspaceDomain $d):array{return ['id'=>$d->id,'uuid'=>$d->uuid,'hostname'=>$d->hostname,'status'=>$d->status,'verification_method'=>$d->verification_method,'verification_record'=>'workintel-verify='.$d->verification_nonce,'verified_at'=>$d->verified_at?->toIso8601String(),'activated_at'=>$d->activated_at?->toIso8601String(),'certificate_status'=>$d->certificate_status,'last_checked_at'=>$d->last_checked_at?->toIso8601String(),'last_error'=>$d->last_error];}
}
