<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use App\Models\{Role,User,WorkspaceMember};use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Str;
/** Provides scim controller behavior within the WorkIntel application. */ class ScimController extends Controller{
 /** Handles the service provider config operation for the current WorkIntel workflow. */ public function serviceProviderConfig():JsonResponse{return $this->scim(['schemas'=>['urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig'],'patch'=>['supported'=>true],'bulk'=>['supported'=>false],'filter'=>['supported'=>true,'maxResults'=>200],'changePassword'=>['supported'=>false],'sort'=>['supported'=>false],'etag'=>['supported'=>false],'authenticationSchemes'=>[['type'=>'oauthbearertoken','name'=>'Bearer Token','description'=>'WorkIntel SCIM bearer token','specUri'=>'https://www.rfc-editor.org/info/rfc6750','primary'=>true]]]);}
 /** Handles the schemas operation for the current WorkIntel workflow. */ public function schemas():JsonResponse{return $this->scim(['schemas'=>['urn:ietf:params:scim:api:messages:2.0:ListResponse'],'totalResults'=>2,'startIndex'=>1,'itemsPerPage'=>2,'Resources'=>[['id'=>'urn:ietf:params:scim:schemas:core:2.0:User','name'=>'User','description'=>'WorkIntel SCIM user schema','attributes'=>[['name'=>'userName','type'=>'string','required'=>true,'uniqueness'=>'server'],['name'=>'active','type'=>'boolean'],['name'=>'name','type'=>'complex'],['name'=>'emails','type'=>'complex','multiValued'=>true]]],['id'=>'urn:ietf:params:scim:schemas:core:2.0:Group','name'=>'Group','description'=>'WorkIntel role/group schema','attributes'=>[['name'=>'displayName','type'=>'string','required'=>true],['name'=>'members','type'=>'complex','multiValued'=>true]]]]]);}
 /** Handles the resource types operation for the current WorkIntel workflow. */ public function resourceTypes():JsonResponse{return $this->scim(['schemas'=>['urn:ietf:params:scim:api:messages:2.0:ListResponse'],'totalResults'=>2,'startIndex'=>1,'itemsPerPage'=>2,'Resources'=>[['id'=>'User','name'=>'User','endpoint'=>'/Users','schema'=>'urn:ietf:params:scim:schemas:core:2.0:User'],['id'=>'Group','name'=>'Group','endpoint'=>'/Groups','schema'=>'urn:ietf:params:scim:schemas:core:2.0:Group']]]);}
 /** Handles the users operation for the current WorkIntel workflow. */ public function users(Request $request):JsonResponse{$w=$request->attributes->get('workspace');$q=WorkspaceMember::with('user')->where('workspace_id',$w->id);if(preg_match('/userName\s+eq\s+"([^"]+)"/i',(string)$request->query('filter'),$m))$q->whereHas('user',fn($u)=>$u->where('email',strtolower($m[1])));$start=max(1,(int)$request->query('startIndex',1));$count=min(200,max(1,(int)$request->query('count',100)));$total=$q->count();$resources=$q->orderBy('id')->skip($start-1)->take($count)->get()->map(fn($m)=>$this->userResource($m))->values();return $this->scim(['schemas'=>['urn:ietf:params:scim:api:messages:2.0:ListResponse'],'totalResults'=>$total,'startIndex'=>$start,'itemsPerPage'=>$resources->count(),'Resources'=>$resources]);}
 /** Handles the show user operation for the current WorkIntel workflow. */ public function showUser(Request $request,string $id):JsonResponse{$w=$request->attributes->get('workspace');$m=WorkspaceMember::with('user')->where('workspace_id',$w->id)->where('user_id',$id)->firstOrFail();return $this->scim($this->userResource($m));}
 /** Handles the store user operation for the current WorkIntel workflow. */ public function storeUser(Request $request):JsonResponse{$w=$request->attributes->get('workspace');$d=$request->validate(['userName'=>'required|email','active'=>'boolean','name.givenName'=>'nullable|string|max:100','name.familyName'=>'nullable|string|max:100','displayName'=>'nullable|string|max:200','externalId'=>'nullable|string|max:200']);$email=strtolower($d['userName']);$user=User::firstOrCreate(['email'=>$email],['first_name'=>$d['name']['givenName']??'SCIM','last_name'=>$d['name']['familyName']??'User','password'=>Hash::make(Str::random(64)),'timezone'=>'UTC','status'=>'active']);$member=WorkspaceMember::firstOrCreate(['workspace_id'=>$w->id,'user_id'=>$user->id],['job_title'=>'SCIM User','employment_type'=>'full_time','employment_stage'=>'active','joining_date'=>today(),'status'=>($d['active']??true)?'active':'inactive','timezone'=>$user->timezone]);if($member->roles()->count()===0){$role=Role::where('workspace_id',$w->id)->where('status','active')->where('slug','employee')->first();if($role)$member->roles()->attach($role->id);}$member->update(['status'=>($d['active']??true)?'active':'inactive']);return $this->scim($this->userResource($member->fresh('user')),201);}
 /** Handles the patch user operation for the current WorkIntel workflow. */ public function patchUser(Request $request,string $id):JsonResponse{$w=$request->attributes->get('workspace');$m=WorkspaceMember::with('user')->where('workspace_id',$w->id)->where('user_id',$id)->firstOrFail();$ops=$request->input('Operations',[]);foreach($ops as $op){$path=strtolower((string)($op['path']??''));$value=$op['value']??null;if($path==='active'||isset($value['active']))$m->update(['status'=>(bool)($path==='active'?$value:$value['active'])?'active':'inactive']);if($path==='name'||isset($value['name'])){$name=$path==='name'?$value:$value['name'];$m->user->update(['first_name'=>$name['givenName']??$m->user->first_name,'last_name'=>$name['familyName']??$m->user->last_name]);}if($path==='username'&&filter_var($value,FILTER_VALIDATE_EMAIL))$m->user->update(['email'=>strtolower($value)]);}return $this->scim($this->userResource($m->fresh('user')));}
 /** Removes delete user data from the requested resource. */ public function deleteUser(Request $request,string $id):JsonResponse{$w=$request->attributes->get('workspace');$m=WorkspaceMember::where('workspace_id',$w->id)->where('user_id',$id)->firstOrFail();$m->update(['status'=>'inactive']);return response()->json(null,204);}
 /** Handles the groups operation for the current WorkIntel workflow. */ public function groups(Request $request):JsonResponse{$w=$request->attributes->get('workspace');$roles=Role::with('members.user')->where('workspace_id',$w->id)->orderBy('name')->get();$resources=$roles->map(fn($r)=>['schemas'=>['urn:ietf:params:scim:schemas:core:2.0:Group'],'id'=>(string)$r->id,'displayName'=>$r->name,'members'=>$r->members->map(fn($m)=>['value'=>(string)$m->user_id,'display'=>trim($m->user->first_name.' '.$m->user->last_name)])->values()])->values();return $this->scim(['schemas'=>['urn:ietf:params:scim:api:messages:2.0:ListResponse'],'totalResults'=>$resources->count(),'startIndex'=>1,'itemsPerPage'=>$resources->count(),'Resources'=>$resources]);}
 /** Handles the patch group operation for the current WorkIntel workflow. */ public function patchGroup(Request $request,string $id):JsonResponse{$w=$request->attributes->get('workspace');$role=Role::where('workspace_id',$w->id)->where('status','active')->findOrFail($id);foreach($request->input('Operations',[]) as $op){$operation=strtolower((string)($op['op']??''));$values=$op['value']??[];foreach($values as $v){$userId=(int)($v['value']??0);$member=WorkspaceMember::where('workspace_id',$w->id)->where('user_id',$userId)->first();if(!$member)continue;if($operation==='add')$member->roles()->syncWithoutDetaching([$role->id]);elseif($operation==='remove')$member->roles()->detach($role->id);}}return $this->scim(['schemas'=>['urn:ietf:params:scim:schemas:core:2.0:Group'],'id'=>(string)$role->id,'displayName'=>$role->name]);}
 /** Handles the user resource operation for the current WorkIntel workflow. */ private function userResource(WorkspaceMember $m):array{return ['schemas'=>['urn:ietf:params:scim:schemas:core:2.0:User'],'id'=>(string)$m->user_id,'userName'=>$m->user->email,'active'=>$m->status instanceof \BackedEnum?$m->status->value==='active':(string)$m->status==='active','displayName'=>trim($m->user->first_name.' '.$m->user->last_name),'name'=>['givenName'=>$m->user->first_name,'familyName'=>$m->user->last_name],'emails'=>[['value'=>$m->user->email,'primary'=>true]],'meta'=>['resourceType'=>'User','location'=>url('/api/scim/v2/Users/'.$m->user_id)]];}
 /** Handles the scim operation for the current WorkIntel workflow. */ private function scim(array $data,int $status=200):JsonResponse{return response()->json($data,$status,['Content-Type'=>'application/scim+json']);}}
