import { ArrowRight, Banknote, CalendarCheck2, ChartBar, Check, Clock3, Globe2, LayoutDashboard, Monitor, Play, ShieldCheck, Sparkles, Users, Zap } from 'lucide-react';
import { Badge, Button, Card, CardBody, Page, Pressable, Box, Grid, Inline, Text, Link } from '../design-system';
const features = [
    { icon: Clock3, title: 'Time Tracking', text: 'Track work by project, task and billable status across web and desktop.' },
    { icon: Zap, title: 'Live Workforce', text: 'See who is working, idle, on break or offline with current context.' },
    { icon: CalendarCheck2, title: 'Attendance', text: 'Shifts, check-in/out, late arrivals, breaks, leave and overtime.' },
    { icon: ChartBar, title: 'Work Intelligence', text: 'Separate tracked, active, focused, productive and billable time.' },
    { icon: Banknote, title: 'Payroll', text: 'Hourly, daily, monthly, yearly and project-based compensation rules.' },
    { icon: ShieldCheck, title: 'Privacy Controls', text: 'Exclusions, blur, retention and transparent employee tracking controls.' },
];
/** Handles the marketing website operation for the WorkIntel client. */ export default function MarketingWebsite() {
    return <Box minHeight="100%" bg="var(--bg)" color="var(--text)">
 <Link className="ui-skip-link" href="#marketing-main">Skip to main content</Link>
 <Box as="header" className="marketing-header" height={62} display="flex" align="center" justify="space-between" p="0 34px" borderBottom="1px solid var(--border)" bg="var(--surface)" position="sticky" top={0} zIndex={4}><Box display="flex" align="center" gap={9} weight={700}><Box as="span" width={30} height={30} radius={7} display="grid" placeItems="center" bg="var(--accent)" color="var(--icon-on-accent)"><LayoutDashboard size={16}/></Box>WorkIntel</Box><Box as="nav" className="marketing-nav" display="flex" gap={18} color="var(--text-2)" size={12}><Pressable type="button" onClick={() => document.getElementById('features')?.scrollIntoView({ behavior: 'smooth' })} border={0} bg="transparent" color="inherit" font="inherit" cursor="pointer">Features</Pressable><Pressable type="button" onClick={() => window.location.assign('/app')} border={0} bg="transparent" color="inherit" font="inherit" cursor="pointer">Workspace</Pressable><Pressable type="button" onClick={() => window.location.assign('/app')} border={0} bg="transparent" color="inherit" font="inherit" cursor="pointer">Security</Pressable></Box><Inline className="marketing-header-actions" gap={8}><Button variant="ghost" onClick={() => window.location.assign('/app')}>Log in</Button><Button variant="primary" onClick={() => window.location.assign('/app')}>Start Free <ArrowRight size={14}/></Button></Inline></Box>
 <main id="marketing-main" tabIndex={-1}><Page maxWidth={1180} m="0 auto" pt={70} pb={70}>
  <Box as="section" className="marketing-hero" display="grid" gridColumns="1.02fr .98fr" gap={56} align="center" minHeight={520}><div><Badge tone="accent"><Sparkles size={12}/> Workforce Intelligence Platform</Badge><Box as="h1" size={58} lineHeight={1.02} letterSpacing="-.045em" m="20px 0 18px" maxWidth={650}>See where work actually goes.</Box><Box as="p" size={18} lineHeight={1.65} color="var(--text-2)" maxWidth={600} m="0 0 28px">Time, projects, attendance, activity, payroll and workforce performance in one operational workspace.</Box><Inline gap={10}><Button size="lg" variant="primary" onClick={() => window.location.assign('/app')}>Start Free <ArrowRight size={15}/></Button><Button size="lg" variant="outline" onClick={() => document.getElementById('features')?.scrollIntoView({ behavior: 'smooth' })}><Play size={15}/> View Product Tour</Button></Inline><Box className="marketing-trust-row" display="flex" gap={22} mt={22} color="var(--text-3)" size={11}><Box as="span" display="flex" align="center" gap={5}><Check size={13}/> No credit card</Box><Box as="span" display="flex" align="center" gap={5}><Check size={13}/> Privacy controls</Box><Box as="span" display="flex" align="center" gap={5}><Check size={13}/> Desktop + browser tracking</Box></Box></div>
  <Card elevated p={8} boxShadow="var(--wi-shadow-popover)"><CardBody><Inline justify="space-between" align="center" mb={18}><div><Box size={11} color="var(--text-3)">LIVE WORKFORCE</Box><Box size={18} weight={650} mt={3}>17 people working now</Box></div><Badge tone="success" dot>Live</Badge></Inline><Grid columns="repeat(3,1fr)" gap={8} mb={14}>{[['Tracked today', '142h 32m'], ['Attendance', '86%'], ['Billable', '97h 08m']].map(([a, b]) => <Box key={a} p={12} border="1px solid var(--border-muted)" radius={7} bg="var(--bg)"><Box size={10} color="var(--text-3)">{a}</Box><Box className="stat-num" size={16} weight={650} mt={4}>{b}</Box></Box>)}</Grid>{[['Ahmed Khan', 'WorkIntel Platform', '82%'], ['Sara Malik', 'Website Redesign', '74%'], ['John Lee', 'Analytics API', '89%']].map(([n, p, a]) => <Box key={n} display="grid" gridColumns="1fr 1fr 60px" gap={8} align="center" p="11px 4px" borderTop="1px solid var(--border-muted)"><Inline gap={8} align="center"><Box as="span" width={8} height={8} radius="50%" bg="var(--success)"/><span>{n}</span></Inline><Text color="var(--text-2)">{p}</Text><Text className="stat-num" align="right">{a}</Text></Box>)}</CardBody></Card>
  </Box>
  <Box as="section" id="features" p="74px 0 18px"><Box maxWidth={650} mb={30}><Box color="var(--accent)" weight={600} size={12} letterSpacing=".05em">ONE OPERATING SYSTEM FOR WORK</Box><Box as="h2" size={36} letterSpacing="-.03em" m="9px 0">Track facts. Understand context. Make better decisions.</Box><Text as="p" color="var(--text-2)" size={15} lineHeight={1.6}>Built for software teams, agencies, consultancies, BPO operations and distributed companies.</Text></Box><Grid className="marketing-feature-grid" columns="repeat(3,1fr)" gap={12}>{features.map(f => { const Icon = f.icon; return <Card key={f.title} interactive><CardBody><Box as="span" width={34} height={34} radius={7} display="grid" placeItems="center" bg="var(--accent-dim)" color="var(--accent)" mb={14}><Icon size={17}/></Box><Box as="h3" size={14} m="0 0 6px">{f.title}</Box><Text as="p" m={0} color="var(--text-2)" size={12} lineHeight={1.6}>{f.text}</Text></CardBody></Card>; })}</Grid></Box>
  <Box as="section" className="marketing-secondary-grid" display="grid" gridColumns="1fr 1fr" gap={14} p="74px 0"><Card><CardBody><Box as="span" display="inline-flex" mb={14} color="var(--accent)"><Monitor size={24}/></Box><Box as="h3" size={22} m="0 0 8px">Desktop agent</Box><Text as="p" color="var(--text-2)" lineHeight={1.65}>Offline-safe timer, applications, idle state, screenshots, multi-monitor capture and device health.</Text></CardBody></Card><Card><CardBody><Box as="span" display="inline-flex" mb={14} color="var(--accent)"><Globe2 size={24}/></Box><Box as="h3" size={22} m="0 0 8px">Browser intelligence</Box><Text as="p" color="var(--text-2)" lineHeight={1.65}>Domain-level activity, configurable productivity rules and privacy-first exclusions.</Text></CardBody></Card></Box>
  <Box as="section" textAlign="center" p="70px 24px" border="1px solid var(--border)" radius={14} bg="var(--surface)"><Box as="span" display="inline-flex" mb={12} color="var(--accent)"><Users size={26}/></Box><Box as="h2" size={34} letterSpacing="-.03em" m="0 0 10px">From hours to workforce intelligence.</Box><Box as="p" color="var(--text-2)" m="0 auto 22px" maxWidth={580}>Give managers operational clarity while keeping tracking rules visible and configurable for teams.</Box><Button size="lg" variant="primary" onClick={() => window.location.assign('/app')}>Create Workspace <ArrowRight size={15}/></Button></Box>
 </Page></main>
 </Box>;
}
