import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { Clock3, Download, Ellipsis, FileText, Folder, FolderPlus, HardDrive, History, Image as ImageIcon, Images, Library, Pencil, Plus, RefreshCw, RotateCcw, ShieldAlert, ShieldCheck, Star, Trash2, Upload, Users, Video, Volume2, WandSparkles } from 'lucide-react'
import { apiDownload, apiRequest } from '../api/client'
import { hasPermission } from '../access'
import { useAuth } from '../auth/AuthContext'
import { CardGridLoadingState, MediaLibraryLoadingState } from '../components/LoadingStates'
import { MediaThumbnail } from '../media/MediaThumbnail'
import { mediaUploadConstraintError, replaceMediaBinary, uploadMediaFiles, type MediaUploadCapabilities } from '../media/upload'
import type { MediaAsset, MediaCollection, MediaFolder, MediaRendition, MediaTag, MediaUsage, MediaVersion } from '../media/types'
import { Form, useConfirmAction, Alert, Badge, Box, Button, Checkbox, ChoiceList, ChoiceRow, DataGrid, type DataGridBulkAction, type DataGridColumn, Drawer, Dropdown, EmptyState, Field, FormDialog, Grid, HiddenFileInput, Inline, Input, Option, Page, PageHeader, Pressable, ProgressBar, SearchInput, Select, Stack, StatCard, Tabs, Text, Textarea, ViewModeToggle } from '../design-system'
import { useShellEntitySearch } from '../shellEntityFocus'

type LibraryResponse={data:MediaAsset[];meta:{current_page:number;last_page:number;per_page:number;total:number};folders:MediaFolder[];tags:MediaTag[];collections:MediaCollection[];summary:{active:number;trash:number;bytes:number;favorites:number;recent:number;collections:number;rights_attention:number}}
type Capabilities=MediaUploadCapabilities&{disk:string;writable:boolean;max_files_per_request:number;renditions_available?:boolean}
type LibrarySection='all'|'image'|'video'|'document'|'audio'|'favorites'|'recent'|'rights'|'collection'|'trash'
type DetailTab='details'|'usage'|'versions'|'renditions'
type QueueRow={name:string;status:'queued'|'uploading'|'done'|'failed';message?:string}
type CollectionMember={id:number;name:string}

/** Formats media byte sizes for user-facing library metadata. */
function bytes(value:number){if(value<1024)return `${value} B`;if(value<1024**2)return `${(value/1024).toFixed(1)} KB`;if(value<1024**3)return `${(value/1024**2).toFixed(1)} MB`;return `${(value/1024**3).toFixed(1)} GB`}
/** Downloads one authenticated blob without exposing its private storage path. */
async function downloadPrivate(url:string,workspaceId:number,fallback:string){const {blob,filename}=await apiDownload(url,workspaceId),href=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=href;anchor.download=filename||fallback;anchor.click();window.setTimeout(()=>URL.revokeObjectURL(href),500)}
/** Downloads one authenticated media asset. */
async function downloadAsset(asset:MediaAsset,workspaceId:number){return downloadPrivate(asset.download_url,workspaceId,asset.original_name)}
/** Return one concise label for an asset type. */
function categoryLabel(asset:MediaAsset){return asset.category==='document'?'Document':asset.category.charAt(0).toUpperCase()+asset.category.slice(1)}
/** Return one concise rights status label. */
function rightsLabel(asset:MediaAsset){return asset.rights_status==='expired'?'License expired':asset.rights_status==='expiring'?'License expiring':asset.rights_status==='review'?'Rights review due':asset.rights_status==='unclassified'?'Rights unclassified':'Rights clear'}
/** Return visual severity for DAM rights status. */
function rightsTone(asset:MediaAsset):'success'|'warning'|'danger'|'neutral'{return asset.rights_status==='clear'?'success':asset.rights_status==='expired'?'danger':asset.rights_status==='expiring'||asset.rights_status==='review'?'warning':'neutral'}
/** Return one icon for the primary DAM section. */
function sectionIcon(section:LibrarySection){if(section==='image')return <Images size={14}/>;if(section==='video')return <Video size={14}/>;if(section==='audio')return <Volume2 size={14}/>;if(section==='document')return <FileText size={14}/>;if(section==='favorites')return <Star size={14}/>;if(section==='recent')return <Clock3 size={14}/>;if(section==='rights')return <ShieldAlert size={14}/>;if(section==='trash')return <Trash2 size={14}/>;return <Library size={14}/>}

/** Renders the workspace DAM with governance, immutable binaries, renditions, bulk actions and resumable uploads. */
export default function MediaLibrary(){
 const confirmAction=useConfirmAction()
 const {session}=useAuth(),workspaceId=session?.user.activeWorkspaceId??0,workspace=session?.user.workspaces.find(item=>item.id===workspaceId)
 const canManage=hasPermission(workspace,'media.manage'),canRestoreTrash=hasPermission(workspace,'trash.restore')
 const [data,setData]=useState<LibraryResponse|null>(null),[capabilities,setCapabilities]=useState<Capabilities|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const [uploading,setUploading]=useState(false),[uploadProgress,setUploadProgress]=useState(0),[uploadError,setUploadError]=useState(''),[uploadQueue,setUploadQueue]=useState<QueueRow[]>([]),[dragging,setDragging]=useState(false)
 const [search,setSearch]=useState(''),[tagId,setTagId]=useState(''),[folderId,setFolderId]=useState(''),[collectionId,setCollectionId]=useState(''),[sort,setSort]=useState('newest'),[section,setSection]=useState<LibrarySection>('all'),[view,setView]=useState<'grid'|'table'>('grid'),[page,setPage]=useState(1)
 useShellEntitySearch('media',setSearch,()=>{setTagId('');setFolderId('');setCollectionId('');setSection('all');setPage(1)})
 const [selected,setSelected]=useState<MediaAsset|null>(null),[detailTab,setDetailTab]=useState<DetailTab>('details'),[usages,setUsages]=useState<MediaUsage[]>([]),[versions,setVersions]=useState<MediaVersion[]>([]),[renditions,setRenditions]=useState<MediaRendition[]>([]),[detailLoading,setDetailLoading]=useState(false)
 const [edit,setEdit]=useState({name:'',alt_text:'',caption:'',folder_id:'',tags:'',focal_x:'50',focal_y:'50',collection_ids:[] as number[],copyright_owner:'',license_type:'',license_reference:'',license_expires_at:'',usage_restrictions:'',rights_review_at:''})
 const [folderOpen,setFolderOpen]=useState(false),[editingFolder,setEditingFolder]=useState<MediaFolder|null>(null),[folderName,setFolderName]=useState(''),[folderParent,setFolderParent]=useState('')
 const [collectionOpen,setCollectionOpen]=useState(false),[editingCollection,setEditingCollection]=useState<MediaCollection|null>(null),[collectionName,setCollectionName]=useState(''),[collectionDescription,setCollectionDescription]=useState(''),[collectionVisibility,setCollectionVisibility]=useState<'workspace'|'restricted'>('workspace'),[collectionMemberIds,setCollectionMemberIds]=useState<number[]>([]),[collectionMembers,setCollectionMembers]=useState<CollectionMember[]>([])
 const [renditionForm,setRenditionForm]=useState({width:'640',height:'640',fit:'contain',format:'webp',quality:'82'}),[renditionBusy,setRenditionBusy]=useState(false),[replaceBusy,setReplaceBusy]=useState(false)
 const fileRef=useRef<HTMLInputElement|null>(null),replaceRef=useRef<HTMLInputElement|null>(null)

 /** Build one API query from the active DAM navigation and filters. */
 const queryString=(targetPage:number)=>{const params=new URLSearchParams({page:String(targetPage),per_page:'36',sort});if(search.trim())params.set('search',search.trim());if(tagId)params.set('tag_id',tagId);if(folderId)params.set('folder_id',folderId);if(section==='collection'&&collectionId)params.set('collection_id',collectionId);if(['image','video','audio','document'].includes(section))params.set('category',section);if(section==='favorites')params.set('favorite','1');if(section==='recent')params.set('recent','1');if(section==='rights')params.set('rights','attention');if(section==='trash')params.set('trash','1');return params}
 /** Loads one filtered Media Library page from the workspace DAM API. */
 const load=async(targetPage=page)=>{if(!workspaceId)return;setLoading(true);setError('');try{const response=await apiRequest<LibraryResponse>(`/api/v1/media?${queryString(targetPage)}`,{workspaceId,silent:true});setData(response);setPage(response.meta.current_page)}catch(reason){setError(reason instanceof Error?reason.message:'Media Library could not be loaded.')}finally{setLoading(false)}}
 /** Loads server upload limits and transform capabilities. */
 const loadCapabilities=async()=>{if(!workspaceId||!canManage)return;try{const response=await apiRequest<{data:Capabilities}>('/api/v1/media/capabilities',{workspaceId,silent:true});setCapabilities(response.data)}catch{setCapabilities(null)}}
 useEffect(()=>{void loadCapabilities()},[workspaceId,canManage])
 useEffect(()=>{const timer=window.setTimeout(()=>void load(1),180);return()=>window.clearTimeout(timer)},[workspaceId,search,tagId,folderId,collectionId,sort,section])

 /** Upload files into the current folder using direct or resumable transport as needed. */
 const upload=async(files:FileList|File[])=>{const list=Array.from(files);if(!list.length||!workspaceId||!canManage)return;const constraint=mediaUploadConstraintError(list,capabilities);if(constraint){setUploadError(constraint);return}setUploading(true);setUploadProgress(0);setUploadError('');setUploadQueue(list.map(file=>({name:file.name,status:'uploading'})));try{const response=await uploadMediaFiles(list,workspaceId,{folderId:folderId?Number(folderId):null,capabilities,onProgress:setUploadProgress});const failed=new Map((response.failures??[]).map(item=>[item.name,item.message]));setUploadQueue(list.map(file=>failed.has(file.name)?{name:file.name,status:'failed',message:failed.get(file.name)}:{name:file.name,status:'done'}));if(response.failures?.length)setUploadError(response.failures.map(item=>`${item.name}: ${item.message}`).join(' · '));await load(1);await loadCapabilities()}catch(reason){const message=reason instanceof Error?reason.message:'Media upload failed.';setUploadError(message);setUploadQueue(list.map(file=>({name:file.name,status:'failed',message})))}finally{setUploading(false);setUploadProgress(0);if(fileRef.current)fileRef.current.value=''}}
 /** Reload detail-side usage, immutable versions and generated renditions. */
 const loadDetails=async(asset:MediaAsset)=>{setDetailLoading(true);try{const [usageResult,versionResult,renditionResult]=await Promise.all([apiRequest<{data:MediaUsage[]}>(`/api/v1/media/${asset.id}/usages`,{workspaceId,silent:true}),apiRequest<{data:MediaVersion[]}>(`/api/v1/media/${asset.id}/versions`,{workspaceId,silent:true}),apiRequest<{data:MediaRendition[]}>(`/api/v1/media/${asset.id}/renditions`,{workspaceId,silent:true})]);setUsages(usageResult.data);setVersions(versionResult.data);setRenditions(renditionResult.data)}catch(reason){setUploadError(reason instanceof Error?reason.message:'Media detail context could not be loaded.')}finally{setDetailLoading(false)}}
 /** Opens the DAM details drawer and prepares governance/editor state. */
 const editAsset=async(asset:MediaAsset)=>{setSelected(asset);setDetailTab('details');setEdit({name:asset.name,alt_text:asset.alt_text??'',caption:asset.caption??'',folder_id:asset.folder?String(asset.folder.id):'',tags:asset.tags.map(tag=>tag.name).join(', '),focal_x:String(asset.focal_x??50),focal_y:String(asset.focal_y??50),collection_ids:asset.collections.map(collection=>collection.id),copyright_owner:asset.copyright_owner??'',license_type:asset.license_type??'',license_reference:asset.license_reference??'',license_expires_at:asset.license_expires_at??'',usage_restrictions:asset.usage_restrictions??'',rights_review_at:asset.rights_review_at??''});setUsages([]);setVersions([]);setRenditions([]);await loadDetails(asset)}
 /** Persist accessibility, governance, organization and focal-point metadata. */
 const saveAsset=async()=>{if(!selected||!canManage)return;const response=await apiRequest<{data:MediaAsset}>(`/api/v1/media/${selected.id}`,{method:'PUT',workspaceId,body:JSON.stringify({name:edit.name,alt_text:edit.alt_text||null,caption:edit.caption||null,folder_id:edit.folder_id?Number(edit.folder_id):null,focal_x:selected.category==='image'?Number(edit.focal_x):null,focal_y:selected.category==='image'?Number(edit.focal_y):null,tags:edit.tags.split(',').map(value=>value.trim()).filter(Boolean),collection_ids:edit.collection_ids,copyright_owner:edit.copyright_owner||null,license_type:edit.license_type||null,license_reference:edit.license_reference||null,license_expires_at:edit.license_expires_at||null,usage_restrictions:edit.usage_restrictions||null,rights_review_at:edit.rights_review_at||null})});setSelected(response.data);await loadDetails(response.data);await load()}
 /** Replace the current binary while retaining all earlier immutable binary versions. */
 const replaceBinary=async(files:FileList|null)=>{const file=files?.[0];if(!selected||!file||!canManage)return;const constraint=mediaUploadConstraintError([file],capabilities);if(constraint){setUploadError(constraint);return}setReplaceBusy(true);setUploadError('');try{const updated=await replaceMediaBinary(selected.id,file,workspaceId,setUploadProgress);setSelected(updated);setEdit(current=>({...current,focal_x:String(updated.focal_x??50),focal_y:String(updated.focal_y??50)}));await loadDetails(updated);await load()}catch(reason){setUploadError(reason instanceof Error?reason.message:'Media replacement failed.')}finally{setReplaceBusy(false);setUploadProgress(0);if(replaceRef.current)replaceRef.current.value=''}}
 /** Restore a prior binary/metadata snapshot as a new current version after confirmation. */
 const restoreVersion=async(version:MediaVersion)=>{if(!selected||!canManage||!version.binary_available)return;if(!await confirmAction({title:`Restore version ${version.version_number}?`,description:'The current binary remains preserved in history. Restoring creates a new current version rather than rewriting earlier versions.',confirmLabel:'Restore version'}))return;const response=await apiRequest<{data:MediaAsset}>(`/api/v1/media/${selected.id}/versions/${version.id}/restore`,{method:'POST',workspaceId});setSelected(response.data);await loadDetails(response.data);await load()}
 /** Generate one focal-point-aware private rendition. */
 const generateRendition=async(event:FormEvent)=>{event.preventDefault();if(!selected||selected.category!=='image'||!canManage)return;setRenditionBusy(true);try{const response=await apiRequest<{data:MediaRendition}>(`/api/v1/media/${selected.id}/renditions`,{method:'POST',workspaceId,body:JSON.stringify({width:Number(renditionForm.width),height:Number(renditionForm.height),fit:renditionForm.fit,format:renditionForm.format,quality:Number(renditionForm.quality)})});setRenditions(current=>[response.data,...current.filter(item=>item.id!==response.data.id)])}catch(reason){setUploadError(reason instanceof Error?reason.message:'Rendition could not be generated.')}finally{setRenditionBusy(false)}}
 /** Adds or removes one member-specific favorite without changing asset permissions. */
 const toggleFavorite=async(asset:MediaAsset)=>{await apiRequest(`/api/v1/media/${asset.id}/favorite`,{method:asset.is_favorite?'DELETE':'POST',workspaceId});setData(current=>current?{...current,data:current.data.map(row=>row.id===asset.id?{...row,is_favorite:!asset.is_favorite}:row),summary:{...current.summary,favorites:Math.max(0,current.summary.favorites+(asset.is_favorite?-1:1))}}:current);setSelected(current=>current?.id===asset.id?{...current,is_favorite:!asset.is_favorite}:current);if(section==='favorites'&&asset.is_favorite)await load()}
 /** Moves one active asset to recoverable Trash. */
 const trashAsset=async(asset:MediaAsset)=>{await apiRequest(`/api/v1/lifecycle/media/${asset.id}/trash`,{method:'POST',workspaceId});await load()}
 /** Restores one asset from Trash. */
 const restoreAsset=async(asset:MediaAsset)=>{await apiRequest(`/api/v1/trash/media/${asset.id}/restore`,{method:'POST',workspaceId});await load()}
 /** Permanently removes one trashed asset after explicit confirmation. */
 const purgeAsset=async(asset:MediaAsset)=>{if(!await confirmAction({title:'Permanently delete media?',description:`Permanently delete “${asset.name}”? Current, historical and rendition binaries will be removed.`,confirmLabel:'Delete permanently',danger:true}))return;await apiRequest(`/api/v1/trash/media/${asset.id}`,{method:'DELETE',workspaceId});await load()}

 /** Opens the folder editor for a new root or nested DAM folder. */
 const openFolderCreate=(parentId='')=>{setEditingFolder(null);setFolderName('');setFolderParent(parentId);setFolderOpen(true)}
 /** Opens the folder editor with current folder metadata. */
 const openFolderEdit=(folder:MediaFolder)=>{setEditingFolder(folder);setFolderName(folder.name);setFolderParent(folder.parent_id?String(folder.parent_id):'');setFolderOpen(true)}
 /** Creates or updates one physical DAM folder. */
 const saveFolder=async(event:FormEvent)=>{event.preventDefault();if(!folderName.trim()||!canManage)return;const body=JSON.stringify({name:folderName.trim(),parent_id:folderParent?Number(folderParent):null});await apiRequest(editingFolder?`/api/v1/media/folders/${editingFolder.id}`:'/api/v1/media/folders',{method:editingFolder?'PUT':'POST',workspaceId,body});setFolderOpen(false);setEditingFolder(null);await load()}
 /** Moves an empty folder to Trash after explicit confirmation. */
 const trashFolder=async(folder:MediaFolder)=>{if(!await confirmAction({title:'Move media folder to Trash?',description:`Move folder “${folder.name}” to Trash?`,confirmLabel:'Move to Trash',danger:true}))return;await apiRequest(`/api/v1/media/folders/${folder.id}`,{method:'DELETE',workspaceId});if(folderId===String(folder.id))setFolderId('');await load()}
 /** Load minimal workspace members available for restricted collection sharing. */
 const loadCollectionMembers=async()=>{if(!canManage||collectionMembers.length)return;try{const response=await apiRequest<{data:CollectionMember[]}>('/api/v1/media/collection-members',{workspaceId,silent:true});setCollectionMembers(response.data)}catch{setCollectionMembers([])}}
 /** Opens a new DAM collection editor. */
 const openCollectionCreate=()=>{setEditingCollection(null);setCollectionName('');setCollectionDescription('');setCollectionVisibility('workspace');setCollectionMemberIds([]);setCollectionOpen(true);void loadCollectionMembers()}
 /** Opens one existing collection for sharing/metadata changes. */
 const openCollectionEdit=(collection:MediaCollection)=>{setEditingCollection(collection);setCollectionName(collection.name);setCollectionDescription(collection.description??'');setCollectionVisibility(collection.visibility??'workspace');setCollectionMemberIds(collection.shared_member_ids??[]);setCollectionOpen(true);void loadCollectionMembers()}
 /** Creates or updates a reusable DAM collection with optional restricted membership. */
 const saveCollection=async(event:FormEvent)=>{event.preventDefault();if(!collectionName.trim()||!canManage)return;await apiRequest(editingCollection?`/api/v1/media/collections/${editingCollection.id}`:'/api/v1/media/collections',{method:editingCollection?'PUT':'POST',workspaceId,body:JSON.stringify({name:collectionName.trim(),description:collectionDescription.trim()||null,visibility:collectionVisibility,member_ids:collectionVisibility==='restricted'?collectionMemberIds:[]})});setCollectionOpen(false);setEditingCollection(null);await load()}
 /** Deletes only a collection container while preserving its assets. */
 const deleteCollection=async(collection:MediaCollection)=>{if(!await confirmAction({title:'Delete media collection?',description:`Delete “${collection.name}”? Assets stay in Media Library.`,confirmLabel:'Delete collection',danger:true}))return;await apiRequest(`/api/v1/media/collections/${collection.id}`,{method:'DELETE',workspaceId});if(collectionId===String(collection.id)){setCollectionId('');setSection('all')}await load()}
 /** Apply one server-bounded bulk action to the currently selected DataGrid rows. */
 const bulk=async(action:string,rows:MediaAsset[],extra:Record<string,unknown>={})=>{if(!rows.length)return;const destructive=action==='trash';if(destructive&&!await confirmAction({title:`Move ${rows.length} media asset(s) to Trash?`,description:'Assets currently in use will be rejected individually and remain active.',confirmLabel:'Move selected to Trash',danger:true}))return;const response=await apiRequest<{failures:{id:number;message:string}[]}>(`/api/v1/media/bulk`,{method:'POST',workspaceId,body:JSON.stringify({action,asset_ids:rows.map(row=>row.id),...extra})});if(response.failures?.length)setUploadError(response.failures.map(item=>`#${item.id}: ${item.message}`).join(' · '));await load()}

 const columns=useMemo<DataGridColumn<MediaAsset>[]>(()=>[
  {id:'favorite',header:'',hideable:false,cell:a=>section==='trash'?null:<Button variant="ghost" size="sm" iconOnly aria-label={a.is_favorite?`Remove ${a.name} from Favorites`:`Add ${a.name} to Favorites`} onClick={()=>void toggleFavorite(a)}>{a.is_favorite?<Star size={14} fill="currentColor"/>:<Star size={14}/>}</Button>},
  {id:'name',header:'Media',searchValue:a=>`${a.name} ${a.original_name} ${a.tags.map(tag=>tag.name).join(' ')}`,sortValue:a=>a.name,cell:a=><div className="media-table-name"><MediaThumbnail asset={a} workspaceId={workspaceId}/><div><strong>{a.name}</strong><span>{a.original_name}</span></div></div>},
  {id:'type',header:'Type',filterValue:a=>a.category,cell:a=><Badge tone="neutral">{categoryLabel(a)}</Badge>},
  {id:'rights',header:'Rights',filterValue:a=>a.rights_status,filter:{type:'select',label:'Rights',options:[{value:'clear',label:'Clear'},{value:'expired',label:'Expired'},{value:'expiring',label:'Expiring'},{value:'review',label:'Review due'},{value:'unclassified',label:'Unclassified'}]},cell:a=><Badge tone={rightsTone(a)}>{rightsLabel(a)}</Badge>},
  {id:'size',header:'Size',sortValue:a=>a.size_bytes,cell:a=>bytes(a.size_bytes)},
  {id:'folder',header:'Folder',filterValue:a=>a.folder?String(a.folder.id):'',cell:a=>a.folder?.name??'Library'},
  {id:'collections',header:'Collections',searchValue:a=>a.collections.map(item=>item.name).join(' '),cell:a=>a.collections.length?<Inline gap={4} wrap="wrap">{a.collections.slice(0,2).map(item=><Badge key={item.id}>{item.name}</Badge>)}{a.collections.length>2&&<Badge>+{a.collections.length-2}</Badge>}</Inline>:'—'},
  {id:'usage',header:'Usage',sortValue:a=>a.usages_count,cell:a=><Badge tone={a.usages_count?'accent':'neutral'}>{a.usages_count}</Badge>},
  {id:'versions',header:'Versions',sortValue:a=>a.versions_count,cell:a=>a.versions_count},
  {id:'renditions',header:'Renditions',sortValue:a=>a.renditions_count,defaultHidden:true,cell:a=>a.renditions_count},
  {id:'updated',header:'Updated',sortValue:a=>a.updated_at??'',cell:a=>a.updated_at?new Date(a.updated_at).toLocaleDateString():'—'},
  {id:'actions',header:'',hideable:false,cell:a=><Dropdown trigger={<Button variant="ghost" size="sm" iconOnly aria-label={`Actions for ${a.name}`}><Ellipsis size={15}/></Button>} items={section==='trash'?[{label:'Restore',icon:<RotateCcw size={14}/>,onClick:()=>void restoreAsset(a)},{label:'Delete permanently',icon:<Trash2 size={14}/>,danger:true,onClick:()=>void purgeAsset(a)}]:[{label:'Edit details',icon:<Pencil size={14}/>,onClick:()=>void editAsset(a)},{label:a.is_favorite?'Remove from Favorites':'Add to Favorites',icon:<Star size={14}/>,onClick:()=>void toggleFavorite(a)},{label:'Download',icon:<Download size={14}/>,onClick:()=>void downloadAsset(a,workspaceId)},...(canManage?[{separator:true as const},{label:'Move to Trash',icon:<Trash2 size={14}/>,danger:true,onClick:()=>void trashAsset(a)}]:[])]}/>},
 ],[section,workspaceId,canManage,data])
 const bulkActions=useMemo<DataGridBulkAction<MediaAsset>[]>(()=>{if(!canManage)return[];if(section==='trash')return canRestoreTrash?[{label:'Restore',icon:<RotateCcw size={13}/>,onClick:rows=>bulk('restore',rows)}]:[];const actions:DataGridBulkAction<MediaAsset>[]=[{label:'Favorite',icon:<Star size={13}/>,onClick:rows=>bulk('favorite',rows)},{label:'Unfavorite',onClick:rows=>bulk('unfavorite',rows)},{label:'Move to Trash',icon:<Trash2 size={13}/>,danger:true,onClick:rows=>bulk('trash',rows)}];if(folderId)actions.splice(2,0,{label:'Move to current folder',icon:<Folder size={13}/>,onClick:rows=>bulk('move_folder',rows,{folder_id:Number(folderId)})});if(collectionId)actions.splice(2,0,{label:'Add to current collection',icon:<Images size={13}/>,onClick:rows=>bulk('add_collection',rows,{collection_id:Number(collectionId)})});return actions},[canManage,canRestoreTrash,section,folderId,collectionId])
 /** Navigate to one DAM section while clearing mutually exclusive folder/tag state. */
 const nav=(next:LibrarySection,collection='')=>{setSection(next);setCollectionId(collection);setFolderId('');setTagId('');setPage(1)}
 const emptyFiltered=Boolean(search||tagId||folderId||collectionId||!['all','trash'].includes(section))

 return <Page><PageHeader title="Media Library" description="Digital asset management for reusable workspace files, binary history, rights governance and generated renditions." actions={canManage?<Inline gap={8}><Button variant="outline" onClick={openCollectionCreate}><Plus size={14}/> Collection</Button><Button variant="outline" onClick={()=>openFolderCreate()}><FolderPlus size={14}/> Folder</Button><Button variant="primary" loading={uploading} onClick={()=>fileRef.current?.click()}><Upload size={14}/> Upload</Button><HiddenFileInput ref={fileRef} multiple accept="image/*,video/*,audio/*,.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.zip" onChange={event=>void upload(event.target.files??[])}/></Inline>:undefined}/>
  {error&&<Alert tone="danger">{error}</Alert>}{uploadError&&<Alert tone="danger">{uploadError}</Alert>}
  {capabilities&&!capabilities.writable&&<Alert tone="danger"><strong>Media storage is not writable.</strong> Check <code>storage/app/private</code> permissions before uploading files.</Alert>}
  {loading&&!data?<MediaLibraryLoadingState/>:<>
   <Grid columns="repeat(auto-fit,minmax(150px,1fr))" gap={9}><StatCard label="Active media" value={data?.summary.active??0} sub="Reusable assets"/><StatCard label="Favorites" value={data?.summary.favorites??0} sub="Your saved assets"/><StatCard label="Collections" value={data?.summary.collections??0} sub="Reusable groups"/><StatCard label="Rights attention" value={data?.summary.rights_attention??0} sub="Expiry, review or unclassified"/><StatCard label="Storage" value={bytes(data?.summary.bytes??0)} sub={`${data?.summary.recent??0} updated recently`}/></Grid>
   <div className="media-library-layout media-dam-layout"><aside className="media-folders media-dam-nav"><div className="media-folders__head"><strong>Library</strong></div>
    {(['all','image','video','document','audio','favorites','recent','rights','trash'] as LibrarySection[]).map(item=><Pressable key={item} className={section===item?'is-active':''} onClick={()=>nav(item)}>{sectionIcon(item)} {item==='all'?'All media':item==='rights'?'Rights attention':item.charAt(0).toUpperCase()+item.slice(1)} <span>{item==='all'?data?.summary.active:item==='favorites'?data?.summary.favorites:item==='recent'?data?.summary.recent:item==='rights'?data?.summary.rights_attention:item==='trash'?data?.summary.trash:undefined}</span></Pressable>)}
    <div className="media-folders__head media-dam-nav__section"><strong>Collections</strong>{canManage&&<Button variant="ghost" size="sm" iconOnly aria-label="Create collection" onClick={openCollectionCreate}><Plus size={14}/></Button>}</div>
    {data?.collections.map(collection=><div key={collection.id} className={`media-folder-row${section==='collection'&&collectionId===String(collection.id)?' is-active':''}`}><Pressable type="button" onClick={()=>nav('collection',String(collection.id))}><Images size={14}/><span className="media-folder-row__name">{collection.name}</span>{collection.visibility==='restricted'&&<Users size={12}/>}<small>{collection.assets_count}</small></Pressable>{canManage&&<Dropdown trigger={<Button variant="ghost" size="sm" iconOnly aria-label={`Actions for ${collection.name}`}><Ellipsis size={13}/></Button>} items={[{label:'Edit collection',icon:<Pencil size={13}/>,onClick:()=>openCollectionEdit(collection)},{separator:true},{label:'Delete collection',icon:<Trash2 size={13}/>,danger:true,onClick:()=>void deleteCollection(collection)}]}/>}</div>)}
    <div className="media-folders__head media-dam-nav__section"><strong>Folders</strong>{canManage&&<Button variant="ghost" size="sm" iconOnly aria-label="Create folder" onClick={()=>openFolderCreate(folderId)}><FolderPlus size={14}/></Button>}</div>
    <Pressable className={!folderId&&section==='all'?'is-active':''} onClick={()=>{setFolderId('');setSection('all')}}><Folder size={14}/> Library root</Pressable>{data?.folders.map(folder=><div key={folder.id} className={`media-folder-row${folderId===String(folder.id)?' is-active':''}`}><Pressable type="button" onClick={()=>{setFolderId(String(folder.id));setSection('all');setCollectionId('')}} className={folder.parent_id?'is-nested':''}><Folder size={14}/><span className="media-folder-row__name">{folder.name}</span><small>{folder.assets_count}</small></Pressable>{canManage&&<Dropdown trigger={<Button variant="ghost" size="sm" iconOnly aria-label={`Actions for folder ${folder.name}`}><Ellipsis size={13}/></Button>} items={[{label:'Rename or move',icon:<Pencil size={13}/>,onClick:()=>openFolderEdit(folder)},{label:'New subfolder',icon:<FolderPlus size={13}/>,onClick:()=>openFolderCreate(String(folder.id))},{separator:true},{label:'Move folder to Trash',icon:<Trash2 size={13}/>,danger:true,onClick:()=>void trashFolder(folder)}]}/>}</div>)}
   </aside>
   <section className="media-library-main"><div className="media-library-toolbar"><SearchInput value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search names, tags, rights, alt text or captions…"/><Select value={tagId} onChange={event=>setTagId(event.target.value)}><Option value="">All tags</Option>{data?.tags.map(tag=><Option key={tag.id} value={tag.id}>{tag.name} ({tag.assets_count})</Option>)}</Select><Select value={sort} onChange={event=>setSort(event.target.value)}><Option value="newest">Recently updated</Option><Option value="oldest">Oldest first</Option><Option value="name">Name A–Z</Option><Option value="size">Largest first</Option></Select><ViewModeToggle value={view} onChange={setView} ariaLabel="Media view"/></div>
    {canManage&&section!=='trash'&&<div className={`media-dropzone${dragging?' is-dragging':''}${uploading?' is-busy':''}`} onDragEnter={event=>{event.preventDefault();setDragging(true)}} onDragOver={event=>event.preventDefault()} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);void upload(event.dataTransfer.files)}}><Upload size={20}/><Stack gap={5} flex="1"><Text weight={650}>{uploading?`Uploading ${uploadProgress}%`:'Drop files here to upload'}</Text><Text size={11} color="var(--text-3)">{capabilities?`Up to ${capabilities.max_files_per_request} files · ${capabilities.max_file_mb} MB each${capabilities.resumable_uploads?' · large files resume automatically':''}`:'Images, documents, audio and video. Executables are blocked.'}</Text>{uploading&&<ProgressBar value={uploadProgress} label="Media upload progress"/>}</Stack><Badge tone={capabilities?.writable?'success':'warning'}>{capabilities?.writable?<><ShieldCheck size={12}/> Storage ready</>:<><HardDrive size={12}/> Check storage</>}</Badge></div>}
    {uploadQueue.length>0&&<Box className="media-upload-queue"><Inline justify="space-between" align="center"><Text weight={650}>Upload queue</Text><Button variant="ghost" size="sm" disabled={uploading} onClick={()=>setUploadQueue([])}>Clear</Button></Inline><Stack gap={5}>{uploadQueue.slice(0,20).map((row,index)=><Inline key={`${row.name}-${index}`} justify="space-between" gap={8}><Text size={11}>{row.name}</Text><Badge tone={row.status==='done'?'success':row.status==='failed'?'danger':row.status==='uploading'?'accent':'neutral'}>{row.status}</Badge></Inline>)}</Stack></Box>}
    {view==='grid'&&canManage&&data?.data.length?<Alert tone="info">Switch to Table view to select multiple assets for bulk favorites, folder/collection moves, Trash and restore actions.</Alert>:null}
    {loading?<CardGridLoadingState cards={8}/>:data?.data.length?view==='table'?<DataGrid rows={data.data} columns={columns} rowKey={row=>row.id} searchable={false} persistKey="media-dam-v3-table" defaultPageSize={36} pageSizeOptions={[12,24,36,60]} onRefresh={()=>load()} bulkActions={bulkActions} empty={<EmptyState title="No media yet" text="Upload the first reusable asset for this workspace."/>}/>:<div className="media-grid">{data.data.map(asset=><article key={asset.id} className="media-card"><Pressable type="button" className="media-card__preview" onClick={()=>section==='trash'?undefined:void editAsset(asset)}><MediaThumbnail asset={asset} workspaceId={workspaceId}/>{asset.usages_count>0&&<span className="media-card__usage">Used {asset.usages_count}</span>}{asset.is_favorite&&<span className="media-card__favorite"><Star size={12} fill="currentColor"/></span>}</Pressable><div className="media-card__meta"><div><strong title={asset.name}>{asset.name}</strong><span>{bytes(asset.size_bytes)} · v{asset.versions_count} · r{asset.renditions_count}</span>{asset.rights_status!=='clear'&&<Badge tone={rightsTone(asset)}>{rightsLabel(asset)}</Badge>}</div><Dropdown trigger={<Button variant="ghost" size="sm" iconOnly aria-label={`Actions for ${asset.name}`}><Ellipsis size={15}/></Button>} items={section==='trash'?[{label:'Restore',icon:<RotateCcw size={14}/>,onClick:()=>void restoreAsset(asset)},{label:'Delete permanently',icon:<Trash2 size={14}/>,danger:true,onClick:()=>void purgeAsset(asset)}]:[{label:'Edit details',icon:<Pencil size={14}/>,onClick:()=>void editAsset(asset)},{label:asset.is_favorite?'Remove from Favorites':'Add to Favorites',icon:<Star size={14}/>,onClick:()=>void toggleFavorite(asset)},{label:'Download',icon:<Download size={14}/>,onClick:()=>void downloadAsset(asset,workspaceId)},...(canManage?[{separator:true as const},{label:'Move to Trash',icon:<Trash2 size={14}/>,danger:true,onClick:()=>void trashAsset(asset)}]:[])]}/></div></article>)}</div>:<EmptyState icon={section==='trash'?<Trash2 size={30}/>:section==='rights'?<ShieldAlert size={30}/>:<ImageIcon size={30}/>} title={section==='trash'?'Media Trash is empty':emptyFiltered?'No media matches this view':'No media yet'} text={section==='trash'?'Deleted media remains recoverable here until permanently removed.':section==='rights'?'No active assets currently need rights attention.':emptyFiltered?'Change the current section, collection or filters to find other assets.':'Upload images, video, documents or audio to create the workspace DAM.'} action={canManage&&section!=='trash'&&!emptyFiltered?<Button onClick={()=>fileRef.current?.click()}><Upload size={14}/> Upload first media</Button>:undefined}/>} 
    {(data?.meta.last_page??1)>1&&<Inline justify="center" gap={8}><Button variant="outline" size="sm" disabled={page<=1} onClick={()=>void load(page-1)}>Previous</Button><Text size={11}>Page {page} of {data?.meta.last_page}</Text><Button variant="outline" size="sm" disabled={page>=(data?.meta.last_page??1)} onClick={()=>void load(page+1)}>Next</Button></Inline>}
   </section></div>
  </>}

  <Drawer open={Boolean(selected)} onClose={()=>setSelected(null)} title="Media details" description="Manage binary history, accessibility, usage, rights and derived renditions.">{selected&&<Stack gap={12}><div className="media-details__hero"><MediaThumbnail asset={selected} workspaceId={workspaceId}/><Stack gap={5}><Inline gap={6} wrap="wrap"><Badge>{categoryLabel(selected)}</Badge>{selected.is_favorite&&<Badge tone="accent"><Star size={11}/> Favorite</Badge>}<Badge tone={rightsTone(selected)}>{rightsLabel(selected)}</Badge><Badge>{selected.usages_count} usages</Badge><Badge>v{selected.versions_count}</Badge><Badge>r{selected.renditions_count}</Badge></Inline><Text weight={650}>{selected.name}</Text><Text size={11} color="var(--text-3)">{selected.original_name} · {bytes(selected.size_bytes)}</Text></Stack></div><Tabs value={detailTab} onChange={value=>setDetailTab(value as DetailTab)} tabs={[{value:'details',label:'Details'},{value:'usage',label:`Usage (${selected.usages_count})`},{value:'versions',label:`Versions (${selected.versions_count})`},{value:'renditions',label:`Renditions (${selected.renditions_count})`}]} ariaLabel="Media details sections"/>
   {detailTab==='details'&&<Stack gap={10}><Inline gap={8} wrap="wrap"><Button variant={selected.is_favorite?'secondary':'outline'} size="sm" onClick={()=>void toggleFavorite(selected)}><Star size={13}/>{selected.is_favorite?' Favorited':' Add to Favorites'}</Button><Button variant="outline" size="sm" onClick={()=>void downloadAsset(selected,workspaceId)}><Download size={13}/> Download</Button>{canManage&&<Button variant="outline" size="sm" loading={replaceBusy} onClick={()=>replaceRef.current?.click()}><RefreshCw size={13}/> Replace file</Button>}<HiddenFileInput ref={replaceRef} onChange={event=>void replaceBinary(event.target.files)}/></Inline>{replaceBusy&&<ProgressBar value={uploadProgress} label="Replacement upload progress"/>}<Field label="Name"><Input disabled={!canManage} value={edit.name} onChange={event=>setEdit({...edit,name:event.target.value})}/></Field><Field label="Folder"><Select disabled={!canManage} value={edit.folder_id} onChange={event=>setEdit({...edit,folder_id:event.target.value})}><Option value="">Library root</Option>{data?.folders.map(folder=><Option key={folder.id} value={folder.id}>{folder.name}</Option>)}</Select></Field>{selected.category==='image'&&<><Field label="Alt text" hint="Describe meaningful visual content for accessibility."><Input disabled={!canManage} value={edit.alt_text} onChange={event=>setEdit({...edit,alt_text:event.target.value})}/></Field><Grid columns="1fr 1fr" gap={8}><Field label="Focal X (%)"><Input disabled={!canManage} type="number" min={0} max={100} value={edit.focal_x} onChange={event=>setEdit({...edit,focal_x:event.target.value})}/></Field><Field label="Focal Y (%)"><Input disabled={!canManage} type="number" min={0} max={100} value={edit.focal_y} onChange={event=>setEdit({...edit,focal_y:event.target.value})}/></Field></Grid></>}<Field label="Caption"><Input disabled={!canManage} value={edit.caption} onChange={event=>setEdit({...edit,caption:event.target.value})}/></Field><Field label="Tags" hint="Comma-separated reusable labels"><Input disabled={!canManage} value={edit.tags} onChange={event=>setEdit({...edit,tags:event.target.value})} placeholder="brand, office, campaign"/></Field>{data?.collections.length?<Field label="Collections" hint="Collections group assets without moving their folder."><ChoiceList columns={1} maxHeight="sm">{data.collections.map(collection=>{const checked=edit.collection_ids.includes(collection.id);return <ChoiceRow key={collection.id} selected={checked}><Checkbox disabled={!canManage} checked={checked} onChange={()=>setEdit(current=>({...current,collection_ids:checked?current.collection_ids.filter(id=>id!==collection.id):[...current.collection_ids,collection.id]}))}/><span>{collection.name}</span><Badge>{collection.assets_count}</Badge></ChoiceRow>})}</ChoiceList></Field>:null}
    <Box><Stack gap={9}><Inline gap={7} align="center"><ShieldCheck size={15}/><Text weight={650}>Rights & governance</Text></Inline><Grid columns="1fr 1fr" gap={8}><Field label="Copyright owner"><Input disabled={!canManage} value={edit.copyright_owner} onChange={event=>setEdit({...edit,copyright_owner:event.target.value})} placeholder="Company or creator"/></Field><Field label="License type"><Input disabled={!canManage} value={edit.license_type} onChange={event=>setEdit({...edit,license_type:event.target.value})} placeholder="Owned, licensed, stock…"/></Field><Field label="License reference"><Input disabled={!canManage} value={edit.license_reference} onChange={event=>setEdit({...edit,license_reference:event.target.value})} placeholder="Agreement, source or receipt"/></Field><Field label="License expires"><Input disabled={!canManage} type="date" value={edit.license_expires_at} onChange={event=>setEdit({...edit,license_expires_at:event.target.value})}/></Field><Field label="Rights review date"><Input disabled={!canManage} type="date" value={edit.rights_review_at} onChange={event=>setEdit({...edit,rights_review_at:event.target.value})}/></Field></Grid><Field label="Usage restrictions"><Textarea disabled={!canManage} rows={3} value={edit.usage_restrictions} onChange={event=>setEdit({...edit,usage_restrictions:event.target.value})} placeholder="Territory, channel, attribution, duration or other restrictions"/></Field></Stack></Box>
    <Grid columns="repeat(3,minmax(0,1fr))" gap={6}><StatCard label="Usage" value={selected.usages_count} sub="Active references"/><StatCard label="Versions" value={selected.versions_count} sub="Immutable snapshots"/><StatCard label="Renditions" value={selected.renditions_count} sub="Derived images"/></Grid>{canManage&&<Button variant="primary" onClick={()=>void saveAsset()}>Save details</Button>}</Stack>}
   {detailTab==='usage'&&(detailLoading?<CardGridLoadingState cards={3}/>:usages.length?<Stack gap={7}>{usages.map(usage=><Box key={usage.id} className="media-dam-usage"><Text weight={650}>{usage.label||usage.resource_type}</Text><Text size={10.5} color="var(--text-3)">{usage.resource_type}{usage.resource_id?` #${usage.resource_id}`:''}{usage.field?` · ${usage.field}`:''}</Text></Box>)}</Stack>:<EmptyState title="No active usages" text="This asset is not currently referenced by a registered workspace resource."/>)}
   {detailTab==='versions'&&(detailLoading?<CardGridLoadingState cards={3}/>:versions.length?<Stack gap={7}>{versions.map(version=><Box key={version.id} className="media-dam-version"><Inline justify="space-between" gap={8}><Inline gap={6} align="center"><History size={13}/><Text weight={650}>Version {version.version_number}</Text>{version.binary_available?<Badge tone={version.binary_status==='quarantined'?'danger':'success'}>{version.binary_status==='quarantined'?'Quarantined binary':'Binary preserved'}</Badge>:<Badge tone="warning">Metadata only</Badge>}</Inline><Text size={10.5} color="var(--text-3)">{version.created_at?new Date(version.created_at).toLocaleString():'—'}</Text></Inline><Text size={11}>{version.name}</Text><Text size={10.5} color="var(--text-3)">{version.reason||'DAM snapshot'}{version.creator?` · ${version.creator}`:''}{version.size_bytes?` · ${bytes(version.size_bytes)}`:''}{version.tags.length?` · ${version.tags.join(', ')}`:''}</Text><Inline gap={6}>{version.download_url&&<Button size="sm" variant="outline" onClick={()=>void downloadPrivate(version.download_url!,workspaceId,`${version.name}-v${version.version_number}`)}><Download size={12}/> Download version</Button>}{canManage&&version.binary_available&&version.binary_status!=='quarantined'&&<Button size="sm" variant="ghost" onClick={()=>void restoreVersion(version)}><RotateCcw size={12}/> Restore as current</Button>}</Inline></Box>)}</Stack>:<EmptyState title="No version history" text="New uploads and changes create immutable DAM snapshots."/>)}
   {detailTab==='renditions'&&(selected.category!=='image'?<EmptyState title="Renditions are for raster images" text="Documents, audio and video keep their original binary versions but are not resized by the image rendition service."/>:<Stack gap={10}>{canManage&&<Box><Form onSubmit={generateRendition}><Stack gap={9}><Inline gap={7} align="center"><WandSparkles size={15}/><Text weight={650}>Generate rendition</Text></Inline><Grid columns="1fr 1fr" gap={8}><Field label="Width"><Input type="number" min={32} max={4096} value={renditionForm.width} onChange={event=>setRenditionForm({...renditionForm,width:event.target.value})}/></Field><Field label="Height"><Input type="number" min={32} max={4096} value={renditionForm.height} onChange={event=>setRenditionForm({...renditionForm,height:event.target.value})}/></Field><Field label="Fit"><Select value={renditionForm.fit} onChange={event=>setRenditionForm({...renditionForm,fit:event.target.value})}><Option value="contain">Contain</Option><Option value="cover">Cover using focal point</Option></Select></Field><Field label="Format"><Select value={renditionForm.format} onChange={event=>setRenditionForm({...renditionForm,format:event.target.value})}><Option value="webp">WebP</Option><Option value="jpeg">JPEG</Option><Option value="png">PNG</Option></Select></Field><Field label="Quality"><Input type="number" min={40} max={95} value={renditionForm.quality} onChange={event=>setRenditionForm({...renditionForm,quality:event.target.value})}/></Field></Grid><Button type="submit" loading={renditionBusy} disabled={capabilities?.renditions_available===false}>Generate rendition</Button>{capabilities?.renditions_available===false&&<Alert tone="warning">PHP GD is not available on this server, so image renditions cannot be generated here.</Alert>}</Stack></Form></Box>}{detailLoading?<CardGridLoadingState cards={3}/>:renditions.length?<Stack gap={7}>{renditions.map(item=><Box key={item.id}><Inline justify="space-between" gap={8}><Text weight={650}>{item.width}×{item.height} · {item.format.toUpperCase()}</Text><Badge>{item.fit}</Badge></Inline><Text size={10.5} color="var(--text-3)">{bytes(item.size_bytes)} · quality {item.quality}</Text><Button size="sm" variant="outline" onClick={()=>void downloadPrivate(item.content_url,workspaceId,`${selected.name}-${item.width}x${item.height}.${item.format==='jpeg'?'jpg':item.format}`)}><Download size={12}/> Download rendition</Button></Box>)}</Stack>:<EmptyState title="No generated renditions" text="Generate reusable transformed images without changing the original binary."/>}</Stack>)}
  </Stack>}</Drawer>

  <FormDialog open={folderOpen} onClose={()=>{setFolderOpen(false);setEditingFolder(null)}} title={editingFolder?'Edit media folder':'Create media folder'} description="Folders define physical library organization; collections can group assets across folders." formId="media-folder-form" onSubmit={saveFolder} submitLabel={editingFolder?'Save folder':'Create folder'} disabled={!folderName.trim()}><Field label="Folder name"><Input autoFocus value={folderName} onChange={event=>setFolderName(event.target.value)} placeholder="Brand assets"/></Field><Field label="Parent folder"><Select value={folderParent} onChange={event=>setFolderParent(event.target.value)}><Option value="">Library root</Option>{data?.folders.filter(folder=>folder.id!==editingFolder?.id).map(folder=><Option key={folder.id} value={folder.id}>{folder.name}</Option>)}</Select></Field></FormDialog>
  <FormDialog open={collectionOpen} onClose={()=>{setCollectionOpen(false);setEditingCollection(null)}} title={editingCollection?'Edit media collection':'Create media collection'} description="Collections group assets without moving their physical folder and can be workspace-wide or restricted." formId="media-collection-form" onSubmit={saveCollection} submitLabel={editingCollection?'Save collection':'Create collection'} disabled={!collectionName.trim()}><Field label="Collection name"><Input autoFocus value={collectionName} onChange={event=>setCollectionName(event.target.value)} placeholder="Brand launch"/></Field><Field label="Description"><Input value={collectionDescription} onChange={event=>setCollectionDescription(event.target.value)} placeholder="Reusable campaign and brand assets"/></Field><Field label="Visibility"><Select value={collectionVisibility} onChange={event=>setCollectionVisibility(event.target.value as 'workspace'|'restricted')}><Option value="workspace">Workspace — visible to media viewers</Option><Option value="restricted">Restricted — creator, media managers and selected members</Option></Select></Field>{collectionVisibility==='restricted'&&<Field label="Shared members" hint="Sharing a collection does not grant access to Media Library itself."><ChoiceList columns={1} maxHeight="md">{collectionMembers.map(member=>{const checked=collectionMemberIds.includes(member.id);return <ChoiceRow key={member.id} selected={checked}><Checkbox checked={checked} onChange={()=>setCollectionMemberIds(current=>checked?current.filter(id=>id!==member.id):[...current,member.id])}/><span>{member.name}</span></ChoiceRow>})}{!collectionMembers.length&&<Text color="var(--text-3)">No active members available.</Text>}</ChoiceList></Field>}</FormDialog>
 </Page>
}
