import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Check, ChevronLeft, ChevronRight, History, LockKeyhole, Pencil, Plus, Send, Trash2, UnlockKeyhole, X } from 'lucide-react'
import { apiRequest } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import { BooleanField, useConfirmAction, FormDialog, ErrorState, EmptyState, Alert, Avatar, Badge, Button, DataGrid, Field, Input, Page, PageHeader, Segmented, Select, StatCard, Textarea, Grid, Inline, Stack, Text, Option, type DataGridColumn } from '../design-system'
import { PageLoadingState } from '../components/LoadingStates'

type Day={date:string;label:string}
type Row={member_id:number;name:string;job_title:string|null;days:Record<string,number>;total_seconds:number;pending_count:number;period_id:number|null;period_status:string}
type Entry={id:number;member_id:number;employee:string|null;project_id:number|null;task_id:number|null;project:string|null;task:string|null;date:string;started_at:string;ended_at:string;duration_seconds:number;billable:boolean;source:string;approval_status:string;note:string|null}
type Project={id:number;name:string}
type Task={id:number;project_id:number;title:string}
type Action={id:number;action:string;previous_status:string|null;new_status:string|null;note:string|null;created_at:string;member:{user:{first_name:string;last_name:string}};actor:{first_name:string;last_name:string}|null}
type Payload={week_start:string;week_end:string;days:Day[];summary:{tracked_seconds:number;billable_seconds:number;non_billable_seconds:number;pending_count:number;approved_count:number};rows:Row[];entries:Entry[];projects:Project[];tasks:Task[];current_member_id:number;can_manage:boolean;history:Action[]}
type TimeForm={member_id:string;project_id:string;task_id:string;date:string;start_time:string;end_time:string;billable:boolean;note:string}

/** Formats fmt data for display. */ const fmt=(seconds:number)=>{if(!seconds)return '—';const h=Math.floor(seconds/3600);const m=Math.floor((seconds%3600)/60);return `${h}h${m?` ${m}m`:''}`}
/** Handles the time operation for the WorkIntel client. */ const time=(iso:string)=>new Date(iso).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})
/** Handles the add days operation for the WorkIntel client. */ const addDays=(date:string,days:number)=>{const value=new Date(`${date}T00:00:00`);value.setDate(value.getDate()+days);return value.toISOString().slice(0,10)}
/** Handles the iso time operation for the WorkIntel client. */ const isoTime=(iso:string)=>new Date(iso).toTimeString().slice(0,5)

/** Handles the timesheets operation for the WorkIntel client. */ export default function Timesheets(){
 const confirmAction=useConfirmAction()
 const {session}=useAuth();const workspaceId=session?.user.activeWorkspaceId??0;const workspace=session?.user.workspaces.find(item=>item.id===workspaceId)
 const [data,setData]=useState<Payload|null>(null);const [start,setStart]=useState('');const [view,setView]=useState<'weekly'|'entries'|'history'>('weekly');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('')
 const [modalOpen,setModalOpen]=useState(false);const [editing,setEditing]=useState<Entry|null>(null);const [form,setForm]=useState<TimeForm>({member_id:'',project_id:'',task_id:'',date:'',start_time:'09:00',end_time:'10:00',billable:true,note:''})
 /** Loads load data required by the current view. */ const load=async(nextStart?:string)=>{if(!workspaceId)return;setLoading(true);setError('');try{const query=nextStart!==undefined?nextStart:start;const payload=await apiRequest<Payload>(`/api/v1/timesheets/week${query?`?start=${query}`:''}`,{workspaceId});setData(payload);setStart(payload.week_start)}catch(err){setError(err instanceof Error?err.message:'Could not load timesheets.')}finally{setLoading(false)}}
 useEffect(()=>{void load('')},[workspaceId])
 useEffect(()=>{/** Handles the handler event for the current workflow. */ const handler=()=>void load();window.addEventListener('workintel:time-entry-created',handler);return()=>window.removeEventListener('workintel:time-entry-created',handler)},[workspaceId,start])
 const pendingIds=useMemo(()=>data?.entries.filter(entry=>['draft','submitted'].includes(entry.approval_status)).map(entry=>entry.id)??[],[data])
 const currentRow=data?.rows.find(row=>row.member_id===data.current_member_id)
 const filteredTasks=data?.tasks.filter(task=>!form.project_id||task.project_id===Number(form.project_id))??[]
 /** Handles the open create operation for the WorkIntel client. */ const openCreate=()=>{if(!data)return;setEditing(null);setForm({member_id:String(data.current_member_id),project_id:data.projects[0]?String(data.projects[0].id):'',task_id:'',date:data.week_start,start_time:'09:00',end_time:'10:00',billable:true,note:''});setError('');setModalOpen(true)}
 /** Handles the open edit operation for the WorkIntel client. */ const openEdit=(entry:Entry)=>{setEditing(entry);setForm({member_id:String(entry.member_id),project_id:entry.project_id?String(entry.project_id):'',task_id:entry.task_id?String(entry.task_id):'',date:entry.date,start_time:isoTime(entry.started_at),end_time:isoTime(entry.ended_at),billable:entry.billable,note:entry.note??''});setError('');setModalOpen(true)}
 /** Handles the save entry operation for the WorkIntel client. */ const saveEntry=async(e:FormEvent)=>{e.preventDefault();if(!workspaceId)return;setSaving(true);setError('');try{await apiRequest(editing?`/api/v1/timesheets/entries/${editing.id}`:'/api/v1/timesheets/entries',{method:editing?'PUT':'POST',workspaceId,body:JSON.stringify({member_id:form.member_id?Number(form.member_id):undefined,project_id:form.project_id?Number(form.project_id):null,task_id:form.task_id?Number(form.task_id):null,started_at:`${form.date}T${form.start_time}:00`,ended_at:`${form.date}T${form.end_time}:00`,billable:form.billable,note:form.note||null})});setModalOpen(false);await load()}catch(err){setError(err instanceof Error?err.message:'Could not save time entry.')}finally{setSaving(false)}}
 /** Handles the remove entry operation for the WorkIntel client. */ const removeEntry=async(entry:Entry)=>{if(!workspaceId||!await confirmAction({title:'Delete time entry?',description:'This manual time entry will be removed.',confirmLabel:'Delete',danger:true}))return;setError('');try{await apiRequest(`/api/v1/timesheets/entries/${entry.id}`,{method:'DELETE',workspaceId});await load()}catch(err){setError(err instanceof Error?err.message:'Could not delete time entry.')}}
 /** Updates update approval state for the current workflow. */ const updateApproval=async(entry:Entry,status:'approved'|'rejected')=>{if(!workspaceId)return;setSaving(true);setError('');try{await apiRequest(`/api/v1/timesheets/entries/${entry.id}/approval`,{method:'PATCH',workspaceId,body:JSON.stringify({status})});await load()}catch(err){setError(err instanceof Error?err.message:'Could not update approval.')}finally{setSaving(false)}}
 /** Handles the bulk approve operation for the WorkIntel client. */ const bulkApprove=async()=>{if(!workspaceId||!pendingIds.length)return;setSaving(true);setError('');try{await apiRequest('/api/v1/timesheets/entries/bulk-approve',{method:'POST',workspaceId,body:JSON.stringify({entry_ids:pendingIds})});await load()}catch(err){setError(err instanceof Error?err.message:'Could not approve entries.')}finally{setSaving(false)}}
 /** Handles the submit week operation for the WorkIntel client. */ const submitWeek=async()=>{if(!workspaceId||!data)return;setSaving(true);setError('');try{await apiRequest('/api/v1/timesheets/submit',{method:'POST',workspaceId,body:JSON.stringify({week_start:data.week_start})});await load()}catch(err){setError(err instanceof Error?err.message:'Could not submit timesheet.')}finally{setSaving(false)}}
 /** Updates set lock state for the current workflow. */ const setLock=async(row:Row,lock:boolean)=>{if(!workspaceId||!row.period_id)return;setSaving(true);setError('');try{await apiRequest(`/api/v1/timesheets/periods/${row.period_id}/${lock?'lock':'unlock'}`,{method:'POST',workspaceId});await load()}catch(err){setError(err instanceof Error?err.message:'Could not update timesheet lock.')}finally{setSaving(false)}}
 if(loading&&!data)return <PageLoadingState/>
 if(!data)return <Page><ErrorState title="Timesheet data unavailable" text={error||'Timesheet data could not be loaded.'} retry={()=>load()}/></Page>
 const period=`${new Date(`${data.week_start}T00:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'})} – ${new Date(`${data.week_end}T00:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}`
 /** Renders the current weekly period state using the shared status badge. */ const periodBadge=(row:Row)=><Badge tone={row.period_status==='approved'?'success':row.period_status==='locked'?'neutral':row.pending_count?'warning':'success'} dot>{row.period_status==='approved'?'Approved':row.period_status==='locked'?'Locked':row.period_status==='submitted'?'Submitted':row.pending_count?`${row.pending_count} pending`:'Open'}</Badge>
 const weeklyColumns:DataGridColumn<Row>[]=[
  {id:'employee',header:'Employee',sortValue:row=>row.name,searchValue:row=>`${row.name} ${row.job_title??''}`,cell:row=><Inline align="center" gap={8}><Avatar name={row.name} size="sm"/><Stack gap={2}><Text weight={550}>{row.name}</Text><Text size={10.5} color="var(--text-3)">{row.job_title||'Team member'}</Text></Stack></Inline>},
  ...data.days.map(day=>({id:`day-${day.date}`,header:day.label,sortValue:(row:Row)=>row.days[day.date]??0,cell:(row:Row)=><Text className="stat-num">{fmt(row.days[day.date]??0)}</Text>} as DataGridColumn<Row>)),
  {id:'total',header:'Total',sortValue:row=>row.total_seconds,cell:row=><Text className="stat-num" weight={650}>{fmt(row.total_seconds)}</Text>},
  {id:'status',header:'Status',sortValue:row=>row.period_status,filterValue:row=>row.period_status,filter:{type:'select',label:'Status',options:[{value:'open',label:'Open'},{value:'submitted',label:'Submitted'},{value:'approved',label:'Approved'},{value:'locked',label:'Locked'}]},cell:periodBadge},
  ...(data.can_manage?[{id:'actions',header:'',hideable:false,cell:(row:Row)=>row.period_id&&row.period_status!=='approved'?<Button variant="ghost" size="sm" iconOnly aria-label={row.period_status==='locked'?'Unlock timesheet':'Lock timesheet'} loading={saving} disabled={row.period_status!=='locked'&&row.pending_count>0} onClick={()=>void setLock(row,row.period_status!=='locked')}>{row.period_status==='locked'?<UnlockKeyhole size={13}/>:<LockKeyhole size={13}/>}</Button>:null} as DataGridColumn<Row>]:[]),
 ]
 const entryColumns:DataGridColumn<Entry>[]=[
  {id:'employee',header:'Employee',sortValue:entry=>entry.employee??'',searchValue:entry=>entry.employee??'',cell:entry=><Text weight={550}>{entry.employee||'Unknown'}</Text>},
  {id:'project',header:'Project',sortValue:entry=>entry.project??'',searchValue:entry=>entry.project??'',cell:entry=><Text color="var(--text-2)">{entry.project||'—'}</Text>},
  {id:'task',header:'Task / note',sortValue:entry=>entry.task??entry.note??'',searchValue:entry=>`${entry.task??''} ${entry.note??''}`,cell:entry=><Text color="var(--text-2)">{entry.task||entry.note||'—'}</Text>},
  {id:'date',header:'Date',sortValue:entry=>entry.date,filterValue:entry=>entry.date,filter:{type:'dateRange',label:'Date'},cell:entry=>entry.date},
  {id:'start',header:'Start',sortValue:entry=>entry.started_at,cell:entry=><Text className="stat-num">{time(entry.started_at)}</Text>},
  {id:'end',header:'End',sortValue:entry=>entry.ended_at,cell:entry=><Text className="stat-num">{time(entry.ended_at)}</Text>},
  {id:'duration',header:'Duration',sortValue:entry=>entry.duration_seconds,cell:entry=><Text className="stat-num" weight={650}>{fmt(entry.duration_seconds)}</Text>},
  {id:'billing',header:'Billing',sortValue:entry=>entry.billable?1:0,filterValue:entry=>entry.billable?'billable':'internal',filter:{type:'select',label:'Billing',options:[{value:'billable',label:'Billable'},{value:'internal',label:'Internal'}]},cell:entry=><Badge tone={entry.billable?'success':'neutral'}>{entry.billable?'Billable':'Internal'}</Badge>},
  {id:'source',header:'Source',sortValue:entry=>entry.source,filterValue:entry=>entry.source,cell:entry=><Badge>{entry.source}</Badge>},
  {id:'status',header:'Status',sortValue:entry=>entry.approval_status,filterValue:entry=>entry.approval_status,filter:{type:'select',label:'Status',options:['draft','submitted','approved','rejected'].map(value=>({value,label:value[0].toUpperCase()+value.slice(1)}))},cell:entry=><Badge tone={entry.approval_status==='approved'?'success':entry.approval_status==='rejected'?'danger':'warning'} dot>{entry.approval_status}</Badge>},
  {id:'actions',header:'',hideable:false,cell:entry=><Inline gap={3}>{entry.approval_status!=='approved'&&<><Button variant="ghost" size="sm" iconOnly aria-label="Edit time entry" onClick={()=>openEdit(entry)}><Pencil size={13}/></Button><Button variant="ghost" size="sm" iconOnly aria-label="Delete time entry" onClick={()=>void removeEntry(entry)}><Trash2 size={13}/></Button></>}{data.can_manage&&['draft','submitted'].includes(entry.approval_status)&&<><Button variant="ghost" size="sm" iconOnly aria-label="Approve" disabled={saving} onClick={()=>void updateApproval(entry,'approved')}><Check size={13} color="var(--success)"/></Button><Button variant="ghost" size="sm" iconOnly aria-label="Reject" disabled={saving} onClick={()=>void updateApproval(entry,'rejected')}><X size={13} color="var(--danger)"/></Button></>}</Inline>},
 ]
 const historyColumns:DataGridColumn<Action>[]=[
  {id:'when',header:'When',sortValue:action=>action.created_at,filterValue:action=>action.created_at,filter:{type:'dateRange',label:'When'},cell:action=>new Date(action.created_at).toLocaleString()},
  {id:'employee',header:'Employee',sortValue:action=>`${action.member.user.first_name} ${action.member.user.last_name}`,searchValue:action=>`${action.member.user.first_name} ${action.member.user.last_name}`,cell:action=>`${action.member.user.first_name} ${action.member.user.last_name}`},
  {id:'action',header:'Action',sortValue:action=>action.action,filterValue:action=>action.action,cell:action=><Badge tone={action.action==='approved'?'success':action.action==='rejected'?'danger':action.action==='locked'?'neutral':'info'} dot>{action.action}</Badge>},
  {id:'from',header:'From',sortValue:action=>action.previous_status??'',cell:action=>action.previous_status||'—'},
  {id:'to',header:'To',sortValue:action=>action.new_status??'',cell:action=>action.new_status||'—'},
  {id:'by',header:'By',sortValue:action=>action.actor?`${action.actor.first_name} ${action.actor.last_name}`:'System',cell:action=>action.actor?`${action.actor.first_name} ${action.actor.last_name}`:'System'},
  {id:'note',header:'Note',searchValue:action=>action.note??'',cell:action=><Text color="var(--text-2)">{action.note||'—'}</Text>},
 ]
 const sheetTitle=workspace?.role==='employee'?'My Timesheet':workspace?.role==='manager'||workspace?.role==='team-lead'?'Team Timesheets':'Timesheets'; return <Page><PageHeader title={sheetTitle} description={period} actions={<><Button variant="outline" size="sm" onClick={()=>void load(addDays(data.week_start,-7))}><ChevronLeft size={13}/> Prev</Button><Button variant="secondary" size="sm" onClick={()=>void load('')}>This Week</Button><Button variant="outline" size="sm" onClick={()=>void load(addDays(data.week_start,7))}>Next <ChevronRight size={13}/></Button><Segmented value={view} onChange={setView} options={[{value:'weekly',label:'Weekly'},{value:'entries',label:'Entries'},{value:'history',label:<><History size={13}/> History</>}]}/><Button variant="outline" size="sm" onClick={openCreate} disabled={['locked','approved'].includes(currentRow?.period_status||'')}><Plus size={13}/> Add Time</Button><Button variant="secondary" size="sm" loading={saving} disabled={['locked','approved','submitted'].includes(currentRow?.period_status||'')} onClick={()=>void submitWeek()}><Send size={13}/> Submit Week</Button>{data.can_manage&&<Button variant="primary" size="sm" loading={saving} disabled={!pendingIds.length} onClick={()=>void bulkApprove()}><Check size={13}/> Bulk Approve</Button>}</>}/>{error&&<Alert tone="danger">{error}</Alert>}
 <Grid columns="repeat(4,minmax(0,1fr))" gap={12} m="14px 0 16px"><StatCard label="Total Tracked" value={fmt(data.summary.tracked_seconds)} sub={`${data.entries.length} entries`}/><StatCard label="Billable" value={fmt(data.summary.billable_seconds)} sub="Client chargeable"/><StatCard label="Non-billable" value={fmt(data.summary.non_billable_seconds)} sub="Internal work"/><StatCard label="Pending Approval" value={String(data.summary.pending_count)} sub={`${data.summary.approved_count} approved`}/></Grid>
 {view==='weekly'?<DataGrid rows={data.rows} columns={weeklyColumns} rowKey={row=>row.member_id} persistKey="timesheets.weekly" searchPlaceholder="Search employee…" defaultSort={{id:'employee',direction:'asc'}} onRefresh={()=>load()} empty={<EmptyState title="No weekly timesheet rows are available." text="Tracked time will appear here for the selected week."/>} mobileCard={row=><Stack gap={6}><Inline justify="space-between" align="center"><strong>{row.name}</strong>{periodBadge(row)}</Inline><Text size={11} color="var(--text-2)">{row.job_title||'Team member'} · {fmt(row.total_seconds)} tracked</Text></Stack>}/>:view==='entries'?<DataGrid rows={data.entries} columns={entryColumns} rowKey={entry=>entry.id} persistKey="timesheets.entries" searchPlaceholder="Search employee, project, task or note…" defaultSort={{id:'date',direction:'desc'}} onRefresh={()=>load()} empty={<EmptyState title="No time entries for this week." text="Add manual time or start a timer to create the first entry."/>} mobileCard={entry=><Stack gap={6}><Inline justify="space-between" align="center"><strong>{entry.employee||'Unknown'}</strong><Badge tone={entry.approval_status==='approved'?'success':entry.approval_status==='rejected'?'danger':'warning'}>{entry.approval_status}</Badge></Inline><Text size={11} color="var(--text-2)">{entry.project||'No project'} · {entry.date} · {fmt(entry.duration_seconds)}</Text></Stack>}/>:<DataGrid rows={data.history} columns={historyColumns} rowKey={action=>action.id} persistKey="timesheets.history" searchPlaceholder="Search approval history…" defaultSort={{id:'when',direction:'desc'}} onRefresh={()=>load()} empty={<EmptyState title="No approval workflow history for this week yet." text="Submission, approval, rejection and lock events will appear here."/>}/>} 
 <FormDialog open={modalOpen} onClose={()=>setModalOpen(false)} title={editing?'Edit time entry':'Add manual time'} description="Manual entries remain editable until approved or the weekly timesheet is locked." formId="manual-time-form" onSubmit={saveEntry} submitLabel={editing?'Save Changes':'Add Time'} loading={saving}>{error&&<Alert tone="danger">{error}</Alert>}{data.can_manage&&<Field label="Employee"><Select value={form.member_id} onChange={e=>setForm({...form,member_id:e.target.value})}>{data.rows.map(row=><Option key={row.member_id} value={row.member_id}>{row.name}</Option>)}</Select></Field>}<Field label="Project"><Select value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value,task_id:''})}><Option value="">No project</Option>{data.projects.map(project=><Option key={project.id} value={project.id}>{project.name}</Option>)}</Select></Field><Field label="Task"><Select value={form.task_id} onChange={e=>setForm({...form,task_id:e.target.value})}><Option value="">No task</Option>{filteredTasks.map(task=><Option key={task.id} value={task.id}>{task.title}</Option>)}</Select></Field><Field label="Date"><Input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} required/></Field><Grid columns="1fr 1fr" gap={10}><Field label="Start"><Input type="time" value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})} required/></Field><Field label="End"><Input type="time" value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})} required/></Field></Grid><Field label="Note"><Textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></Field><BooleanField label="Billable" description="Include this entry in client billable time." checked={form.billable} onChange={billable=>setForm({...form,billable})}/></FormDialog>
 </Page>
}
