const ext = globalThis.browser ?? globalThis.chrome
/** Handles the $ operation for the WorkIntel application. */ const $ = id => document.getElementById(id)
/** Handles the message operation for the WorkIntel application. */ async function message(type, payload) { return await ext.runtime.sendMessage({ type, payload }) }
/** Formats format date data for output. */ function formatDate(value) { return value ? new Date(value).toLocaleString() : 'Never' }
/** Normalize the server origin supplied by the server-bound deployment package. */ function normalizeServerUrl(value) {
  let url
  try { url = new URL(String(value || '').trim()) } catch { throw new Error('This browser package is not configured with a valid WorkIntel server.') }
  if (!['http:', 'https:'].includes(url.protocol)) throw new Error('Configured WorkIntel server must use http:// or https://')
  if (url.username || url.password) throw new Error('Configured WorkIntel server must not contain credentials.')
  if ((url.pathname.replace(/\/+$/, '') || '/') !== '/' || url.search || url.hash) throw new Error('Configured WorkIntel server must be an origin without an API path.')
  return url.origin
}
let configuredServerUrl = ''
/** Load the runtime server binding injected when the extension is downloaded from WorkIntel. */ async function loadConfiguredServerUrl() {
  if (configuredServerUrl) return configuredServerUrl
  let response
  try { response = await fetch(ext.runtime.getURL('workintel-server.txt'), { cache: 'no-store' }) } catch { response = null }
  if (!response?.ok) throw new Error('This extension is not server-bound. Download it from WorkIntel Downloads, then load that extracted package.')
  configuredServerUrl = normalizeServerUrl(await response.text())
  return configuredServerUrl
}
/** Handles the origin pattern operation for the WorkIntel application. */ function originPattern(value) {
  const url = new URL(normalizeServerUrl(value))
  return `${url.origin}/*`
}
/** Handles the ensure server permission operation for the WorkIntel application. */ async function ensureServerPermission(serverUrl) {
  const pattern = originPattern(serverUrl)
  const has = await ext.permissions.contains({ origins: [pattern] })
  if (has) return true
  return await ext.permissions.request({ origins: [pattern] })
}
/** Renders output for the current application state. */ async function render() {
  const result = await message('status')
  const connected = Boolean(result?.config?.access_token)
  $('connect-view').hidden = connected; $('status-view').hidden = !connected
  if (connected) {
    $('connection').textContent = result.config.connection_uuid || ''
    $('server-status').textContent = result.config.server_url || ''
    $('queue').textContent = String(result.queue_size || 0)
    $('last-sync').textContent = formatDate(result.config.last_sync_at)
    $('message').textContent = result.config.last_error || ''
    return
  }
  try {
    const serverUrl = await loadConfiguredServerUrl()
    $('configured-server').textContent = serverUrl
    $('message').textContent = ''
  } catch (error) {
    $('configured-server').textContent = 'Not configured'
    $('message').textContent = error instanceof Error ? error.message : String(error)
  }
}
$('connect').addEventListener('click', async () => {
  try {
    const serverUrl = await loadConfiguredServerUrl()
    $('message').textContent = 'Requesting server access…'
    const granted = await ensureServerPermission(serverUrl)
    if (!granted) throw new Error('Permission to connect to the configured WorkIntel server was not granted.')
    $('message').textContent = 'Connecting…'
    const enrollmentCode = $('code').value.trim()
    if (!/^(WI|WB)-/i.test(enrollmentCode)) { $('message').textContent = 'Use the enrollment code generated by WorkIntel Downloads or Devices & Agents.'; return }
    const result = await message('enroll', { server_url: serverUrl, enrollment_code: enrollmentCode })
    if (result?.error) throw new Error(result.error)
    $('message').textContent = 'Connected.'
    await render()
  } catch (error) { $('message').textContent = error instanceof Error ? error.message : String(error) }
})
$('sync').addEventListener('click', async () => { $('message').textContent = 'Syncing…'; const result = await message('sync_now'); $('message').textContent = result?.error || 'Synced.'; await render() })
$('disconnect').addEventListener('click', async () => { await message('disconnect'); $('message').textContent = 'Disconnected locally. Revoke the connection in Workforce Intelligence if needed.'; await render() })
void render()
