const ext = globalThis.browser ?? globalThis.chrome
/** Handles the $ operation for the WorkIntel application. */ const $ = id => document.getElementById(id)
/** Handles the message operation for the WorkIntel application. */ async function message(type, payload) { return await ext.runtime.sendMessage({ type, payload }) }
/** Formats format date data for output. */ function formatDate(value) { return value ? new Date(value).toLocaleString() : 'Never' }
/** Normalize a server/base URL and safely accept the enrollment endpoints shown by WorkIntel. */ function normalizeServerUrl(value) {
  let url
  try { url = new URL(String(value || '').trim()) } catch { throw new Error('Enter a valid Workforce server URL, for example https://team.example.com') }
  if (!['http:', 'https:'].includes(url.protocol)) throw new Error('Server URL must use http:// or https://')
  if (url.username || url.password) throw new Error('Server URL must not contain credentials.')
  const path = url.pathname.replace(/\/+$/, '') || '/'
  const enrollmentPaths = new Set(['/api/v1/agent/enroll', '/api/v1/browser/enroll'])
  if (path !== '/' && !enrollmentPaths.has(path)) throw new Error('Use the Workforce server base URL, not an API path.')
  url.pathname = '/'
  url.search = ''
  url.hash = ''
  return url.origin
}
/** Handles the origin pattern operation for the WorkIntel application. */ function originPattern(value) {
  const url = new URL(normalizeServerUrl(value))
  return `${url.origin}/*`
}
/** Handles the ensure server permission operation for the WorkIntel application. */ async function ensureServerPermission(serverUrl) {
  const pattern = originPattern(serverUrl)
  const has = await ext.permissions.contains({ origins: [pattern] })
  if (has) return true
  return await ext.permissions.request({ origins: [pattern] })
}
/** Renders output for the current application state. */ async function render() {
  const result = await message('status')
  const connected = Boolean(result?.config?.access_token)
  $('connect-view').hidden = connected; $('status-view').hidden = !connected
  if (connected) {
    $('connection').textContent = result.config.connection_uuid || ''
    $('server-status').textContent = result.config.server_url || ''
    $('queue').textContent = String(result.queue_size || 0)
    $('last-sync').textContent = formatDate(result.config.last_sync_at)
    $('message').textContent = result.config.last_error || ''
  }
}
$('connect').addEventListener('click', async () => {
  try {
    $('message').textContent = 'Requesting server access…'
    const serverUrl = normalizeServerUrl($('server').value)
    $('server').value = serverUrl
    const granted = await ensureServerPermission(serverUrl)
    if (!granted) throw new Error('Permission to connect to this server was not granted.')
    $('message').textContent = 'Connecting…'
    const enrollmentCode = $('code').value.trim()
    if (!/^(WI|WB)-/i.test(enrollmentCode)) { $('message').textContent = 'Use a WI desktop-agent code or WB browser code generated by Workforce Intelligence.'; return }
    const result = await message('enroll', { server_url: serverUrl, enrollment_code: enrollmentCode })
    if (result?.error) throw new Error(result.error)
    $('message').textContent = 'Connected.'
    await render()
  } catch (error) { $('message').textContent = error instanceof Error ? error.message : String(error) }
})
$('sync').addEventListener('click', async () => { $('message').textContent = 'Syncing…'; const result = await message('sync_now'); $('message').textContent = result?.error || 'Synced.'; await render() })
$('disconnect').addEventListener('click', async () => { await message('disconnect'); $('message').textContent = 'Disconnected locally. Revoke the connection in Workforce Intelligence if needed.'; await render() })
void render()
