<?php
namespace App\Services\Platform;

use App\Models\DataImportItem;use App\Models\DataImportJob;use App\Models\Department;use App\Models\Project;use App\Models\Role;use App\Models\Task;use App\Models\User;use App\Models\Workspace;use App\Models\WorkspaceMember;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;
/** Provides data import service behavior within the WorkIntel application. */ class DataImportService
{
    public const ENTITIES=['people','projects','tasks'];
    /** Creates create job data for the requested workflow. */ public function createJob(Workspace $workspace,User $actor,UploadedFile $file,string $entityType,string $sourceSystem,array $mapping,array $options=[]):DataImportJob
    {
        if(!in_array($entityType,self::ENTITIES,true))throw ValidationException::withMessages(['entity_type'=>['Supported imports: people, projects, tasks.']]);
        if(strtolower($file->getClientOriginalExtension())!=='csv')throw ValidationException::withMessages(['file'=>['Upload a CSV file.']]);
        if($file->getSize()>10*1024*1024)throw ValidationException::withMessages(['file'=>['CSV cannot exceed 10 MB.']]);
        $uuid=(string)Str::uuid();$name=$uuid.'.csv';$path=$file->storeAs('platform/imports/'.$workspace->id,$name,'local');$sha=hash_file('sha256',Storage::disk('local')->path($path));
        $job=DataImportJob::create(['uuid'=>$uuid,'workspace_id'=>$workspace->id,'created_by'=>$actor->id,'source_system'=>$sourceSystem,'entity_type'=>$entityType,'status'=>'uploaded','file_path'=>$path,'original_name'=>$file->getClientOriginalName(),'file_sha256'=>$sha,'column_mapping'=>$mapping,'options'=>$options]);
        $this->stageRows($job);return $job->fresh('items');
    }
    /** Handles the preview operation for the current WorkIntel workflow. */ public function preview(DataImportJob $job,int $limit=10):array{return $job->items()->orderBy('row_number')->limit(max(1,min(50,$limit)))->get()->map(fn($i)=>['row'=>$i->row_number,'source'=>$i->source_data,'normalized'=>$i->normalized_data,'status'=>$i->status,'error'=>$i->error])->all();}
    /** Handles the run operation for the current WorkIntel workflow. */ public function run(DataImportJob $job):DataImportJob
    {
        if(!in_array($job->status,['uploaded','ready','failed','completed_with_errors'],true))abort(422,'This import cannot be run in its current state.');$job->update(['status'=>'running','started_at'=>now(),'last_error'=>null]);$counts=['imported'=>0,'skipped'=>0,'failed'=>0];
        foreach($job->items()->whereIn('status',['pending','failed'])->orderBy('row_number')->cursor() as $item){try{$target=DB::transaction(fn()=>match($job->entity_type){'people'=>$this->importPerson($job,$item),'projects'=>$this->importProject($job,$item),'tasks'=>$this->importTask($job,$item)});$item->update(['status'=>'imported','target_type'=>$target::class,'target_id'=>$target->id,'error'=>null]);$counts['imported']++;}catch(\Throwable $e){$item->update(['status'=>'failed','error'=>mb_substr($e->getMessage(),0,2000)]);$counts['failed']++;}}
        $status=$counts['failed']?'completed_with_errors':'completed';$job->update(['status'=>$status,'summary'=>$counts,'completed_at'=>now()]);return $job->fresh();
    }
    /** Handles the stage rows operation for the current WorkIntel workflow. */ private function stageRows(DataImportJob $job):void
    {
        $path=Storage::disk('local')->path($job->file_path);$fh=fopen($path,'rb');if(!$fh)throw new \RuntimeException('Import file could not be read.');$headers=fgetcsv($fh, null, ",", "\"", "");if(!$headers){fclose($fh);throw ValidationException::withMessages(['file'=>['CSV has no header row.']]);}$headers=array_map(fn($h)=>trim((string)$h),$headers);$row=1;$count=0;
        while(($values=fgetcsv($fh, null, ",", "\"", ""))!==false){$row++;if($count>=5000){fclose($fh);throw ValidationException::withMessages(['file'=>['Maximum 5,000 rows per import job.']]);}$values=array_pad($values,count($headers),null);$source=array_combine($headers,array_slice($values,0,count($headers)))?:[];$normalized=$this->normalize($job->entity_type,$source,$job->column_mapping??[]);$external=(string)($normalized['external_id']??'');DataImportItem::create(['data_import_job_id'=>$job->id,'row_number'=>$row,'external_key'=>$external?:null,'fingerprint'=>hash('sha256',json_encode($source,JSON_UNESCAPED_UNICODE)),'status'=>'pending','source_data'=>$source,'normalized_data'=>$normalized]);$count++;}fclose($fh);$job->update(['status'=>'ready','summary'=>['rows'=>$count]]);
    }
    /** Handles the normalize operation for the current WorkIntel workflow. */ private function normalize(string $entity,array $source,array $mapping):array{$out=[];foreach($mapping as $canonical=>$header){if($header!==null&&$header!==''&&array_key_exists($header,$source))$out[$canonical]=is_string($source[$header])?trim($source[$header]):$source[$header];}return $out;}
    /** Handles the import person operation for the current WorkIntel workflow. */ private function importPerson(DataImportJob $job,DataImportItem $item):WorkspaceMember
    {
        $d=$item->normalized_data??[];foreach(['email','first_name','last_name'] as $key)if(empty($d[$key]))throw new \RuntimeException("Missing {$key}.");if(!filter_var($d['email'],FILTER_VALIDATE_EMAIL))throw new \RuntimeException('Invalid email.');$user=User::firstOrCreate(['email'=>strtolower($d['email'])],['first_name'=>$d['first_name'],'last_name'=>$d['last_name'],'password'=>Str::random(40),'timezone'=>$d['timezone']??'UTC','status'=>'active']);$dept=null;if(!empty($d['department']))$dept=Department::firstOrCreate(['workspace_id'=>$job->workspace_id,'name'=>$d['department']],['code'=>Str::upper(substr(Str::slug($d['department'],''),0,12))?:'DEPT']);$member=WorkspaceMember::updateOrCreate(['workspace_id'=>$job->workspace_id,'user_id'=>$user->id],['employee_code'=>$d['employee_code']??null,'job_title'=>$d['job_title']??'Employee','department_id'=>$dept?->id,'employment_type'=>$d['employment_type']??'full_time','joining_date'=>$d['joining_date']??today()->toDateString(),'status'=>'active','timezone'=>$d['timezone']??$user->timezone]);if(!$member->roles()->exists()){$role=Role::where('workspace_id',$job->workspace_id)->where('status','active')->where('slug','employee')->first();if($role)$member->roles()->attach($role->id);}return $member;
    }
    /** Handles the import project operation for the current WorkIntel workflow. */ private function importProject(DataImportJob $job,DataImportItem $item):Project{$d=$item->normalized_data??[];if(empty($d['name']))throw new \RuntimeException('Missing project name.');$lookup=!empty($d['code'])?['workspace_id'=>$job->workspace_id,'code'=>$d['code']]:['workspace_id'=>$job->workspace_id,'name'=>$d['name']];return Project::updateOrCreate($lookup,['name'=>$d['name'],'code'=>$d['code']??null,'description'=>$d['description']??null,'status'=>$d['status']??'active','priority'=>$d['priority']??'medium','currency'=>$d['currency']??Workspace::find($job->workspace_id)?->currency??'USD','billable'=>filter_var($d['billable']??true,FILTER_VALIDATE_BOOLEAN),'created_by'=>$job->created_by]);}
    /** Handles the import task operation for the current WorkIntel workflow. */ private function importTask(DataImportJob $job,DataImportItem $item):Task
    {
        $d=$item->normalized_data??[];if(empty($d['title']))throw new \RuntimeException('Missing task title.');$project=null;if(!empty($d['project_code']))$project=Project::where('workspace_id',$job->workspace_id)->where('code',$d['project_code'])->first();if(!$project&&!empty($d['project_name']))$project=Project::where('workspace_id',$job->workspace_id)->where('name',$d['project_name'])->first();if(!$project)throw new \RuntimeException('Task project was not found.');
        $workspace=Workspace::findOrFail($job->workspace_id);$workflow=app(\App\Services\Tasks\TaskWorkflowService::class);$workflow->ensureDefaults($workspace);$status=$workflow->resolveStatus($job->workspace_id,null,(string)($d['status']??'todo'));
        $existing=$this->priorTarget($job,$item,Task::class);
        if($existing){$existing->update(['project_id'=>$project->id,'title'=>$d['title'],'description'=>$d['description']??null,'priority'=>$d['priority']??'medium','estimated_minutes'=>(int)($d['estimated_minutes']??0)]);$workflow->applyStatus($existing,$status,null,false,'import');return $existing;}
        $task=Task::create(['workspace_id'=>$job->workspace_id,'project_id'=>$project->id,'task_status_id'=>$status->id,'title'=>$d['title'],'description'=>$d['description']??null,'status'=>$status->slug,'priority'=>$d['priority']??'medium','estimated_minutes'=>(int)($d['estimated_minutes']??0),'position'=>$workflow->nextPosition($job->workspace_id,$status->id),'billable'=>filter_var($d['billable']??true,FILTER_VALIDATE_BOOLEAN),'created_by'=>$job->created_by,'completed_at'=>$status->is_completed?now():null]);app(\App\Services\Tasks\TaskActivityService::class)->log($task,null,'created',['source'=>'import']);return $task;
    }
    /** Handles the prior target operation for the current WorkIntel workflow. */ private function priorTarget(DataImportJob $job,DataImportItem $item,string $class):?object{if(!$item->external_key)return null;$prior=DataImportItem::query()->where('external_key',$item->external_key)->where('target_type',$class)->where('status','imported')->whereHas('job',fn($q)=>$q->where('workspace_id',$job->workspace_id)->where('source_system',$job->source_system))->latest('id')->first();return $prior? $class::find($prior->target_id):null;}
}
