import { useState, type FormEvent } from 'react'
import { ArrowLeft, Eye, EyeOff, LogOut, ShoppingCart } from 'lucide-react'
import SellerConsole from '../pages/SellerConsole'
import { useAuth } from '../auth/AuthContext'
import { Alert, Button, ErrorState, Field, IconButton, Input, Checkbox, Inline, Form, Label, Link, PageHeader } from '../design-system'
import { AppBootLoader } from '../components/LoadingStates'
import { useLocalization } from '../i18n/LocalizationContext'

/** Render the dedicated global seller/operator surface independently from tenant navigation. */
export default function SellerPlatformApp(){
  const {session,isAuthenticated,isReady,login,logout}=useAuth();const {t}=useLocalization()
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[remember,setRemember]=useState(true),[mfaCode,setMfaCode]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  /** Authenticate into the seller surface with the normal account security pipeline. */
  const submit=async(event:FormEvent)=>{event.preventDefault();setError('');setBusy(true);try{await login({email,password,remember,mfaCode})}catch(reason){setError(reason instanceof Error?reason.message:'Unable to sign in.')}finally{setBusy(false)}}
  if(!isReady)return <AppBootLoader label="Loading Seller Platform"/>
  if(!isAuthenticated||!session)return <div className="seller-auth"><div className="seller-auth__card"><div className="seller-auth__brand"><span><ShoppingCart size={18}/></span><div><strong>WorkIntel Seller Platform</strong><small>Platform operator access</small></div></div><PageHeader title="Seller sign in" description="Manage plans, customers, subscriptions, platform payment providers and revenue without entering a tenant workspace."/>{error&&<Alert tone="danger">{error}</Alert>}<Form onSubmit={submit} className="seller-auth__form"><Field label="Operator email"><Input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></Field><Field label="Password"><div className="auth-password"><Input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><IconButton type="button" variant="ghost" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={15}/>:<Eye size={15}/>}</IconButton></div></Field><Field label="MFA / recovery code"><Input value={mfaCode} onChange={e=>setMfaCode(e.target.value)} inputMode="numeric" autoComplete="one-time-code"/></Field><Label className="auth-check"><Checkbox checked={remember} onChange={e=>setRemember(e.target.checked)}/><span>Keep me signed in</span></Label><Button size="lg" type="submit" loading={busy}>Sign in to Seller Platform</Button></Form><Button variant="ghost" onClick={()=>location.href='/app'}><ArrowLeft size={14}/> Back to workspace login</Button></div></div>
  if(!session.user.platformOperator)return <div className="seller-auth"><div className="seller-auth__card"><ErrorState title="Platform operator access required" text="This signed-in account belongs to a workspace but is not authorized to administer the WorkIntel seller platform."/><Inline gap={8} wrap="wrap"><Button onClick={()=>location.href='/app'}><ArrowLeft size={14}/> Return to workspace</Button><Button variant="outline" onClick={()=>logout()}><LogOut size={14}/> Sign out</Button></Inline></div></div>
  return <div className="seller-shell"><Link className="ui-skip-link" href="#seller-main">{t('common.skip_to_content')}</Link><header className="seller-shell__header"><div><span><ShoppingCart size={16}/></span><div><strong>WorkIntel Seller Platform</strong><small>Global commerce administration</small></div></div><div><span>{session.user.email}</span><Button size="sm" variant="outline" onClick={()=>location.href='/app'}><ArrowLeft size={13}/> Workspace</Button><Button size="sm" variant="ghost" onClick={()=>logout()}><LogOut size={13}/> Sign out</Button></div></header><main id="seller-main" tabIndex={-1} className="seller-shell__main"><SellerConsole/></main></div>
}
