import { ArrowRight, BookOpen, Check, Circle, Compass, RotateCcw, ShieldCheck } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import type { AuthWorkspace } from '../auth/types'
import { canAccessPage, isPageVisibleInNavigation, roleLabel } from '../access'
import type { Page } from './Sidebar'
import { pageTranslationKey } from '../navigation'
import { contextualHelpForPage } from '../help/roleHelpCatalog'
import { useRoleExperience } from '../help/roleExperience'
import { pageShell, workspaceModule, workspaceModuleForPage, type WorkspaceModuleId } from '../moduleCatalog'
import { Alert, Badge, Button, Drawer, EmptyState, Inline, Progress, SearchInput, Stack, Tabs, Text } from '../design-system'
import { useLocalization } from '../i18n/LocalizationContext'

type HelpTab='context'|'start'|'handbook'

/** Render a global role-aware Help Center grounded in the current page/module and effective authorization. */
export default function HelpCenter({open,onClose,workspace,page,activeModule,onNavigate,onOpenModule}:{open:boolean;onClose:()=>void;workspace:AuthWorkspace;page:Page;activeModule?:WorkspaceModuleId|null;onNavigate:(page:Page)=>void;onOpenModule:(id:WorkspaceModuleId)=>void}){
 const {t,text}=useLocalization(),experience=useRoleExperience(workspace),[tab,setTab]=useState<HelpTab>('context'),[query,setQuery]=useState('')
 const help=contextualHelpForPage(page,workspace),module=activeModule?workspaceModule(activeModule):workspaceModuleForPage(page),guide=experience.guide
 const accessible=useMemo(()=>Object.keys(pageShell).map(value=>value as Page).filter(candidate=>canAccessPage(workspace,candidate)&&isPageVisibleInNavigation(workspace,candidate)),[workspace.id,workspace.role,workspace.permissions.join('|'),JSON.stringify(workspace.modules??{})])
 const searchRows=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return[];return accessible.filter(candidate=>{const meta=pageShell[candidate],hay=[candidate,t(pageTranslationKey[candidate]),meta.description,...meta.aliases].join(' ').toLowerCase();return hay.includes(q)}).slice(0,10)},[query,accessible,t])
 const tasks=guide?.tasks??[],done=tasks.filter(task=>experience.state.completed.includes(task.id)).length,percent=tasks.length?Math.round(done/tasks.length*100):0
 const modulePages=module?.pages.filter(candidate=>canAccessPage(workspace,candidate)&&isPageVisibleInNavigation(workspace,candidate))??[]
 const contextSteps=activeModule&&module?[t('help.module_step_one',{count:modulePages.length}),t('help.module_step_two',{page:modulePages[0]?t(pageTranslationKey[modulePages[0]]):text(module.label)}),t('help.module_step_three')]:help.firstSteps.map(text)
 const contextRelated=activeModule?modulePages.slice(0,6):help.relatedPages
 useEffect(()=>{if(open&&!experience.state.seen)void experience.markSeen()},[open,experience.state.seen])
 useEffect(()=>{/** Honor shell-level help requests that specify a safe Help Center tab. */ const handler=(event:Event)=>{const requested=(event as CustomEvent<{tab?:HelpTab}>).detail?.tab;if(requested&&['context','start','handbook'].includes(requested))setTab(requested)};window.addEventListener('workintel:open-help',handler);return()=>window.removeEventListener('workintel:open-help',handler)},[])
 /** Navigate from help without granting access or leaving a stale drawer over the destination. */
 const go=(destination:Page)=>{onNavigate(destination);onClose()}
 return <Drawer open={open} onClose={onClose} title={t('help.center')} description={`${text(roleLabel(workspace.role))} · ${t('help.access_guidance')}`} footer={<Inline justify="space-between" align="center"><Text size={10.5} color="var(--text-3)">{t('help.shortcut')}</Text><Button variant="ghost" size="sm" onClick={()=>void experience.reset()}><RotateCcw size={12}/> {t('help.reset_guide')}</Button></Inline>}><Stack gap={12}>
  <SearchInput value={query} onChange={event=>setQuery(event.target.value)} placeholder={t('help.search_placeholder')} aria-label={t('help.search_aria')}/>
  {query&&<div className="ui-help-search-results">{searchRows.map(candidate=>{const Icon=pageShell[candidate].icon;return <Button key={candidate} variant="ghost" className="ui-help-search-result" onClick={()=>go(candidate)}><Icon size={14}/><span><strong>{t(pageTranslationKey[candidate])}</strong><small>{text(pageShell[candidate].description)}</small></span><ArrowRight className="ui-help-directional-icon" size={12}/></Button>})}{!searchRows.length&&<EmptyState title={t('help.no_result')} text={t('help.no_result_text')}/>}</div>}
  <Tabs value={tab} onChange={setTab} ariaLabel={t('help.sections_aria')} tabs={[{value:'context',label:t('help.this_page')},{value:'start',label:t('help.start_here')},{value:'handbook',label:t('help.role_handbook')}]}/>
  {tab==='context'&&<Stack gap={12}><div className="ui-help-context-hero"><Inline gap={8} align="center"><Compass size={16}/><div><strong>{activeModule&&module?text(module.label):t(pageTranslationKey[page])}</strong><small>{activeModule&&module?text(module.description):text(help.summary)}</small></div></Inline></div><div><Text as="strong" size={12.5}>{t('help.first_steps')}</Text><ol className="ui-help-steps">{contextSteps.map((step,index)=><li key={step}><span>{index+1}</span><Text size={11.5}>{step}</Text></li>)}</ol></div><div><Text as="strong" size={12.5}>{t('help.watch_for')}</Text><Stack gap={6} mt={7}>{help.watchFor.map(note=><Alert key={note} tone="info"><ShieldCheck size={13}/> {text(note)}</Alert>)}</Stack></div>{contextRelated.length>0&&<div><Text as="strong" size={12.5}>{t('help.related_destinations')}</Text><Inline gap={6} wrap="wrap" mt={7}>{contextRelated.map(candidate=><Button key={candidate} size="sm" variant="outline" onClick={()=>go(candidate)}>{t(pageTranslationKey[candidate])}</Button>)}</Inline></div>}{module&&!activeModule&&<Button variant="ghost" size="sm" onClick={()=>{onOpenModule(module.id);onClose()}}>{t('help.open_module_home',{module:text(module.label)})} <ArrowRight className="ui-help-directional-icon" size={12}/></Button>}</Stack>}
  {tab==='start'&&guide&&<Stack gap={10}>{experience.error&&<Alert tone="warning">{experience.error}</Alert>}<div><Inline justify="space-between" gap={8}><div><Text as="strong">{text(guide.title)}</Text><Text as="p" size={11.5} color="var(--text-2)" mt={3}>{text(guide.summary)}</Text></div><Badge tone={percent===100?'success':'accent'}>{done}/{tasks.length}</Badge></Inline><Progress value={percent} tone={percent===100?'success':'accent'} label={t('help.progress',{percent})} /></div><div className="ui-help-checklist">{tasks.map(task=>{const complete=experience.state.completed.includes(task.id);return <div key={task.id} className={`ui-help-checklist__row${complete?' is-complete':''}`}><Button iconOnly size="sm" variant="ghost" aria-pressed={complete} aria-label={complete?t('help.mark_incomplete',{item:text(task.title)}):t('help.mark_complete',{item:text(task.title)})} onClick={()=>void experience.toggleTask(task.id)}>{complete?<Check size={14}/>:<Circle size={14}/>}</Button><div><strong>{text(task.title)}</strong><small>{text(task.description)}</small><Text size={10} color="var(--text-3)">{text(task.why)}</Text></div><Button size="sm" variant="ghost" onClick={()=>go(task.page)}>{t('help.open')}</Button></div>})}</div></Stack>}
  {tab==='handbook'&&guide&&<Stack gap={12}><div className="ui-help-context-hero"><Inline gap={8} align="center"><BookOpen size={16}/><div><strong>{text(guide.label)} {t('help.role_handbook').toLowerCase()}</strong><small>{text(guide.title)}</small></div></Inline></div><div><Text as="strong" size={12.5}>{t('help.what_good_looks_like')}</Text><Stack gap={7} mt={7}>{guide.outcomes.map(outcome=><Inline key={outcome} gap={7} align="flex-start"><Check size={13}/><Text size={11.5}>{text(outcome)}</Text></Inline>)}</Stack></div><div><Text as="strong" size={12.5}>{t('help.accessible_work_areas')}</Text><div className="ui-help-area-list">{Array.from(new Set(accessible.map(candidate=>workspaceModuleForPage(candidate)?.id).filter(Boolean) as WorkspaceModuleId[])).map(id=>{const item=workspaceModule(id);if(!item)return null;const AreaIcon=item.icon;return <Button key={id} variant="outline" className="ui-help-area" onClick={()=>{onOpenModule(id);onClose()}}><AreaIcon size={14}/><span><strong>{text(item.label)}</strong><small>{text(item.description)}</small></span><ArrowRight className="ui-help-directional-icon" size={12}/></Button>})}</div></div><Alert tone="info">{t('help.authority_note')}</Alert></Stack>}
 </Stack></Drawer>
}
