<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /** Handles the up operation for the current WorkIntel workflow. */ public function up(): void
    {
        foreach ([
            ['Field Workforce','field.view_own'],['Field Workforce','field.view_team'],['Field Workforce','field.manage'],
            ['Field Workforce','field.forms.manage'],['Field Workforce','field.incidents.manage'],
        ] as [$group,$slug]) if(Schema::hasTable('permissions')) DB::table('permissions')->updateOrInsert(['slug'=>$slug],['name'=>ucwords(str_replace(['.','_'],' ',$slug)),'group'=>$group]);
        if(Schema::hasTable('roles')&&Schema::hasTable('permissions')&&Schema::hasTable('role_permissions')){
            $ids=DB::table('permissions')->pluck('id','slug');$ts=Schema::hasColumn('role_permissions','created_at')&&Schema::hasColumn('role_permissions','updated_at');
            $grant=function(string $roleSlug,array $slugs)use($ids,$ts):void{foreach(DB::table('roles')->where('is_system',true)->where('slug',$roleSlug)->get(['id']) as $role)foreach($slugs as $slug){$pid=$ids[$slug]??null;if(!$pid)continue;$row=['role_id'=>$role->id,'permission_id'=>$pid];if($ts)$row+=['created_at'=>now(),'updated_at'=>now()];DB::table('role_permissions')->insertOrIgnore($row);}};
            foreach(['owner','admin'] as $r)$grant($r,['field.view_own','field.view_team','field.manage','field.forms.manage','field.incidents.manage']);
            $grant('manager',['field.view_own','field.view_team','field.manage','field.incidents.manage']);$grant('team-lead',['field.view_own','field.view_team','field.incidents.manage']);$grant('hr',['field.view_own','field.view_team','field.incidents.manage']);$grant('employee',['field.view_own']);
        }

        if(!Schema::hasTable('mobile_access_tokens'))Schema::create('mobile_access_tokens',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->char('token_hash',64)->unique();$t->string('token_prefix',18);$t->uuid('device_uuid');$t->string('platform',24);$t->string('device_name',120)->nullable();$t->string('app_version',40)->nullable();$t->text('push_token_encrypted')->nullable();$t->timestamp('last_used_at')->nullable();$t->ipAddress('last_used_ip')->nullable();$t->timestamp('expires_at')->nullable();$t->timestamp('revoked_at')->nullable();$t->timestamp('created_at')->useCurrent();$t->unique(['workspace_id','member_id','device_uuid'],'mat_ws_member_device_uq');$t->index(['workspace_id','revoked_at'],'mat_ws_revoked_idx');});
        if(!Schema::hasTable('field_work_orders'))Schema::create('field_work_orders',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('project_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('client_id')->nullable()->constrained()->nullOnDelete();$t->string('work_order_number',50);$t->string('title',180);$t->text('description')->nullable();$t->string('status',24)->default('assigned');$t->string('priority',20)->default('normal');$t->timestamp('scheduled_start_at')->nullable();$t->timestamp('scheduled_end_at')->nullable();$t->timestamp('due_at')->nullable();$t->string('site_name',180)->nullable();$t->string('site_address',500)->nullable();$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->unsignedInteger('geofence_radius_meters')->nullable();$t->text('instructions')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['workspace_id','work_order_number'],'fwo_ws_number_uq');$t->index(['workspace_id','status','due_at'],'fwo_ws_status_due_idx');});
        if(!Schema::hasTable('field_work_order_assignees'))Schema::create('field_work_order_assignees',function(Blueprint $t){$t->id();$t->foreignId('field_work_order_id')->constrained('field_work_orders')->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->string('role',30)->default('assignee');$t->timestamp('accepted_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();$t->unique(['field_work_order_id','member_id'],'fwoa_order_member_uq');$t->index(['member_id','completed_at'],'fwoa_member_completed_idx');});
        if(!Schema::hasTable('field_work_order_events'))Schema::create('field_work_order_events',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('field_work_order_id')->constrained('field_work_orders')->cascadeOnDelete();$t->foreignId('member_id')->nullable()->constrained('workspace_members')->nullOnDelete();$t->string('event_type',50);$t->text('note')->nullable();$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->decimal('accuracy_meters',8,2)->nullable();$t->json('metadata')->nullable();$t->timestamp('occurred_at');$t->timestamp('created_at')->useCurrent();$t->index(['field_work_order_id','occurred_at'],'fwoe_order_occurred_idx');});
        if(!Schema::hasTable('field_files'))Schema::create('field_files',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('field_work_order_id')->nullable()->constrained('field_work_orders')->cascadeOnDelete();$t->foreignId('incident_id')->nullable();$t->foreignId('member_id')->nullable()->constrained('workspace_members')->nullOnDelete();$t->string('kind',30)->default('photo');$t->string('file_path',500);$t->string('file_name',255);$t->string('mime_type',120);$t->unsignedBigInteger('size_bytes');$t->char('sha256',64);$t->text('caption')->nullable();$t->timestamp('captured_at')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['workspace_id','field_work_order_id'],'ff_ws_order_idx');});
        if(!Schema::hasTable('field_checkpoints'))Schema::create('field_checkpoints',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('project_id')->nullable()->constrained()->nullOnDelete();$t->string('name',160);$t->string('type',20)->default('qr');$t->char('scan_token_hash',64)->unique();$t->string('token_prefix',16);$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->unsignedInteger('radius_meters')->nullable();$t->string('status',20)->default('active');$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['workspace_id','status'],'fc_ws_status_idx');});
        if(!Schema::hasTable('field_checkpoint_visits'))Schema::create('field_checkpoint_visits',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('field_checkpoint_id')->constrained('field_checkpoints')->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->foreignId('field_work_order_id')->nullable()->constrained('field_work_orders')->nullOnDelete();$t->string('scan_method',20)->default('qr');$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->decimal('accuracy_meters',8,2)->nullable();$t->boolean('within_geofence')->nullable();$t->timestamp('visited_at');$t->timestamp('created_at')->useCurrent();$t->index(['workspace_id','member_id','visited_at'],'fcv_ws_member_visit_idx');});
        if(!Schema::hasTable('field_form_templates'))Schema::create('field_form_templates',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name',160);$t->string('category',50)->default('checklist');$t->string('status',20)->default('active');$t->boolean('requires_work_order')->default(false);$t->boolean('requires_location')->default(false);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['workspace_id','status','category'],'fft_ws_status_cat_idx');});
        if(!Schema::hasTable('field_form_fields'))Schema::create('field_form_fields',function(Blueprint $t){$t->id();$t->foreignId('field_form_template_id')->constrained('field_form_templates')->cascadeOnDelete();$t->string('key',80);$t->string('label',180);$t->string('type',30);$t->boolean('required')->default(false);$t->json('options')->nullable();$t->json('validation')->nullable();$t->unsignedSmallInteger('position')->default(1);$t->timestamps();$t->unique(['field_form_template_id','key'],'fff_template_key_uq');});
        if(!Schema::hasTable('field_form_submissions'))Schema::create('field_form_submissions',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('field_form_template_id')->constrained('field_form_templates')->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->foreignId('field_work_order_id')->nullable()->constrained('field_work_orders')->nullOnDelete();$t->string('status',20)->default('submitted');$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->timestamp('submitted_at');$t->timestamp('created_at')->useCurrent();$t->index(['workspace_id','member_id','submitted_at'],'ffs_ws_member_submit_idx');});
        if(!Schema::hasTable('field_form_answers'))Schema::create('field_form_answers',function(Blueprint $t){$t->id();$t->foreignId('field_form_submission_id')->constrained('field_form_submissions')->cascadeOnDelete();$t->foreignId('field_form_field_id')->constrained('field_form_fields')->cascadeOnDelete();$t->json('value')->nullable();$t->timestamps();$t->unique(['field_form_submission_id','field_form_field_id'],'ffa_submission_field_uq');});
        if(!Schema::hasTable('safety_incidents'))Schema::create('safety_incidents',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('reporter_member_id')->constrained('workspace_members')->cascadeOnDelete();$t->foreignId('field_work_order_id')->nullable()->constrained('field_work_orders')->nullOnDelete();$t->string('incident_number',50);$t->string('type',50);$t->string('severity',20);$t->string('status',24)->default('open');$t->string('title',180);$t->text('description');$t->timestamp('occurred_at');$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->text('immediate_action')->nullable();$t->text('resolution')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reviewed_at')->nullable();$t->timestamps();$t->unique(['workspace_id','incident_number'],'si_ws_number_uq');$t->index(['workspace_id','status','severity'],'si_ws_status_severity_idx');});
        if(!Schema::hasTable('mobile_sync_events'))Schema::create('mobile_sync_events',function(Blueprint $t){$t->id();$t->uuid('event_uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->string('event_type',60);$t->json('payload');$t->string('status',20)->default('processed');$t->text('error')->nullable();$t->timestamp('client_occurred_at')->nullable();$t->timestamp('processed_at')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['workspace_id','member_id','created_at'],'mse_ws_member_created_idx');});
    }
    /** Handles the down operation for the current WorkIntel workflow. */ public function down():void{foreach(['mobile_sync_events','field_form_answers','field_form_submissions','field_form_fields','field_form_templates','field_checkpoint_visits','field_checkpoints','field_files','field_work_order_events','field_work_order_assignees','safety_incidents','field_work_orders','mobile_access_tokens'] as $t)Schema::dropIfExists($t);}
};
