<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /** Handles the up operation for the current WorkIntel workflow. */ public function up(): void
    {
        foreach ([
            ['Finance Ops','expenses.view_own'],['Finance Ops','expenses.view_team'],['Finance Ops','expenses.manage'],['Finance Ops','expenses.policies.manage'],
            ['Finance Ops','procurement.view'],['Finance Ops','procurement.manage'],['Finance Ops','job_costing.view'],['Finance Ops','job_costing.manage'],['Finance Ops','cost_centers.manage'],
        ] as [$group,$slug]) if(Schema::hasTable('permissions')) DB::table('permissions')->updateOrInsert(['slug'=>$slug],['name'=>ucwords(str_replace(['.','_'],' ',$slug)),'group'=>$group]);
        if(Schema::hasTable('roles')&&Schema::hasTable('permissions')&&Schema::hasTable('role_permissions')){
            $ids=DB::table('permissions')->pluck('id','slug');$ts=Schema::hasColumn('role_permissions','created_at')&&Schema::hasColumn('role_permissions','updated_at');
            $grant=function(string $roleSlug,array $slugs)use($ids,$ts):void{foreach(DB::table('roles')->where('is_system',true)->where('slug',$roleSlug)->get(['id']) as $role){foreach($slugs as $slug){$pid=$ids[$slug]??null;if(!$pid)continue;$row=['role_id'=>$role->id,'permission_id'=>$pid];if($ts)$row+=['created_at'=>now(),'updated_at'=>now()];DB::table('role_permissions')->insertOrIgnore($row);}}};
            $all=['expenses.view_own','expenses.view_team','expenses.manage','expenses.policies.manage','procurement.view','procurement.request','procurement.manage','job_costing.view','job_costing.manage','cost_centers.manage'];
            foreach(['owner','admin'] as $r)$grant($r,$all);$grant('hr',['expenses.view_own','expenses.view_team']);$grant('manager',['expenses.view_own','expenses.view_team','procurement.view','procurement.request','procurement.manage','job_costing.view']);$grant('team-lead',['expenses.view_own','expenses.view_team','procurement.view','procurement.request']);$grant('payroll-manager',['expenses.view_own','expenses.manage','job_costing.view']);$grant('employee',['expenses.view_own','procurement.request']);
        }
        if(!Schema::hasTable('cost_centers'))Schema::create('cost_centers',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('parent_id')->nullable()->constrained('cost_centers')->nullOnDelete();$t->foreignId('manager_member_id')->nullable()->constrained('workspace_members')->nullOnDelete();$t->string('code',40);$t->string('name',140);$t->decimal('annual_budget',14,2)->nullable();$t->string('currency',3)->default('USD');$t->boolean('active')->default(true);$t->timestamps();$t->unique(['workspace_id','code'],'cc_ws_code_uq');$t->index(['workspace_id','active'],'cc_ws_active_idx');});
        if(!Schema::hasTable('expense_policies'))Schema::create('expense_policies',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name',160);$t->string('status',20)->default('active');$t->string('currency',3)->default('USD');$t->decimal('receipt_required_over',12,2)->default(0);$t->decimal('mileage_rate',8,3)->default(0);$t->decimal('daily_per_diem',10,2)->default(0);$t->decimal('max_claim_amount',14,2)->nullable();$t->json('allowed_categories')->nullable();$t->boolean('requires_approval')->default(true);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['workspace_id','status'],'ep_ws_status_idx');});
        if(!Schema::hasTable('expense_claims'))Schema::create('expense_claims',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->foreignId('project_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('cost_center_id')->nullable()->constrained('cost_centers')->nullOnDelete();$t->foreignId('expense_policy_id')->nullable()->constrained('expense_policies')->nullOnDelete();$t->string('claim_number',50);$t->string('title',180);$t->string('status',24)->default('draft');$t->string('currency',3);$t->decimal('total_amount',14,2)->default(0);$t->decimal('approved_amount',14,2)->default(0);$t->string('reimbursement_status',24)->default('not_ready');$t->timestamp('submitted_at')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reviewed_at')->nullable();$t->timestamp('reimbursed_at')->nullable();$t->foreignId('payroll_run_id')->nullable()->constrained('payroll_runs')->nullOnDelete();$t->text('note')->nullable();$t->timestamps();$t->unique(['workspace_id','claim_number'],'ec_ws_number_uq');$t->index(['workspace_id','member_id','status'],'ec_ws_member_status_idx');});
        if(!Schema::hasTable('expense_claim_items'))Schema::create('expense_claim_items',function(Blueprint $t){$t->id();$t->foreignId('expense_claim_id')->constrained('expense_claims')->cascadeOnDelete();$t->date('expense_date');$t->string('category',60);$t->string('description',255);$t->decimal('amount',14,2);$t->decimal('tax_amount',12,2)->default(0);$t->string('currency',3);$t->string('merchant',160)->nullable();$t->decimal('mileage_km',10,2)->nullable();$t->decimal('mileage_rate',8,3)->nullable();$t->foreignId('project_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('cost_center_id')->nullable()->constrained('cost_centers')->nullOnDelete();$t->string('receipt_path',500)->nullable();$t->string('receipt_file_name',255)->nullable();$t->string('receipt_mime_type',120)->nullable();$t->unsignedBigInteger('receipt_size_bytes')->default(0);$t->char('receipt_sha256',64)->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->index(['expense_claim_id','expense_date'],'eci_claim_date_idx');});
        if(!Schema::hasTable('expense_reimbursements'))Schema::create('expense_reimbursements',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('expense_claim_id')->unique()->constrained('expense_claims')->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->decimal('amount',14,2);$t->string('currency',3);$t->string('method',24)->default('payroll');$t->string('status',24)->default('pending');$t->foreignId('payroll_run_id')->nullable()->constrained('payroll_runs')->nullOnDelete();$t->foreignId('payroll_item_id')->nullable()->constrained('payroll_items')->nullOnDelete();$t->foreignId('payroll_adjustment_id')->nullable()->constrained('payroll_adjustments')->nullOnDelete();$t->timestamp('processed_at')->nullable();$t->timestamps();$t->index(['workspace_id','status'],'er_ws_status_idx');});
        if(!Schema::hasTable('purchase_requests'))Schema::create('purchase_requests',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('requester_member_id')->constrained('workspace_members')->cascadeOnDelete();$t->foreignId('project_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('cost_center_id')->nullable()->constrained('cost_centers')->nullOnDelete();$t->string('request_number',50);$t->string('title',180);$t->string('vendor',160)->nullable();$t->string('currency',3);$t->decimal('amount',14,2);$t->string('status',24)->default('draft');$t->date('needed_by')->nullable();$t->text('justification')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reviewed_at')->nullable();$t->string('purchase_order_number',80)->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['workspace_id','request_number'],'pr_ws_number_uq');$t->index(['workspace_id','status','needed_by'],'pr_ws_status_needed_idx');});
        if(!Schema::hasTable('job_budgets'))Schema::create('job_budgets',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('project_id')->constrained()->cascadeOnDelete();$t->foreignId('cost_center_id')->nullable()->constrained('cost_centers')->nullOnDelete();$t->string('name',140);$t->string('currency',3);$t->decimal('labor_budget',14,2)->default(0);$t->decimal('expense_budget',14,2)->default(0);$t->decimal('procurement_budget',14,2)->default(0);$t->unsignedTinyInteger('alert_threshold_percent')->default(80);$t->string('status',20)->default('active');$t->date('start_date')->nullable();$t->date('end_date')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['workspace_id','project_id','name'],'jb_ws_project_name_uq');$t->index(['workspace_id','status'],'jb_ws_status_idx');});
        if(!Schema::hasTable('project_cost_allocations'))Schema::create('project_cost_allocations',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('project_id')->constrained()->cascadeOnDelete();$t->foreignId('cost_center_id')->constrained('cost_centers')->cascadeOnDelete();$t->decimal('allocation_percent',6,2)->default(100);$t->timestamps();$t->unique(['project_id','cost_center_id'],'pca_project_cc_uq');});
        if(!Schema::hasTable('job_cost_snapshots'))Schema::create('job_cost_snapshots',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('project_id')->constrained()->cascadeOnDelete();$t->date('snapshot_date');$t->string('currency',3);$t->decimal('planned_labor',14,2)->default(0);$t->decimal('actual_labor',14,2)->default(0);$t->decimal('planned_expense',14,2)->default(0);$t->decimal('actual_expense',14,2)->default(0);$t->decimal('planned_procurement',14,2)->default(0);$t->decimal('actual_procurement',14,2)->default(0);$t->decimal('total_planned',14,2)->default(0);$t->decimal('total_actual',14,2)->default(0);$t->decimal('variance',14,2)->default(0);$t->timestamp('generated_at');$t->unique(['project_id','snapshot_date'],'jcs_project_date_uq');$t->index(['workspace_id','snapshot_date'],'jcs_ws_date_idx');});
    }
    /** Handles the down operation for the current WorkIntel workflow. */ public function down():void{foreach(['job_cost_snapshots','project_cost_allocations','job_budgets','purchase_requests','expense_reimbursements','expense_claim_items','expense_claims','expense_policies','cost_centers'] as $table)Schema::dropIfExists($table);}
};
