<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /** Handles the up operation for the current WorkIntel workflow. */ public function up(): void
    {
        foreach ([
            ['Enterprise','enterprise.identity.manage'],['Enterprise','enterprise.scim.manage'],['Enterprise','enterprise.security.manage'],['Enterprise','enterprise.governance.manage'],
        ] as [$group,$slug]) if(Schema::hasTable('permissions')) DB::table('permissions')->updateOrInsert(['slug'=>$slug],['name'=>ucwords(str_replace(['.','_'],' ',$slug)),'group'=>$group]);
        if(Schema::hasTable('roles')&&Schema::hasTable('permissions')&&Schema::hasTable('role_permissions')){$ids=DB::table('permissions')->pluck('id','slug');$ts=Schema::hasColumn('role_permissions','created_at')&&Schema::hasColumn('role_permissions','updated_at');$grant=function(string $r,array $slugs)use($ids,$ts):void{foreach(DB::table('roles')->where('is_system',true)->where('slug',$r)->get(['id']) as $role)foreach($slugs as $slug){$pid=$ids[$slug]??null;if(!$pid)continue;$row=['role_id'=>$role->id,'permission_id'=>$pid];if($ts)$row+=['created_at'=>now(),'updated_at'=>now()];DB::table('role_permissions')->insertOrIgnore($row);}};foreach(['owner','admin'] as $r)$grant($r,['enterprise.identity.manage','enterprise.scim.manage','enterprise.security.manage','enterprise.governance.manage']);}

        if(!Schema::hasTable('enterprise_identity_providers'))Schema::create('enterprise_identity_providers',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name',140);$t->string('type',20);$t->string('status',20)->default('inactive');$t->json('domains')->nullable();$t->text('config_encrypted');$t->boolean('enforce_login')->default(false);$t->boolean('jit_provisioning')->default(false);$t->string('default_role_slug',80)->default('employee');$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['workspace_id','type','status'],'eip_ws_type_status_idx');});
        if(!Schema::hasTable('enterprise_sso_states'))Schema::create('enterprise_sso_states',function(Blueprint $t){$t->id();$t->char('state_hash',64)->unique();$t->foreignId('enterprise_identity_provider_id')->constrained('enterprise_identity_providers')->cascadeOnDelete();$t->text('code_verifier_encrypted')->nullable();$t->string('nonce',100)->nullable();$t->string('redirect_uri',1000);$t->timestamp('expires_at');$t->timestamp('created_at')->useCurrent();$t->index(['enterprise_identity_provider_id','expires_at'],'ess_provider_exp_idx');});
        if(!Schema::hasTable('scim_access_tokens'))Schema::create('scim_access_tokens',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name',120);$t->char('token_hash',64)->unique();$t->string('token_prefix',18);$t->json('scopes')->nullable();$t->timestamp('last_used_at')->nullable();$t->ipAddress('last_used_ip')->nullable();$t->timestamp('expires_at')->nullable();$t->timestamp('revoked_at')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('created_at')->useCurrent();$t->index(['workspace_id','revoked_at'],'sat_ws_revoked_idx');});
        if(!Schema::hasTable('user_mfa_methods'))Schema::create('user_mfa_methods',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('type',20)->default('totp');$t->text('secret_encrypted');$t->json('recovery_code_hashes')->nullable();$t->timestamp('confirmed_at')->nullable();$t->timestamp('last_used_at')->nullable();$t->timestamps();$t->unique(['user_id','type'],'umm_user_type_uq');});
        if(!Schema::hasTable('workspace_security_policies'))Schema::create('workspace_security_policies',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->unique()->constrained()->cascadeOnDelete();$t->boolean('require_mfa')->default(false);$t->json('mfa_role_slugs')->nullable();$t->unsignedInteger('session_ttl_minutes')->default(720);$t->unsignedSmallInteger('max_active_sessions')->default(10);$t->boolean('allow_password_login')->default(true);$t->boolean('require_sso')->default(false);$t->unsignedTinyInteger('password_min_length')->default(12);$t->boolean('block_compromised_devices')->default(false);$t->timestamps();});
        if(!Schema::hasTable('workspace_ip_rules'))Schema::create('workspace_ip_rules',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name',120);$t->string('cidr',64);$t->string('action',10)->default('allow');$t->unsignedSmallInteger('priority')->default(100);$t->boolean('active')->default(true);$t->timestamps();$t->index(['workspace_id','active','priority'],'wir_ws_active_priority_idx');});
        if(!Schema::hasTable('workspace_access_sessions'))Schema::create('workspace_access_sessions',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->char('session_hash',64);$t->ipAddress('ip_address')->nullable();$t->string('user_agent',500)->nullable();$t->timestamp('last_seen_at');$t->timestamp('expires_at')->nullable();$t->timestamp('revoked_at')->nullable();$t->string('revoke_reason',500)->nullable();$t->timestamp('created_at')->useCurrent();$t->unique(['workspace_id','session_hash'],'was_ws_session_uq');$t->index(['workspace_id','user_id','revoked_at'],'was_ws_user_revoked_idx');});
        if(!Schema::hasTable('legal_entities'))Schema::create('legal_entities',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('code',40);$t->string('name',180);$t->char('country_code',2)->nullable();$t->string('registration_number',120)->nullable();$t->string('tax_identifier',120)->nullable();$t->char('currency',3);$t->string('timezone',80)->default('UTC');$t->string('status',20)->default('active');$t->timestamps();$t->unique(['workspace_id','code'],'le_ws_code_uq');});
        if(!Schema::hasTable('business_units'))Schema::create('business_units',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('legal_entity_id')->nullable()->constrained('legal_entities')->nullOnDelete();$t->foreignId('parent_id')->nullable()->constrained('business_units')->nullOnDelete();$t->string('code',40);$t->string('name',160);$t->foreignId('leader_member_id')->nullable()->constrained('workspace_members')->nullOnDelete();$t->string('status',20)->default('active');$t->timestamps();$t->unique(['workspace_id','code'],'bu_ws_code_uq');});
        if(!Schema::hasTable('workspace_access_policies'))Schema::create('workspace_access_policies',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name',140);$t->string('resource',60)->default('workspace');$t->string('action',60)->default('*');$t->string('effect',10)->default('deny');$t->unsignedSmallInteger('priority')->default(100);$t->json('conditions')->nullable();$t->boolean('active')->default(true);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['workspace_id','resource','active','priority'],'wap_ws_res_active_idx');});
        if(!Schema::hasTable('data_governance_policies'))Schema::create('data_governance_policies',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('dataset',80);$t->unsignedInteger('retention_days')->nullable();$t->string('residency_region',80)->nullable();$t->string('storage_class',40)->default('standard');$t->string('deletion_mode',30)->default('soft_then_purge');$t->boolean('legal_hold')->default(false);$t->json('settings')->nullable();$t->timestamps();$t->unique(['workspace_id','dataset'],'dgp_ws_dataset_uq');});
        if(!Schema::hasTable('data_retention_runs'))Schema::create('data_retention_runs',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('dataset',80);$t->timestamp('started_at');$t->timestamp('completed_at')->nullable();$t->unsignedInteger('candidate_count')->default(0);$t->unsignedInteger('deleted_count')->default(0);$t->string('status',20)->default('running');$t->text('error')->nullable();$t->json('metadata')->nullable();$t->index(['workspace_id','started_at'],'drr_ws_started_idx');});
        if(!Schema::hasTable('data_retention_tombstones'))Schema::create('data_retention_tombstones',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('dataset',80);$t->unsignedBigInteger('record_id');$t->timestamp('staged_at');$t->timestamp('purge_after');$t->timestamps();$t->unique(['workspace_id','dataset','record_id'],'drt_ws_dataset_record_uq');$t->index(['workspace_id','dataset','purge_after'],'drt_ws_dataset_purge_idx');});

        if(Schema::hasTable('workspace_members')){if(!Schema::hasColumn('workspace_members','legal_entity_id'))Schema::table('workspace_members',fn(Blueprint $t)=>$t->foreignId('legal_entity_id')->nullable()->after('department_id')->constrained('legal_entities')->nullOnDelete());if(!Schema::hasColumn('workspace_members','business_unit_id'))Schema::table('workspace_members',fn(Blueprint $t)=>$t->foreignId('business_unit_id')->nullable()->after('legal_entity_id')->constrained('business_units')->nullOnDelete());}
        if(Schema::hasTable('projects')){if(!Schema::hasColumn('projects','legal_entity_id'))Schema::table('projects',fn(Blueprint $t)=>$t->foreignId('legal_entity_id')->nullable()->after('client_id')->constrained('legal_entities')->nullOnDelete());if(!Schema::hasColumn('projects','business_unit_id'))Schema::table('projects',fn(Blueprint $t)=>$t->foreignId('business_unit_id')->nullable()->after('legal_entity_id')->constrained('business_units')->nullOnDelete());}
        if(Schema::hasTable('cost_centers')){if(!Schema::hasColumn('cost_centers','legal_entity_id'))Schema::table('cost_centers',fn(Blueprint $t)=>$t->foreignId('legal_entity_id')->nullable()->after('workspace_id')->constrained('legal_entities')->nullOnDelete());if(!Schema::hasColumn('cost_centers','business_unit_id'))Schema::table('cost_centers',fn(Blueprint $t)=>$t->foreignId('business_unit_id')->nullable()->after('legal_entity_id')->constrained('business_units')->nullOnDelete());}
    }
    /** Handles the down operation for the current WorkIntel workflow. */ public function down():void
    {
        if(Schema::hasTable('cost_centers')){foreach(['business_unit_id','legal_entity_id'] as $c)if(Schema::hasColumn('cost_centers',$c))Schema::table('cost_centers',fn(Blueprint $t)=>$t->dropConstrainedForeignId($c));}
        if(Schema::hasTable('projects')){foreach(['business_unit_id','legal_entity_id'] as $c)if(Schema::hasColumn('projects',$c))Schema::table('projects',fn(Blueprint $t)=>$t->dropConstrainedForeignId($c));}
        if(Schema::hasTable('workspace_members')){foreach(['business_unit_id','legal_entity_id'] as $c)if(Schema::hasColumn('workspace_members',$c))Schema::table('workspace_members',fn(Blueprint $t)=>$t->dropConstrainedForeignId($c));}
        foreach(['data_retention_tombstones','data_retention_runs','data_governance_policies','workspace_access_policies','workspace_access_sessions','workspace_ip_rules','workspace_security_policies','user_mfa_methods','scim_access_tokens','enterprise_sso_states','enterprise_identity_providers','business_units','legal_entities'] as $t)Schema::dropIfExists($t);
    }
};
