<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /** Handles the up operation for the current WorkIntel workflow. */ public function up(): void
    {
        foreach ([
            ['Performance', 'performance.view_own'], ['Performance', 'performance.view_team'], ['Performance', 'performance.view_all'],
            ['Performance', 'performance.manage'], ['Performance', 'performance.reviews.manage'], ['Performance', 'performance.skills.manage'],
            ['Performance', 'performance.learning.manage'], ['Performance', 'performance.surveys.manage'], ['Performance', 'performance.compensation.manage'],
        ] as [$group, $slug]) {
            if (Schema::hasTable('permissions')) DB::table('permissions')->updateOrInsert(['slug'=>$slug], ['name'=>ucwords(str_replace(['.','_'],' ',$slug)), 'group'=>$group]);
        }
        if (Schema::hasTable('roles') && Schema::hasTable('permissions') && Schema::hasTable('role_permissions')) {
            $ids=DB::table('permissions')->pluck('id','slug'); $ts=Schema::hasColumn('role_permissions','created_at')&&Schema::hasColumn('role_permissions','updated_at');
            $grant=function(string $roleSlug,array $slugs) use($ids,$ts):void { foreach(DB::table('roles')->where('is_system',true)->where('slug',$roleSlug)->get(['id']) as $role){foreach($slugs as $slug){$pid=$ids[$slug]??null;if(!$pid)continue;$row=['role_id'=>$role->id,'permission_id'=>$pid];if($ts)$row+=['created_at'=>now(),'updated_at'=>now()];DB::table('role_permissions')->insertOrIgnore($row);}}};
            $all=['performance.view_own','performance.view_team','performance.view_all','performance.manage','performance.reviews.manage','performance.skills.manage','performance.learning.manage','performance.surveys.manage','performance.compensation.manage'];
            foreach(['owner','admin','hr'] as $role)$grant($role,$all);
            $grant('manager',['performance.view_own','performance.view_team','performance.manage','performance.reviews.manage','performance.skills.manage','performance.learning.manage']);
            $grant('team-lead',['performance.view_own','performance.view_team','performance.manage','performance.reviews.manage']);
            $grant('payroll-manager',['performance.view_own','performance.compensation.manage']);
            $grant('employee',['performance.view_own']);
        }

        if (!Schema::hasTable('performance_goals')) Schema::create('performance_goals', function(Blueprint $t){
            $t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->foreignId('parent_goal_id')->nullable()->constrained('performance_goals')->nullOnDelete();$t->string('title',180);$t->text('description')->nullable();$t->string('category',40)->default('individual');$t->string('status',24)->default('active');$t->unsignedTinyInteger('progress_percent')->default(0);$t->unsignedTinyInteger('weight')->default(100);$t->decimal('target_value',14,2)->nullable();$t->decimal('current_value',14,2)->nullable();$t->string('unit',40)->nullable();$t->date('start_date')->nullable();$t->date('due_date')->nullable();$t->timestamp('completed_at')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['workspace_id','member_id','status'],'pg_ws_member_status_idx');$t->index(['workspace_id','due_date','status'],'pg_ws_due_status_idx');
        });
        if (!Schema::hasTable('performance_goal_updates')) Schema::create('performance_goal_updates', function(Blueprint $t){$t->id();$t->foreignId('performance_goal_id')->constrained('performance_goals')->cascadeOnDelete();$t->foreignId('member_id')->nullable()->constrained('workspace_members')->nullOnDelete();$t->unsignedTinyInteger('progress_percent');$t->decimal('current_value',14,2)->nullable();$t->text('note')->nullable();$t->timestamp('recorded_at');$t->timestamps();$t->index(['performance_goal_id','recorded_at'],'pgu_goal_recorded_idx');});
        if (!Schema::hasTable('performance_review_cycles')) Schema::create('performance_review_cycles', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name',160);$t->string('review_type',40)->default('annual');$t->string('status',24)->default('draft');$t->date('start_date');$t->date('end_date');$t->boolean('self_review_enabled')->default(true);$t->boolean('manager_review_enabled')->default(true);$t->boolean('calibration_enabled')->default(false);$t->json('questions')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['workspace_id','status','start_date'],'prc_ws_status_start_idx');});
        if (!Schema::hasTable('performance_reviews')) Schema::create('performance_reviews', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('cycle_id')->constrained('performance_review_cycles')->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->foreignId('manager_member_id')->nullable()->constrained('workspace_members')->nullOnDelete();$t->string('status',24)->default('pending');$t->decimal('self_rating',4,2)->nullable();$t->decimal('manager_rating',4,2)->nullable();$t->decimal('overall_rating',4,2)->nullable();$t->text('self_summary')->nullable();$t->text('manager_summary')->nullable();$t->timestamp('self_submitted_at')->nullable();$t->timestamp('manager_submitted_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();$t->unique(['cycle_id','member_id'],'prev_cycle_member_uq');$t->index(['workspace_id','status'],'prev_ws_status_idx');});
        if (!Schema::hasTable('performance_review_answers')) Schema::create('performance_review_answers', function(Blueprint $t){$t->id();$t->foreignId('performance_review_id')->constrained('performance_reviews')->cascadeOnDelete();$t->foreignId('reviewer_member_id')->constrained('workspace_members')->cascadeOnDelete();$t->string('reviewer_type',24);$t->string('question_key',80);$t->string('question_text',255);$t->decimal('rating',4,2)->nullable();$t->text('response')->nullable();$t->timestamps();$t->unique(['performance_review_id','reviewer_member_id','question_key'],'pra_review_reviewer_q_uq');});
        if (!Schema::hasTable('one_on_ones')) Schema::create('one_on_ones', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->foreignId('manager_member_id')->constrained('workspace_members')->cascadeOnDelete();$t->timestamp('scheduled_at');$t->timestamp('occurred_at')->nullable();$t->string('status',24)->default('scheduled');$t->text('agenda')->nullable();$t->text('private_manager_notes')->nullable();$t->json('shared_notes')->nullable();$t->json('action_items')->nullable();$t->timestamp('next_meeting_at')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['workspace_id','member_id','scheduled_at'],'ooo_ws_member_sched_idx');});
        if (!Schema::hasTable('skill_catalog')) Schema::create('skill_catalog', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name',140);$t->string('category',80)->nullable();$t->text('description')->nullable();$t->unsignedTinyInteger('max_proficiency')->default(5);$t->boolean('active')->default(true);$t->timestamps();$t->unique(['workspace_id','name'],'skill_ws_name_uq');});
        if (!Schema::hasTable('member_skills')) Schema::create('member_skills', function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->foreignId('skill_id')->constrained('skill_catalog')->cascadeOnDelete();$t->unsignedTinyInteger('proficiency')->default(1);$t->unsignedTinyInteger('target_proficiency')->nullable();$t->foreignId('assessed_by')->nullable()->constrained('workspace_members')->nullOnDelete();$t->timestamp('assessed_at')->nullable();$t->text('evidence')->nullable();$t->timestamps();$t->unique(['member_id','skill_id'],'ms_member_skill_uq');$t->index(['workspace_id','skill_id','proficiency'],'ms_ws_skill_prof_idx');});
        if (!Schema::hasTable('training_courses')) Schema::create('training_courses', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name',180);$t->string('provider',140)->nullable();$t->text('description')->nullable();$t->decimal('duration_hours',8,2)->default(0);$t->unsignedSmallInteger('validity_months')->nullable();$t->string('status',20)->default('active');$t->timestamps();$t->index(['workspace_id','status'],'tc_ws_status_idx');});
        if (!Schema::hasTable('training_enrollments')) Schema::create('training_enrollments', function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('course_id')->constrained('training_courses')->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->string('status',24)->default('assigned');$t->timestamp('assigned_at')->useCurrent();$t->timestamp('started_at')->nullable();$t->timestamp('completed_at')->nullable();$t->date('expires_on')->nullable();$t->decimal('score',6,2)->nullable();$t->unsignedBigInteger('certificate_document_id')->nullable();$t->foreignId('assigned_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['course_id','member_id'],'te_course_member_uq');$t->index(['workspace_id','expires_on','status'],'te_ws_exp_status_idx');});
        if (!Schema::hasTable('development_plans')) Schema::create('development_plans', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->foreignId('manager_member_id')->nullable()->constrained('workspace_members')->nullOnDelete();$t->string('title',180);$t->text('objective');$t->string('status',24)->default('active');$t->date('start_date')->nullable();$t->date('target_date')->nullable();$t->text('summary')->nullable();$t->timestamps();$t->index(['workspace_id','member_id','status'],'dp_ws_member_status_idx');});
        if (!Schema::hasTable('development_plan_items')) Schema::create('development_plan_items', function(Blueprint $t){$t->id();$t->foreignId('development_plan_id')->constrained('development_plans')->cascadeOnDelete();$t->foreignId('skill_id')->nullable()->constrained('skill_catalog')->nullOnDelete();$t->string('title',180);$t->text('description')->nullable();$t->string('status',24)->default('planned');$t->date('due_date')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();$t->index(['development_plan_id','status'],'dpi_plan_status_idx');});
        if (!Schema::hasTable('recognitions')) Schema::create('recognitions', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('recipient_member_id')->constrained('workspace_members')->cascadeOnDelete();$t->foreignId('sender_member_id')->constrained('workspace_members')->cascadeOnDelete();$t->string('type',40)->default('kudos');$t->string('title',160);$t->text('message');$t->unsignedSmallInteger('points')->default(0);$t->boolean('visible_to_team')->default(true);$t->timestamp('recognized_at')->useCurrent();$t->index(['workspace_id','recipient_member_id','recognized_at'],'rec_ws_recipient_at_idx');});
        if (!Schema::hasTable('pulse_surveys')) Schema::create('pulse_surveys', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('title',180);$t->text('description')->nullable();$t->string('status',20)->default('draft');$t->boolean('anonymous')->default(true);$t->timestamp('opens_at')->nullable();$t->timestamp('closes_at')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['workspace_id','status'],'ps_ws_status_idx');});
        if (!Schema::hasTable('pulse_questions')) Schema::create('pulse_questions', function(Blueprint $t){$t->id();$t->foreignId('pulse_survey_id')->constrained('pulse_surveys')->cascadeOnDelete();$t->unsignedSmallInteger('position')->default(1);$t->string('question',255);$t->string('question_type',24)->default('rating');$t->boolean('required')->default(true);$t->timestamps();$t->index(['pulse_survey_id','position'],'pq_survey_position_idx');});
        if (!Schema::hasTable('pulse_responses')) Schema::create('pulse_responses', function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('pulse_survey_id')->constrained('pulse_surveys')->cascadeOnDelete();$t->foreignId('pulse_question_id')->constrained('pulse_questions')->cascadeOnDelete();$t->foreignId('member_id')->nullable()->constrained('workspace_members')->nullOnDelete();$t->unsignedTinyInteger('rating')->nullable();$t->text('response')->nullable();$t->timestamp('submitted_at')->useCurrent();$t->index(['workspace_id','pulse_survey_id'],'pres_ws_survey_idx');});
        if (!Schema::hasTable('compensation_review_cycles')) Schema::create('compensation_review_cycles', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name',160);$t->date('start_date');$t->date('end_date');$t->string('status',20)->default('draft');$t->string('currency',3)->default('USD');$t->decimal('budget_amount',14,2)->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['workspace_id','status'],'crc_ws_status_idx');});
        if (!Schema::hasTable('compensation_review_items')) Schema::create('compensation_review_items', function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('cycle_id')->constrained('compensation_review_cycles')->cascadeOnDelete();$t->foreignId('member_id')->constrained('workspace_members')->cascadeOnDelete();$t->decimal('current_amount',14,2)->nullable();$t->decimal('proposed_amount',14,2)->nullable();$t->string('currency',3);$t->string('current_title',140)->nullable();$t->string('proposed_title',140)->nullable();$t->string('status',24)->default('draft');$t->text('justification')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reviewed_at')->nullable();$t->timestamps();$t->unique(['cycle_id','member_id'],'cri_cycle_member_uq');$t->index(['workspace_id','status'],'cri_ws_status_idx');});
    }

    /** Handles the down operation for the current WorkIntel workflow. */ public function down(): void
    {
        foreach(['compensation_review_items','compensation_review_cycles','pulse_responses','pulse_questions','pulse_surveys','recognitions','development_plan_items','development_plans','training_enrollments','training_courses','member_skills','skill_catalog','one_on_ones','performance_review_answers','performance_reviews','performance_review_cycles','performance_goal_updates','performance_goals'] as $table) Schema::dropIfExists($table);
    }
};
