<?php
namespace App\Services\Commerce\Providers;
use App\Models\BillingTransaction;use App\Models\CommerceCheckoutSession;use App\Models\CommerceProviderConfig;use App\Models\CommerceRefund;use Illuminate\Http\Request;use Illuminate\Support\Facades\Http;use RuntimeException;use App\Services\Commerce\CommerceUrlGuard;
/** Provides custom http provider behavior within the WorkIntel application. */ class CustomHttpProvider implements CommerceProvider
{
    private CommerceUrlGuard $guard; /** Initializes the class with its required dependencies and state. */ public function __construct(){ $this->guard=new CommerceUrlGuard(); }
    /** Handles the key operation for the current WorkIntel workflow. */ public function key():string{return 'custom_http';}/** Handles the client operation for the current WorkIntel workflow. */ private function client(CommerceProviderConfig $c){$token=$c->credentials['bearer_token']??null;$h=Http::acceptJson()->timeout(15);return $token?$h->withToken($token):$h;}
    /** Handles the test operation for the current WorkIntel workflow. */ public function test(CommerceProviderConfig $c):array{$url=$c->settings['health_url']??null;if(!$url)return ['ok'=>false,'message'=>'Custom provider health_url is missing.'];$this->guard->assertPublicHttps($url);$r=$this->client($c)->get($url);return ['ok'=>$r->successful(),'message'=>$r->successful()?'Custom provider health check passed.':'Custom provider health check failed: '.$r->status()];}
    /** Creates create checkout data for the requested workflow. */ public function createCheckout(CommerceProviderConfig $c,CommerceCheckoutSession $s,string $email):array{$url=$c->settings['checkout_url']??null;if(!$url)throw new RuntimeException('Custom provider checkout_url is missing.');$this->guard->assertPublicHttps($url);$r=$this->client($c)->post($url,['checkout_uuid'=>$s->uuid,'workspace_id'=>$s->workspace_id,'plan'=>$s->plan->slug,'interval'=>$s->billing_interval,'seats'=>$s->seat_quantity,'currency'=>$s->currency,'total'=>(float)$s->total,'buyer_email'=>$email]);if(!$r->successful())throw new RuntimeException('Custom checkout failed: '.$r->status());return ['status'=>'redirect','provider_session_id'=>$r->json('provider_session_id'),'checkout_url'=>$r->json('checkout_url'),'metadata'=>[]];}
    /** Handles the refund operation for the current WorkIntel workflow. */ public function refund(CommerceProviderConfig $c,CommerceRefund $refund,?BillingTransaction $txn):array{$url=$c->settings['refund_url']??null;if(!$url)throw new RuntimeException('Custom provider refund_url is missing.');$this->guard->assertPublicHttps($url);$r=$this->client($c)->post($url,['refund_uuid'=>$refund->uuid,'transaction_id'=>$txn?->provider_transaction_id,'amount'=>(float)$refund->amount,'currency'=>$refund->currency,'reason'=>$refund->reason]);if(!$r->successful())throw new RuntimeException('Custom refund failed: '.$r->status());return ['status'=>$r->json('status')??'processing','provider_refund_id'=>$r->json('provider_refund_id')];}
    /** Handles the verify webhook operation for the current WorkIntel workflow. */ public function verifyWebhook(CommerceProviderConfig $c,Request $request,string $raw):bool{$secret=$c->credentials['webhook_secret']??'';$sig=$request->header('X-WorkIntel-Signature','');return $secret&&$sig&&hash_equals(hash_hmac('sha256',$raw,$secret),$sig);}
    /** Handles the normalize webhook operation for the current WorkIntel workflow. */ public function normalizeWebhook(array $p):?array{return isset($p['event_id'],$p['status'])?['event_id'=>(string)$p['event_id'],'event_type'=>(string)($p['event_type']??'custom'),'checkout_uuid'=>$p['checkout_uuid']??null,'status'=>$p['status'],'provider_transaction_id'=>$p['provider_transaction_id']??null,'provider_subscription_id'=>$p['provider_subscription_id']??null]:null;}
}
