<?php
namespace App\Services\Commerce\Providers;
use App\Models\BillingTransaction;use App\Models\CommerceCheckoutSession;use App\Models\CommerceProviderConfig;use App\Models\CommerceRefund;use Illuminate\Http\Request;use Illuminate\Support\Facades\Http;use RuntimeException;
/** Provides paddle provider behavior within the WorkIntel application. */ class PaddleProvider implements CommerceProvider
{
    /** Handles the key operation for the current WorkIntel workflow. */ public function key():string{return 'paddle';}/** Handles the base operation for the current WorkIntel workflow. */ private function base(CommerceProviderConfig $c):string{return $c->test_mode?'https://sandbox-api.paddle.com':'https://api.paddle.com';}/** Handles the key for operation for the current WorkIntel workflow. */ private function keyFor(CommerceProviderConfig $c):string{$k=$c->credentials['api_key']??'';if(!$k)throw new RuntimeException('Paddle API key is not configured.');return $k;}
    /** Handles the test operation for the current WorkIntel workflow. */ public function test(CommerceProviderConfig $c):array{$r=Http::withToken($this->keyFor($c))->get($this->base($c).'/products?per_page=1');return ['ok'=>$r->successful(),'message'=>$r->successful()?'Paddle API credentials verified.':'Paddle connection failed: '.$r->status()];}
    /** Creates create checkout data for the requested workflow. */ public function createCheckout(CommerceProviderConfig $c,CommerceCheckoutSession $s,string $email):array{$key=$s->plan->slug.'.'.$s->billing_interval;$price=$c->settings['price_map'][$key]??null;if(!$price)throw new RuntimeException("Paddle price mapping missing for {$key}.");$payload=['items'=>[['price_id'=>$price,'quantity'=>$s->seat_quantity]],'collection_mode'=>'automatic','custom_data'=>['checkout_uuid'=>$s->uuid,'workspace_id'=>$s->workspace_id]];$r=Http::withToken($this->keyFor($c))->post($this->base($c).'/transactions',$payload);if(!$r->successful())throw new RuntimeException('Paddle checkout failed: '.$r->status());$d=$r->json('data')??[];return ['status'=>'redirect','provider_session_id'=>$d['id']??null,'checkout_url'=>$d['checkout']['url']??null,'metadata'=>[]];}
    /** Handles the refund operation for the current WorkIntel workflow. */ public function refund(CommerceProviderConfig $c,CommerceRefund $refund,?BillingTransaction $txn):array{$tx=$txn?->provider_transaction_id;if(!$tx)throw new RuntimeException('A Paddle transaction is required.');$r=Http::withToken($this->keyFor($c))->post($this->base($c).'/adjustments',['action'=>'refund','transaction_id'=>$tx,'reason'=>'other','items'=>[]]);if(!$r->successful())throw new RuntimeException('Paddle refund failed: '.$r->status());return ['status'=>'processing','provider_refund_id'=>$r->json('data.id')];}
    /** Handles the verify webhook operation for the current WorkIntel workflow. */ public function verifyWebhook(CommerceProviderConfig $c,Request $request,string $raw):bool{$secret=$c->credentials['webhook_secret']??'';$header=$request->header('Paddle-Signature','');if(!$secret||!$header)return false;$parts=[];foreach(explode(';',$header) as $part){[$k,$v]=array_pad(explode('=',$part,2),2,null);if($k&&$v)$parts[$k][]=$v;}$ts=(int)($parts['ts'][0]??0);if(!$ts||abs(time()-$ts)>300)return false;$expected=hash_hmac('sha256',$ts.':'.$raw,$secret);foreach($parts['h1']??[] as $sig)if(hash_equals($expected,$sig))return true;return false;}
    /** Handles the normalize webhook operation for the current WorkIntel workflow. */ public function normalizeWebhook(array $p):?array{$type=$p['event_type']??'';$d=$p['data']??[];if($type==='transaction.completed')return ['event_id'=>$p['event_id']??sha1(json_encode($p)),'event_type'=>$type,'checkout_uuid'=>$d['custom_data']['checkout_uuid']??null,'status'=>'completed','provider_transaction_id'=>$d['id']??null,'provider_subscription_id'=>$d['subscription_id']??null];if($type==='transaction.payment_failed')return ['event_id'=>$p['event_id']??sha1(json_encode($p)),'event_type'=>$type,'status'=>'payment_failed','provider_subscription_id'=>$d['subscription_id']??null];return null;}
}
