<?php
namespace App\Services\Commerce\Providers;
use App\Models\BillingTransaction;use App\Models\CommerceCheckoutSession;use App\Models\CommerceProviderConfig;use App\Models\CommerceRefund;use Illuminate\Http\Request;use Illuminate\Support\Facades\Http;use RuntimeException;
/** Provides pay pal provider behavior within the WorkIntel application. */ class PayPalProvider implements CommerceProvider
{
    /** Handles the key operation for the current WorkIntel workflow. */ public function key():string{return 'paypal';}/** Handles the base operation for the current WorkIntel workflow. */ private function base(CommerceProviderConfig $c):string{return $c->test_mode?'https://api-m.sandbox.paypal.com':'https://api-m.paypal.com';}
    /** Handles the token operation for the current WorkIntel workflow. */ private function token(CommerceProviderConfig $c):string{$id=$c->credentials['client_id']??'';$secret=$c->credentials['client_secret']??'';if(!$id||!$secret)throw new RuntimeException('PayPal client credentials are not configured.');$r=Http::withBasicAuth($id,$secret)->asForm()->post($this->base($c).'/v1/oauth2/token',['grant_type'=>'client_credentials']);if(!$r->successful())throw new RuntimeException('PayPal authentication failed.');return $r->json('access_token');}
    /** Handles the test operation for the current WorkIntel workflow. */ public function test(CommerceProviderConfig $c):array{try{$this->token($c);return ['ok'=>true,'message'=>'PayPal API credentials verified.'];}catch(\Throwable $e){return ['ok'=>false,'message'=>$e->getMessage()];}}
    /** Creates create checkout data for the requested workflow. */ public function createCheckout(CommerceProviderConfig $c,CommerceCheckoutSession $s,string $email):array{$key=$s->plan->slug.'.'.$s->billing_interval;$plan=$c->settings['price_map'][$key]??null;if(!$plan)throw new RuntimeException("PayPal plan mapping missing for {$key}.");$r=Http::withToken($this->token($c))->post($this->base($c).'/v1/billing/subscriptions',['plan_id'=>$plan,'quantity'=>(string)$s->seat_quantity,'custom_id'=>$s->uuid,'subscriber'=>['email_address'=>$email],'application_context'=>['return_url'=>$c->settings['success_url']??config('app.url').'/app?checkout=success','cancel_url'=>$c->settings['cancel_url']??config('app.url').'/app?checkout=cancel']]);if(!$r->successful())throw new RuntimeException('PayPal checkout failed: '.$r->status());$j=$r->json();$url=collect($j['links']??[])->firstWhere('rel','approve')['href']??null;return ['status'=>'redirect','provider_session_id'=>$j['id']??null,'checkout_url'=>$url,'metadata'=>[]];}
    /** Handles the refund operation for the current WorkIntel workflow. */ public function refund(CommerceProviderConfig $c,CommerceRefund $refund,?BillingTransaction $txn):array{$capture=$txn?->provider_transaction_id;if(!$capture)throw new RuntimeException('A PayPal capture transaction is required.');$r=Http::withToken($this->token($c))->post($this->base($c)."/v2/payments/captures/{$capture}/refund",['amount'=>['value'=>number_format((float)$refund->amount,2,'.',''),'currency_code'=>$refund->currency]]);if(!$r->successful())throw new RuntimeException('PayPal refund failed: '.$r->status());return ['status'=>'succeeded','provider_refund_id'=>$r->json('id')];}
    /** Handles the verify webhook operation for the current WorkIntel workflow. */ public function verifyWebhook(CommerceProviderConfig $c,Request $request,string $raw):bool{$webhookId=$c->credentials['webhook_id']??'';if(!$webhookId)return false;try{$payload=json_decode($raw,true,512,JSON_THROW_ON_ERROR);$r=Http::withToken($this->token($c))->post($this->base($c).'/v1/notifications/verify-webhook-signature',['auth_algo'=>$request->header('PAYPAL-AUTH-ALGO'),'cert_url'=>$request->header('PAYPAL-CERT-URL'),'transmission_id'=>$request->header('PAYPAL-TRANSMISSION-ID'),'transmission_sig'=>$request->header('PAYPAL-TRANSMISSION-SIG'),'transmission_time'=>$request->header('PAYPAL-TRANSMISSION-TIME'),'webhook_id'=>$webhookId,'webhook_event'=>$payload]);return $r->successful()&&$r->json('verification_status')==='SUCCESS';}catch(\Throwable){return false;}}
    /** Handles the normalize webhook operation for the current WorkIntel workflow. */ public function normalizeWebhook(array $p):?array{$type=$p['event_type']??'';$r=$p['resource']??[];if(in_array($type,['BILLING.SUBSCRIPTION.ACTIVATED','BILLING.SUBSCRIPTION.CREATED'],true))return ['event_id'=>$p['id']??sha1(json_encode($p)),'event_type'=>$type,'checkout_uuid'=>$r['custom_id']??null,'status'=>'completed','provider_subscription_id'=>$r['id']??null];if($type==='BILLING.SUBSCRIPTION.PAYMENT.FAILED')return ['event_id'=>$p['id']??sha1(json_encode($p)),'event_type'=>$type,'status'=>'payment_failed','provider_subscription_id'=>$r['id']??null];return null;}
}
