import { useEffect, useMemo, useState } from 'react'
import { BarChart3, FileChartColumnIncreasing, RefreshCw, ShieldAlert } from 'lucide-react'
import { canAccessPage } from '../access'
import { apiRequest } from '../api/client'
import type { AuthWorkspace } from '../auth/types'
import type { Page } from '../components/Sidebar'
import { Alert, Button, Card, CardBody, CardHeader, EmptyState, Grid, Inline, Stack, StatCard, Text } from '../design-system'

type IntelligenceSummary={stats?:{open:number;critical:number;danger:number;warning:number};latest_run?:{status:string;completed_at:string|null}|null}
type ReportSummary={data?:Array<{id:number;is_shared?:boolean;last_run_at?:string|null}>}
type Snapshot={insights:IntelligenceSummary|null;reports:ReportSummary|null}
const emptySnapshot:Snapshot={insights:null,reports:null}

/** Render explainable intelligence and reporting readiness for the current role. */
export default function IntelligenceHome({workspace,onNavigate}:{workspace:AuthWorkspace;onNavigate:(page:Page)=>void}){
 const [snapshot,setSnapshot]=useState<Snapshot>(emptySnapshot);const [loading,setLoading]=useState(true);const [warning,setWarning]=useState('');const access=useMemo(()=>({insights:canAccessPage(workspace,'insights'),reports:canAccessPage(workspace,'reports')}),[workspace])
 /** Load insights and report inventory independently to keep discovery resilient. */
 const load=async()=>{setLoading(true);setWarning('');const requests:Array<Promise<{kind:keyof Snapshot;value:unknown}>>=[];if(access.insights)requests.push(apiRequest<IntelligenceSummary>('/api/v1/intelligence/overview',{workspaceId:workspace.id,silent:true}).then(value=>({kind:'insights' as const,value})));if(access.reports)requests.push(apiRequest<ReportSummary>('/api/v1/reports/saved',{workspaceId:workspace.id,silent:true}).then(value=>({kind:'reports' as const,value})));const results=await Promise.allSettled(requests);const next:Snapshot={...emptySnapshot};let failed=0;for(const result of results){if(result.status==='rejected'){failed++;continue}next[result.value.kind]=result.value.value as never}setSnapshot(next);if(failed)setWarning('Some intelligence or report summary data could not be loaded. Available analysis pages remain accessible below.');setLoading(false)}
 useEffect(()=>{void load()},[workspace.id,access.insights,access.reports])
 const high=Number(snapshot.insights?.stats?.critical??0)+Number(snapshot.insights?.stats?.danger??0);const reports=snapshot.reports?.data??[];const shared=reports.filter(row=>row.is_shared).length;const hasData=access.insights||access.reports
 return <Stack gap={12}><Card><CardHeader title="Intelligence & reports snapshot" description="Explain workforce signals, then turn trusted operational data into saved and repeatable reports." action={<Button size="sm" variant="ghost" loading={loading} onClick={()=>void load()}><RefreshCw size={13}/> Refresh</Button>}/><CardBody>{warning&&<Alert tone="warning">{warning}</Alert>}{!hasData?<EmptyState title="No intelligence or reporting areas are available for this role." text="Your permissions and plan determine which analysis surfaces you can use." contextualHelp/>:<Grid columns="repeat(auto-fit,minmax(160px,1fr))" gap={9}>{access.insights&&<><StatCard label="Open signals" value={loading?'…':String(snapshot.insights?.stats?.open??0)} sub={`${high} high-severity signal(s)`}/><StatCard label="Warnings" value={loading?'…':String(snapshot.insights?.stats?.warning??0)} sub={snapshot.insights?.latest_run?.status??'No latest run'}/></>}{access.reports&&<><StatCard label="Saved reports" value={loading?'…':String(reports.length)} sub={`${shared} shared with workspace`}/><StatCard label="Recently run" value={loading?'…':String(reports.filter(row=>row.last_run_at).length)} sub="Saved definitions with history"/></>}</Grid>}</CardBody></Card><Grid columns="repeat(auto-fit,minmax(260px,1fr))" gap={9}>{access.insights&&<Card><CardHeader title="Workforce Intelligence" description="Explainable signals, capacity evidence, project risk and configurable thresholds."/><CardBody><Stack gap={8}><Inline gap={8} align="center">{high?<ShieldAlert size={15}/>:<BarChart3 size={15}/>}<Text color="var(--text-2)">{high?`${high} high-severity signal(s) need review.`:'No high-severity signal in the current snapshot.'}</Text></Inline><Button size="sm" variant="outline" onClick={()=>onNavigate('insights')}>Open Intelligence</Button></Stack></CardBody></Card>}{access.reports&&<Card><CardHeader title="Reports" description="Build, save, schedule, run and export operational reports."/><CardBody><Stack gap={8}><Inline gap={8} align="center"><FileChartColumnIncreasing size={15}/><Text color="var(--text-2)">{reports.length} saved report definition(s) are visible.</Text></Inline><Button size="sm" variant="outline" onClick={()=>onNavigate('reports')}>Open Reports</Button></Stack></CardBody></Card>}</Grid></Stack>
}
