<?php
namespace App\Services\Payroll;
use App\Models\CompensationProfile;use App\Models\PayrollCompliancePack;use App\Models\PayrollComplianceRule;use App\Models\TerminationSettlement;use App\Models\WorkspaceMember;use Carbon\Carbon;use Illuminate\Support\Str;
/** Provides termination settlement service behavior within the WorkIntel application. */ class TerminationSettlementService{
 /** Handles the preview operation for the current WorkIntel workflow. */ public function preview(WorkspaceMember $member,Carbon $terminationDate,?PayrollCompliancePack $pack=null,array $overrides=[]):TerminationSettlement{
  $profile=CompensationProfile::query()->where('workspace_id',$member->workspace_id)->where('member_id',$member->id)->whereDate('effective_from','<=',$terminationDate->toDateString())->where(fn($q)=>$q->whereNull('effective_to')->orWhereDate('effective_to','>=',$terminationDate->toDateString()))->orderByDesc('effective_from')->firstOrFail();
  $joining=$member->joining_date?Carbon::parse($member->joining_date):$terminationDate;$years=max(0,$joining->diffInDays($terminationDate)/365.2425);$daily=$this->dailyEquivalent($profile);$daysPerYear=(float)($overrides['days_per_service_year']??$pack?->settings['termination_days_per_service_year']??0);$base=round($years*$daily*$daysPerYear,2);$leave=(float)($overrides['leave_payout']??0);$other=(float)($overrides['other_earnings']??0);$deductions=(float)($overrides['deductions']??0);$total=max(0,round($base+$leave+$other-$deductions,2));
  return TerminationSettlement::create(['uuid'=>(string)Str::uuid(),'workspace_id'=>$member->workspace_id,'member_id'=>$member->id,'payroll_compliance_pack_id'=>$pack?->id,'currency'=>$profile->currency,'termination_date'=>$terminationDate->toDateString(),'service_years'=>round($years,3),'base_amount'=>$base,'leave_payout'=>$leave,'other_earnings'=>$other,'deductions'=>$deductions,'total_amount'=>$total,'status'=>'draft','calculation_snapshot'=>['profile_id'=>$profile->id,'daily_equivalent'=>$daily,'days_per_service_year'=>$daysPerYear,'pack'=>$pack?->only(['id','name','version','country_code']),'note'=>'Generic configurable termination estimate. Legal/statutory review is required before approval.']]);
 }
 /** Handles the daily equivalent operation for the current WorkIntel workflow. */ private function dailyEquivalent(CompensationProfile $p):float{return match($p->pay_type){'daily'=>(float)$p->daily_rate,'hourly'=>(float)$p->hourly_rate*(float)$p->standard_hours_per_day,'monthly'=>(float)$p->monthly_salary/30,'yearly'=>(float)$p->annual_salary/365,default=>(float)($p->project_rate??0)};}
}
