export type Client = {
    id: number;
    name: string;
    company_name: string | null;
    email: string | null;
    billing_email: string | null;
    phone: string | null;
    billing_address: string | null;
    tax_id: string | null;
    currency: string;
    billing_rate: string | null;
    status: string;
    projects_count: number;
    active_projects_count?: number;
    portal_accounts_count?: number;
    invoices_count?: number;
    reports_count?: number;
};
export type Project = {
    id: number;
    client_id: number | null;
    name: string;
    status: string;
};
export type InvoiceLine = {
    id: number;
    project_id: number | null;
    description: string;
    quantity: string | number;
    unit_price: string | number;
    amount: string | number;
    source_type: string;
    project?: Project | null;
};
export type Payment = {
    id: number;
    amount: string | number;
    currency: string;
    method: string;
    reference: string | null;
    paid_on: string;
    note: string | null;
};
export type Invoice = {
    id: number;
    uuid: string;
    client_id: number;
    client?: Client;
    number: string;
    status: string;
    currency: string;
    issue_date: string;
    due_date: string;
    period_start: string | null;
    period_end: string | null;
    subtotal: string | number;
    discount_total: string | number;
    tax_percent: string | number;
    tax_total: string | number;
    total: string | number;
    amount_paid: string | number;
    amount_due: string | number;
    notes: string | null;
    terms: string | null;
    lines?: InvoiceLine[];
    payments?: Payment[];
};
export type ClientReport = {
    id: number;
    uuid: string;
    client_id: number;
    client?: Client;
    project_id: number | null;
    project?: Project | null;
    name: string;
    report_type: string;
    period_start: string | null;
    period_end: string | null;
    snapshot: Record<string, any>;
    note: string | null;
    published_at: string | null;
};
export type PortalAccount = {
    id: number;
    name: string;
    email: string;
    status: string;
    activated_at: string | null;
    last_login_at: string | null;
};
export type PortalInvite = {
    id: number;
    name: string;
    email: string;
    expires_at: string;
    accepted_at: string | null;
    created_at: string;
};
export type ClientForm = {
    name: string;
    company_name: string;
    email: string;
    billing_email: string;
    phone: string;
    billing_address: string;
    tax_id: string;
    currency: string;
    billing_rate: string;
    status: string;
};
export const emptyClient: ClientForm = { name: '', company_name: '', email: '', billing_email: '', phone: '', billing_address: '', tax_id: '', currency: 'USD', billing_rate: '', status: 'active' };
/** Handles the money operation for the WorkIntel client. */ export const money = (value: number | string, currency: string) => new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 2 }).format(Number(value ?? 0));
/** Handles the dt operation for the WorkIntel client. */ export const dt = (value: string | null) => value ? new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value.includes('T') ? value : `${value}T00:00:00`)) : '—';
