<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/** Defines one platform-level metric threshold used by the observability evaluator. */
class SystemObservabilityAlertRule extends Model
{
    protected $fillable=['key','name','metric_key','operator','threshold','window_minutes','severity','enabled','cooldown_minutes','channels','updated_by','last_triggered_at'];

    /** Define rule numeric, boolean, collection and timestamp casts. */
    protected function casts(): array { return ['threshold'=>'decimal:3','enabled'=>'boolean','channels'=>'array','last_triggered_at'=>'datetime']; }

    /** Return the operator that last changed the rule. */
    public function updater(): BelongsTo { return $this->belongsTo(User::class,'updated_by'); }

    /** Return alert incidents generated by this rule. */
    public function alerts(): HasMany { return $this->hasMany(SystemObservabilityAlert::class,'alert_rule_id'); }
}
