import { useEffect, useState, type FormEvent } from 'react'
import { ArrowRight } from 'lucide-react'
import { apiRequest } from '../../api/client'
import { Alert, Button, Field, Input, Form, LoadingState } from '../../design-system'
import { AuthBackButton, AuthHeading, AuthMobileBrand } from './AuthPrimitives'

type JoinPolicy={workspace:{name:string;slug:string};mode:string;require_email_verification:boolean;allow_existing_users:boolean}
type InviteInfo={workspace:{name:string;slug:string};email:string|null;role_slug:string;expires_at:string}
/** Handles the join workspace operation for the WorkIntel client. */ export default function JoinWorkspace({workspaceSlug,inviteToken,onLogin,productName='WorkIntel'}:{workspaceSlug?:string;inviteToken?:string;onLogin:()=>void;productName?:string}){
 const [meta,setMeta]=useState<JoinPolicy|InviteInfo|null>(null),[first,setFirst]=useState(''),[last,setLast]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('')
 useEffect(()=>{setBusy(true);const url=inviteToken?`/api/v1/auth/invitations/${encodeURIComponent(inviteToken)}`:`/api/v1/auth/join/${encodeURIComponent(workspaceSlug||'')}/policy`;apiRequest<any>(url).then(r=>{const value=inviteToken?r.data:r;setMeta(value);if(value.email)setEmail(value.email)}).catch(e=>setError(e instanceof Error?e.message:'This registration link is unavailable.')).finally(()=>setBusy(false))},[workspaceSlug,inviteToken])
 /** Handles the submit operation for the WorkIntel client. */ const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{if(inviteToken){const r=await apiRequest<{message:string}>(`/api/v1/auth/invitations/${encodeURIComponent(inviteToken)}/accept`,{method:'POST',body:JSON.stringify({first_name:first,last_name:last,email,password,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})});setMessage(r.message)}else{const r=await apiRequest<{message:string}>(`/api/v1/auth/join/${encodeURIComponent(workspaceSlug||'')}`,{method:'POST',body:JSON.stringify({first_name:first,last_name:last,email,password,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})});setMessage(r.message)}}catch(e){setError(e instanceof Error?e.message:'Could not join workspace.')}finally{setBusy(false)}}
 const workspaceName=meta?.workspace.name||'workspace';const mode='mode' in (meta||{})?(meta as JoinPolicy).mode:'invite'
 const blocked=!inviteToken&&['disabled','invite_only','invite_link','sso_only'].includes(mode)
 return <><AuthMobileBrand productName={productName}/><AuthBackButton onClick={onLogin}/><AuthHeading kicker="Join workspace" title={busy&&!meta?'Preparing workspace access…':`Join ${workspaceName}`} description={inviteToken?'Accept your workspace invitation. Existing users should enter their current password.':'Create or connect your account according to this workspace registration policy.'}/>{busy&&!meta&&<LoadingState compact title="Loading registration policy…" text="Checking how this workspace accepts new members."/>}{error&&<Alert tone="danger">{error}</Alert>}{message?<><Alert tone="success">{message}</Alert><Button variant="primary" size="lg" onClick={onLogin}>Continue to sign in</Button></>:blocked?<Alert tone="warning">Self-registration is not enabled for this workspace. Ask an administrator for an invitation or use enterprise SSO.</Alert>:<Form className="auth-form" onSubmit={submit}><div className="auth-form__grid"><Field label="First name"><Input value={first} onChange={e=>setFirst(e.target.value)} required={!email||!inviteToken}/></Field><Field label="Last name"><Input value={last} onChange={e=>setLast(e.target.value)} required={!email||!inviteToken}/></Field></div><Field label="Email"><Input type="email" value={email} onChange={e=>setEmail(e.target.value)} readOnly={Boolean(inviteToken&&(meta as InviteInfo)?.email)} required/></Field><Field label={inviteToken?'Password / current account password':'Password'}><Input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></Field><Button variant="primary" size="lg" type="submit" disabled={busy}>{busy?'Processing…':<>Continue <ArrowRight size={15}/></>}</Button></Form>}</>
}
